<?php

declare(strict_types=1);

namespace ArazzoDocs\AggregateMapDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Aggregate Map

Where mutable state lives, and which of it crosses process boundaries:

1. **Immutability profile** — readonly value objects vs mutable types per
   package (the spec layer is deliberately all-readonly).
2. **Mutable clusters** — every non-readonly class; these are the candidate
   aggregate roots and entities Evans would ask you to justify.
3. **Cross-process aggregates** — mutable state serialized through queue jobs
   or persistence payloads: consistency guarantees must be explicit there.

MD;

/**
 * @param  array<string, list<ScannedFile>>  $core
 * @param  array<string, list<ScannedFile>>  $laravel
 */
function render(array $core, array $laravel): string
{
    $files = [];
    foreach ([['core', $core], ['laravel', $laravel]] as [$package, $modules]) {
        foreach ($modules as $moduleFiles) {
            foreach ($moduleFiles as $file) {
                $files[$package][$file->namespace.'\\'.$file->className] = $file;
            }
        }
    }

    $lines = [BANNER];

    // --- immutability profile ---
    $lines[] = '## Immutability profile';
    $lines[] = '';
    $lines[] = '| Package | Readonly | Mutable | Readonly share |';
    $lines[] = '|---|---:|---:|---:|';
    $profile = [];
    foreach (['core', 'laravel'] as $package) {
        $readonly = 0;
        $mutable = 0;
        foreach ($files[$package] ?? [] as $file) {
            if ($file->isInterface || !isClass($file)) {
                continue;
            }
            if (isReadonly($file->content)) {
                $readonly++;
            } else {
                $mutable++;
            }
        }
        $profile[$package] = [$readonly, $mutable];
        $total = $readonly + $mutable;
        $share = $total > 0 ? sprintf('%.0f%%', $readonly / $total * 100) : '—';
        $lines[] = sprintf('| %s | %d | %d | %s |', $package, $readonly, $mutable, $share);
    }
    $lines[] = '';

    // --- mutable clusters ---
    $lines[] = '## Mutable clusters';
    $lines[] = '';
    $lines[] = '| Class | Package | Dir | Serialization signals |';
    $lines[] = '|---|---|---|---|';

    $crossProcess = [];
    foreach (['core', 'laravel'] as $package) {
        foreach ($files[$package] ?? [] as $fqcn => $file) {
            if ($file->isInterface || !isClass($file) || isReadonly($file->content)) {
                continue;
            }
            $signals = serializationSignals($file);
            if ($signals !== []) {
                $crossProcess[$fqcn] = ['package' => $package, 'signals' => $signals];
            }
            $signalCells = $signals === []
                ? ''
                : implode(', ', array_map(fn (string $s): string => '`'.$s.'`', $signals));
            if ($signalCells === '') {
                continue; // keep the table focused on stateful types with IO signals
            }
            $lines[] = sprintf(
                '| `%s` | %s | `%s` | %s |',
                short($fqcn),
                $package,
                str_replace('\\', '/', $file->relativeDir),
                $signalCells,
            );
        }
    }

    // --- cross process ---
    $lines[] = '';
    $lines[] = '## Cross-process aggregates';
    $lines[] = '';
    $lines[] = 'Mutable types that serialize themselves or are carried by queue jobs —'
        .' each needs an explicit consistency story (versioning, TTLs, idempotency):';
    $lines[] = '';
    ksort($crossProcess);
    foreach ($crossProcess as $fqcn => $meta) {
        $lines[] = sprintf(
            '- `%s` <small>%s · %s</small>',
            short((string) $fqcn),
            $meta['package'],
            implode(', ', array_map(fn (string $s): string => '`'.$s.'`', $meta['signals'])),
        );
    }
    if ($crossProcess === []) {
        $lines[] = '_None detected._';
    }

    return implode("\n", $lines)."\n";
}

function isClass(ScannedFile $file): bool
{
    return preg_match('/^(?:(?:abstract|final|readonly)\s+)*class\s/m', $file->content) === 1;
}

function isReadonly(string $content): bool
{
    return preg_match('/^(?:(?:abstract\s+)?(?:final\s+)?readonly\s+(?:final\s+)?|(?:final\s+)?readonly\s+)class\s/m', $content) === 1;
}

/** @return list<string> */
function serializationSignals(ScannedFile $file): array
{
    $signals = [];
    $patterns = [
        'serialize' => '/public\s+function\s+serialize\s*\(/',
        'toArray' => '/public\s+function\s+to(?:Array|Payload|Row|Context)\s*\(/',
        'hydrate' => '/public\s+(?:static\s+)?function\s+(?:from|hydrate)\w*\s*\(/',
        '__sleep' => '/function\s+__sleep\s*\(/',
    ];
    foreach ($patterns as $name => $pattern) {
        if (preg_match($pattern, $file->content) === 1) {
            $signals[] = $name;
        }
    }

    return $signals;
}

function short(string $fqcn): string
{
    $parts = explode('\\', $fqcn);

    return end($parts);
}
