<?php

declare(strict_types=1);

namespace ArazzoDocs\BcDiffDoc;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Breaking-Change Report

Compares the current generated public API surface (`docs/generated/public-api.md`)
against the same file at the previous release tag. Any removal or signature
change is listed here in full — this file is the release gate for backwards
compatibility.

Override the comparison tag with `ARAZZO_BC_TAG=<tag>`; default is the latest
tag (or the second-latest when HEAD sits exactly on a tag).

MD;

/**
 * classKey => ['kind' => string, 'methods' => [name => signature],
 *              'constants' => list<string>, 'cases' => list<string>]
 *
 * @return array<string, array{kind: string, methods: array<string, string>, constants: list<string>, cases: list<string>}>
 */
function parseApiMarkdown(string $content): array
{
    $classes = [];
    $current = null;

    foreach (explode("\n", $content) as $line) {
        if (preg_match('/^### `([\w~]+)` (.+)$/', trim($line), $m) === 1) {
            $current = $m[1];
            $classes[$current] = ['kind' => trim($m[2]), 'methods' => [], 'constants' => [], 'cases' => []];

            continue;
        }
        if ($current === null || !str_starts_with(trim($line), '- ')) {
            continue;
        }
        $entry = substr(trim($line), 2);
        if (preg_match('/^`(.+)$/', $entry, $sig) === 1) {
            $signature = rtrim($sig[1], '`');
            if (preg_match('/function\s+(\w+)/', $signature, $fn) === 1) {
                $classes[$current]['methods'][$fn[1]] = $signature;
            }

            continue;
        }
        if (preg_match('/^Constants:\s*(.+)$/', $entry, $c) === 1) {
            foreach (explode(', ', $c[1]) as $constant) {
                $classes[$current]['constants'][] = trim($constant, '`');
            }
        }
        if (preg_match('/^Cases:\s*(.+)$/', $entry, $c) === 1) {
            foreach (explode(', ', $c[1]) as $case) {
                $classes[$current]['cases'][] = trim($case, '`');
            }
        }
    }

    ksort($classes);

    return $classes;
}

function render(string $root): string
{
    [$tag, $reason] = resolveTag($root);
    if ($tag === null) {
        return BANNER.sprintf("_No comparison tag available (%s). Tag a release to enable this report._\n", $reason);
    }

    $oldContent = shell_exec(
        'git -C '.escapeshellarg($root).' show '.escapeshellarg($tag.':docs/generated/public-api.md').' 2>/dev/null',
    );
    if (!is_string($oldContent) || $oldContent === '') {
        return BANNER.sprintf("_Tag `%s` has no docs/generated/public-api.md — report unavailable._\n", $tag);
    }

    $old = parseApiMarkdown($oldContent);
    $new = parseApiMarkdown((string) file_get_contents($root.'/docs/generated/public-api.md'));

    [$breakingRows, $addedRows] = diff($old, $new);

    $lines = [BANNER];
    $lines[] = sprintf('Comparing `%s` → working tree.', $tag);
    $lines[] = '';

    if ($breakingRows === []) {
        $lines[] = '**No breaking changes.**';
    } else {
        $lines[] = sprintf('**%d breaking change(s):**', count($breakingRows));
        $lines[] = '';
        $lines[] = '| Kind | Class | Member | Detail |';
        $lines[] = '|---|---|---|---|';
        usort($breakingRows, fn (array $a, array $b): int => strcmp($a[0].$a[1].$a[2], $b[0].$b[1].$b[2]));
        foreach ($breakingRows as [$kind, $class, $member, $detail]) {
            $lines[] = sprintf('| %s | `%s` | %s | %s |', $kind, $class, $member !== '' ? '`'.$member.'`' : '—', $detail);
        }
    }

    if ($addedRows !== []) {
        $lines[] = '';
        $lines[] = sprintf('**Additions (non-breaking):** %d', count($addedRows));
        $lines[] = '';
        $lines[] = '| Kind | Class | Member |';
        $lines[] = '|---|---|---|';
        usort($addedRows, fn (array $a, array $b): int => strcmp($a[0].$a[1].$a[2], $b[0].$b[1].$b[2]));
        foreach ($addedRows as [$kind, $class, $member]) {
            $lines[] = sprintf('| %s | `%s` | %s |', $kind, $class, $member !== '' ? '`'.$member.'`' : '—');
        }
    }

    return implode("\n", $lines)."\n";
}

/**
 * @param  array<string, array{kind: string, methods: array<string, string>, constants: list<string>, cases: list<string>}>  $old
 * @param  array<string, array{kind: string, methods: array<string, string>, constants: list<string>, cases: list<string>}>  $new
 * @return array{0: list<array{string, string, string, string}>, 1: list<array{string, string, string}>}
 */
function diff(array $old, array $new): array
{
    $breaking = [];
    $added = [];

    foreach (array_keys($old) as $classKey) {
        if (!isset($new[$classKey])) {
            $breaking[] = ['removed class', $classKey, '', 'was '.$old[$classKey]['kind']];

            continue;
        }
        foreach (array_diff_key($old[$classKey]['methods'], $new[$classKey]['methods']) as $method => $signature) {
            $breaking[] = ['removed method', $classKey, $method, '`'.$signature.'`'];
        }
        foreach ($old[$classKey]['methods'] as $method => $signature) {
            if (isset($new[$classKey]['methods'][$method])
                && $new[$classKey]['methods'][$method] !== $signature) {
                $breaking[] = ['changed method', $classKey, $method, '`'.$signature.'` → `'.$new[$classKey]['methods'][$method].'`'];
            }
        }
        foreach (array_diff($old[$classKey]['constants'], $new[$classKey]['constants']) as $constant) {
            $breaking[] = ['removed constant', $classKey, $constant, ''];
        }
        foreach (array_diff($old[$classKey]['cases'], $new[$classKey]['cases']) as $case) {
            $breaking[] = ['removed enum case', $classKey, $case, ''];
        }
    }

    foreach (array_keys($new) as $classKey) {
        if (!isset($old[$classKey])) {
            $added[] = ['added class', $classKey, ''];

            continue;
        }
        foreach (array_diff_key($new[$classKey]['methods'], $old[$classKey]['methods']) as $method => $signature) {
            $added[] = ['added method', $classKey, $method];
        }
        foreach (array_diff($new[$classKey]['constants'], $old[$classKey]['constants']) as $constant) {
            $added[] = ['added constant', $classKey, $constant];
        }
        foreach (array_diff($new[$classKey]['cases'], $old[$classKey]['cases']) as $case) {
            $added[] = ['added enum case', $classKey, $case];
        }
    }

    return [$breaking, $added];
}

/** @return array{0: ?string, 1: string} */
function resolveTag(string $root): array
{
    $override = getenv('ARAZZO_BC_TAG');
    if (is_string($override) && $override !== '') {
        return [$override, 'via ARAZZO_BC_TAG'];
    }

    exec('git -C '.escapeshellarg($root).' tag --sort=-creatordate 2>/dev/null', $tags);
    $tags = array_values(array_filter($tags));
    if ($tags === []) {
        return [null, 'no tags exist yet'];
    }

    // when HEAD is exactly on the latest tag (just released), compare to the one before it
    exec('git -C '.escapeshellarg($root).' describe --tags --exact-match 2>/dev/null', $exact);
    $onTag = $exact[0] ?? null;

    return $tags[0] === $onTag && isset($tags[1])
        ? [$tags[1], '']
        : [$tags[0], ''];
}
