<?php

declare(strict_types=1);

namespace ArazzoDocs\BoundariesAuditDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Framework Boundary Audit

Every third-party namespace the source imports, per package. Clean
architecture lives or dies at these edges: `packages/core` must stay free of
framework concerns (PSR interfaces are fine — they are contracts, not
frameworks). Rows marked ⚠ are violations under the declared policy below;
edit `POLICY` when a boundary consciously moves.

MD;

/**
 * vendor root => allowed in core?
 * Anything imported and not listed is flagged as unclassified (review).
 */
const POLICY = [
    'Psr' => true,                       // contracts only
    'Symfony' => false,                  // console app is an edge adapter — see note
    'Illuminate' => false,
    'GuzzleHttp' => false,
    'OpenApi' => false,
    'cebe' => false,
    'Symfony\Component\Yaml' => false,
    'Seld' => false,
];

const VENDOR_ROOTS = ['Psr', 'Illuminate', 'Symfony', 'GuzzleHttp', 'OpenApi', 'cebe', 'Seld', 'PHPUnit', 'Webmozart', 'Composer'];

/**
 * @param  array<string, list<ScannedFile>>  $core
 * @param  array<string, list<ScannedFile>>  $laravel
 */
function render(array $core, array $laravel): string
{
    $usage = [];
    foreach ([['core', $core], ['laravel', $laravel]] as [$package, $modules]) {
        foreach ($modules as $module => $files) {
            foreach ($files as $file) {
                foreach ($file->useStatements as $statement) {
                    $root = vendorRoot(trim($statement));
                    if ($root === null || str_starts_with(trim($statement), 'Alama\Arazzo')) {
                        continue;
                    }
                    $key = $package.'|'.$module.'|'.$root;
                    $usage[$key] = ($usage[$key] ?? 0) + 1;
                }
            }
        }
    }

    // aggregate to package level for the verdict, keep module detail
    $byPackage = [];
    $detail = [];
    ksort($usage);
    foreach ($usage as $key => $count) {
        [$package, $module, $root] = explode('|', $key);
        $byPackage[$package][$root] = ($byPackage[$package][$root] ?? 0) + $count;
        $detail[] = [$package, $module, $root, $count];
    }

    $lines = [BANNER, '## Package-level imports', '', '| Vendor | core refs | laravel refs | Policy in core |', '|---|---:|---:|---|'];

    $roots = array_unique([...array_keys($byPackage['core'] ?? []), ...array_keys($byPackage['laravel'] ?? [])]);
    sort($roots);
    foreach ($roots as $root) {
        $allowed = POLICY[$root] ?? null;
        $policyText = match (true) {
            $allowed === true => 'allowed',
            $allowed === false => '**forbidden**',
            default => '_unclassified_',
        };
        $flag = ($root !== 'Psr' && ($byPackage['core'][$root] ?? 0) > 0 && $allowed !== true) ? ' ⚠' : '';
        $lines[] = sprintf(
            '| `%s` | %s | %s | %s%s |',
            $root,
            number_format((float) ($byPackage['core'][$root] ?? 0)),
            number_format((float) ($byPackage['laravel'][$root] ?? 0)),
            $policyText,
            $flag,
        );
    }

    // module detail table
    $lines[] = '';
    $lines[] = '## Module detail';
    $lines[] = '';
    $lines[] = '| Package | Module | Vendor | References |';
    $lines[] = '|---|---|---|---:|';
    foreach ($detail as [$package, $module, $vendorRoot, $count]) {
        $lines[] = sprintf('| %s | `%s` | `%s` | %d |', $package, $module, $vendorRoot, $count);
    }

    // explicit violation section
    $violations = array_filter(
        $detail,
        fn (array $row): bool => $row[0] === 'core'
            && $row[2] !== 'Psr'
            && (POLICY[$row[2]] ?? null) !== true,
    );
    $lines[] = '';
    if ($violations === []) {
        $lines[] = '**Core boundary clean** — no forbidden vendor namespaces inside `packages/core/src`.';
        if (isset($byPackage['core']['Symfony'])) {
            $lines[] = '';
            $lines[] = '_Note:_ Symfony appears only under `Console/` — the CLI edge adapter. That is a deliberate, contained exception; move it out of core if the CLI grows beyond thin command wrappers.';
        }
    } else {
        $lines[] = sprintf('**%d core boundary violation(s):**', count($violations));
        foreach ($violations as [$package, $module, $vendorRoot, $count]) {
            $lines[] = sprintf('- `%s` imports `%s\\*` (%d refs)', $module, $vendorRoot, $count);
        }
    }

    return implode("\n", $lines)."\n";
}

function vendorRoot(string $statement): ?string
{
    $statement = preg_replace('/^use\s+/', '', rtrim($statement, ';'));
    $statement = trim((string) preg_replace('/\s+as\s+\w+$/', '', trim((string) $statement)));

    foreach (VENDOR_ROOTS as $root) {
        if (str_starts_with($statement, $root.'\\') || $statement === $root) {
            return $root;
        }
    }

    return str_contains($statement, '\\') ? explode('\\', $statement)[0] : null;
}
