<?php

declare(strict_types=1);

namespace ArazzoDocs\ChurnHotspotsDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Churn Hotspots

Where edit pressure lands. **Touches** = number of times a module's src files
appear in `git log` commits (full history, deterministic per HEAD). The
hotspot score normalizes churn by size: high touches-per-KLOC means a module
is edited far more often than its mass justifies — the classic "working in the
same corner every week" signal that static structure graphs cannot show.

MD;

const TOP_CHART_MODULES = 12;
const HOTSPOT_COUNT = 3;

/**
 * @param array<string, list<ScannedFile>> $core
 * @param array<string, list<ScannedFile>> $laravel
 */
function render(array $core, array $laravel, string $root): string
{
    $touches = scanChurn($root);
    if ($touches === []) {
        return BANNER . "_No git history found — hotspot analysis unavailable._\n";
    }

    // LOC per module from the already-scanned sources.
    // Scanner returns UNPREFIXED module dirs for both packages, so the
    // package must be prepended here (mirrors NamespaceGraphDoc\merge()).
    $loc = [];
    foreach ([['core', $core], ['laravel', $laravel]] as [$package, $modules]) {
        foreach ($modules as $module => $files) {
            if ($module === '_') {
                continue;
            }
            $key = ($package === 'laravel' ? 'Laravel/' : '') . $module;
            $loc[$key] = array_sum(array_map(
                fn (ScannedFile $f): int => substr_count($f->content, "\n") + 1,
                $files,
            ));
        }
    }

    // history may contain defunct dirs (pre-restructure); keep current structure only
    $touches = array_intersect_key($touches, $loc);

    $rows = [];
    foreach (array_unique([...array_keys($touches), ...array_keys($loc)]) as $module) {
        if ($module === '_') {
            continue;
        }
        $kloc = max(0.001, ($loc[$module] ?? 0) / 1000);
        $rows[] = [
            'module' => $module,
            'touches' => $touches[$module] ?? 0,
            'loc' => $loc[$module] ?? 0,
            'score' => round(($touches[$module] ?? 0) / $kloc, 1),
        ];
    }
    usort($rows, fn (array $a, array $b): int => $b['touches'] <=> $a['touches'] ?: strcmp((string) $a['module'], (string) $b['module']));

    $totalTouches = array_sum(array_column($rows, 'touches'));

    // chart: top N by touches
    $chartRows = array_slice($rows, 0, TOP_CHART_MODULES);
    $maxTouches = max(1, ...array_column($chartRows, 'touches'));
    $yMax = (int) (ceil($maxTouches * 1.15 / 10) * 10);

    $lines = [BANNER, '```mermaid', 'xychart-beta'];
    $lines[] = '    title "Edit churn per module (git touches)"';
    $lines[] = '    x-axis [' . implode(', ', array_map(fn (array $r): string => '"' . $r['module'] . '"', $chartRows)) . ']';
    $lines[] = sprintf('    y-axis "Touches" 0 --> %d', $yMax);
    $lines[] = '    bar ' . '[' . implode(', ', array_column($chartRows, 'touches')) . ']';
    $lines[] = '```';

    $lines[] = '';
    $lines[] = sprintf('Analyzed %d total file-touches across %d modules.', $totalTouches, count($rows));
    $lines[] = '';
    $lines[] = '| Module | Touches | Share | LOC | Touches/KLOC |';
    $lines[] = '|---|---:|---:|---:|---:|';
    foreach ($rows as $row) {
        $share = $totalTouches > 0 ? sprintf('%.0f%%', $row['touches'] / $totalTouches * 100) : '—';
        $lines[] = sprintf(
            '| `%s` | %d | %s | %s | %s |',
            $row['module'],
            $row['touches'],
            $share,
            number_format((float) $row['loc']),
            (string) $row['score'],
        );
    }

    // hotspots: highest churn density among modules with non-trivial churn
    $candidates = array_filter($rows, fn (array $r): bool => $r['touches'] >= 5 && $r['loc'] >= 100);
    usort($candidates, fn (array $a, array $b): int => $b['score'] <=> $a['score']);
    $hotspots = array_slice($candidates, 0, HOTSPOT_COUNT);
    if ($hotspots !== []) {
        $lines[] = '';
        $lines[] = '**Hotspots** (highest touches-per-KLOC with meaningful size/churn): '
            . implode(', ', array_map(fn (array $r): string => '`' . $r['module'] . '` (' . $r['score'] . ')', $hotspots));
    }

    return implode("\n", $lines) . "\n";
}

/** Path touch counts per module from full git history. */
function scanChurn(string $root): array
{
    exec(
        'git -C ' . escapeshellarg($root) . ' log --name-only --format=%x00 -- packages/core/src packages/laravel/src 2>/dev/null',
        $output,
    );

    $touches = [];
    $seenInCommit = [];
    $inCommit = false;
    foreach ($output as $line) {
        $line = trim($line);
        if ($line === chr(0) || $line === '') {
            $inCommit = true;
            $seenInCommit = [];

            continue;
        }
        if (!$inCommit || !str_contains($line, '/src/')) {
            continue;
        }
        // rename notation: take the post-rename path
        if (str_contains($line, ' => ')) {
            $parts = explode(' => ', $line);
            $line = end($parts);
            $line = trim($line, '{}');
        }
        if (!preg_match('#^packages/(core|laravel)/src/([^/]+)/#', $line, $m)) {
            continue;
        }
        $module = ($m[1] === 'laravel' ? 'Laravel/' : '') . $m[2];
        if (!isset($seenInCommit[$module])) {
            $seenInCommit[$module] = true;
            $touches[$module] = ($touches[$module] ?? 0) + 1;
        }
    }
    ksort($touches);

    return $touches;
}
