<?php

declare(strict_types=1);

namespace ArazzoDocs\CliReferenceDoc;

use Alama\Arazzo\Cli\Console\Application;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: CLI Reference

Introspected live from the real `Alama\Arazzo\Cli\Console\Application` instance —
every command, argument and option below is what the binary actually accepts,
not hand-maintained prose.

MD;

function render(string $root): string
{
    $autoload = $root.'/vendor/autoload.php';
    if (!is_file($autoload)) {
        return BANNER."_Root vendor autoload not found — run composer install._\n";
    }
    require_once $autoload;

    if (!class_exists(Application::class)) {
        return BANNER."_Console application class missing._\n";
    }

    $app = new Application();
    $commands = [];
    foreach ($app->all() as $name => $command) {
        // keep only package commands; Symfony ships help/list/completion noise
        if (str_starts_with(get_class($command), 'Alama\\Arazzo\\')) {
            $commands[$name] = $command;
        }
    }
    ksort($commands);

    $lines = [BANNER];
    $lines[] = sprintf('Binary: `bin/arazzo` · %d commands · version %s', count($commands), $app->getVersion());
    $lines[] = '';
    $lines[] = globalOptionsSection($app);

    foreach ($commands as $name => $command) {
        $lines[] = '## `arazzo '.$name.'`';
        $description = (string) $command->getDescription();
        if ($description !== '') {
            $lines[] = $description;
        }
        $lines[] = '';

        $definition = $command->getDefinition();

        // usage synopsis
        $synopsis = 'arazzo '.$name;
        foreach ($definition->getArguments() as $argument) {
            $synopsis .= $argument->isRequired()
                ? ' <'.$argument->getName().'>'
                : ' ['.$argument->getName().']';
        }
        if ($definition->getOptions() !== []) {
            $synopsis .= ' [options]';
        }
        $lines[] = '`$ '.$synopsis.'`';
        $lines[] = '';

        $arguments = $definition->getArguments();
        if ($arguments !== []) {
            $lines[] = '| Argument | Required | Default | Description |';
            $lines[] = '|---|---|---|---|';
            foreach ($arguments as $argument) {
                $lines[] = sprintf(
                    '| `%s` | %s | %s | %s |',
                    $argument->getName(),
                    $argument->isRequired() ? 'yes' : 'no',
                    defaultCell($argument->getDefault()),
                    escape((string) $argument->getDescription()),
                );
            }
            $lines[] = '';
        }

        $options = $definition->getOptions();
        if ($options !== []) {
            $lines[] = '| Option | Shortcut | Value | Default | Description |';
            $lines[] = '|---|---|---|---|---|';
            foreach ($options as $option) {
                $shortcut = $option->getShortcut() ? '-'.$option->getShortcut() : '';
                $lines[] = sprintf(
                    '| `--%s` | `%s` | %s | %s | %s |',
                    $option->getName(),
                    $shortcut,
                    $option->acceptValue() ? ($option->isArray() ? 'value[]' : 'value') : 'flag',
                    defaultCell($option->getDefault()),
                    escape((string) $option->getDescription()),
                );
            }
            $lines[] = '';
        }
    }

    return implode("\n", $lines)."\n";
}

function globalOptionsSection(\Symfony\Component\Console\Application $app): string
{
    $options = $app->getDefinition()->getOptions();
    if ($options === []) {
        return '';
    }

    $out = ['## Global options', '', '| Option | Shortcut | Value | Description |', '|---|---|---|---|'];
    foreach ($options as $option) {
        $shortcut = $option->getShortcut() ? '-'.$option->getShortcut() : '';
        $out[] = sprintf(
            '| `--%s` | `%s` | %s | %s |',
            $option->getName(),
            $shortcut,
            $option->acceptValue() ? 'value' : 'flag',
            escape((string) $option->getDescription()),
        );
    }

    return implode("\n", $out);
}

/** @param mixed $default */
function defaultCell($default): string
{
    if ($default === null) {
        return '—';
    }
    if ($default === true) {
        return 'true';
    }
    if ($default === false) {
        return 'false';
    }
    if (is_array($default)) {
        return $default === [] ? '[]' : '`'.implode(', ', array_map(strval(...), $default)).'`';
    }

    return '`'.((string) $default).'`';
}

function escape(string $text): string
{
    return str_replace('|', '\\|', trim($text));
}
