<?php

declare(strict_types=1);

namespace ArazzoDocs\ContractsDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Contracts & Implementations (Ports and Adapters)

Every `*Interface` in the engine and the classes that implement it, scanned live
from both packages. Core defines contracts; Laravel implements them.

MD;

/**
 * @param  array<string, array<string, list<ScannedFile>>>  $scans  package slug => (module => files)
 */
function render(array $scans): string
{
    $interfaces = [];   // shortName => ['module' => string, 'fqcn' => string]
    foreach (\ArazzoDocs\flattenScans($scans) as $file) {
        if ($file->isInterface) {
            $interfaces[$file->className] = [
                'package' => $file->package,
                'module' => \ArazzoDocs\packageKey($file->package, \ArazzoDocs\fileModule($file)),
                'fqcn' => $file->namespace.'\\'.$file->className,
            ];
        }
    }

    // find implementations: scan all non-interface files for "implements ...Interface"
    $impls = [];   // interfaceShort => list of [class, package, module]
    foreach (\ArazzoDocs\flattenScans($scans) as $file) {
        if ($file->isInterface) {
            continue;
        }
        if (!preg_match('/implements\s+([\w\\\\,\s]+)$/m', $file->content, $m)) {
            continue;
        }
        foreach (explode(',', str_replace("\n", ' ', trim($m[1]))) as $raw) {
            $short = basename(str_replace('\\', '/', trim(preg_replace('/\s+/', ' ', $raw))));
            if (!isset($interfaces[$short])) {
                continue;
            }
            $impls[$short][] = [$file->className, $file->package, \ArazzoDocs\packageKey($file->package, \ArazzoDocs\fileModule($file)), $file->namespace.'\\'.$file->className];
        }
    }

    ksort($interfaces);

    $lines = [BANNER, '```mermaid', 'flowchart LR'];

    foreach ($interfaces as $name => $meta) {
        $style = $meta['package'] === 'laravel' ? 'contractLaravel' : 'contract';
        $moduleLabel = str_ends_with($meta['module'], ':_') ? '('.strtok($meta['module'], ':').' root)' : $meta['module'];
        $lines[] = sprintf(
            '    I_%s["%s<br/><small>%s</small>"]:::%s',
            $name,
            $name,
            $moduleLabel,
            $style,
        );
    }

    foreach ($impls as $interface => $implementations) {
        foreach ($implementations as [$class, $pkg, $module]) {
            $style = $pkg === 'laravel' ? 'implLaravel' : 'implCore';
            $id = 'C_'.preg_replace('/[^A-Za-z0-9_]/', '_', "{$pkg}_{$module}_{$class}");
            $lines[] = sprintf(
                '    %s["%s<br/><small>%s</small>"]:::%s',
                $id,
                $class,
                str_ends_with($module, ':_') ? '('.strtok($module, ':').' root)' : $module,
                $style,
            );
            $lines[] = sprintf('    %s -.->|implements| I_%s', $id, $interface);
        }
    }

    // contracts with no implementation found get a floating marker
    foreach (array_keys($interfaces) as $name) {
        if (!isset($impls[$name])) {
            $lines[] = sprintf('    N_%1$s["no implementation found"]:::orphan --> I_%1$s', $name);
        }
    }

    $lines[] = '    classDef contract fill:#e8f0fe,stroke:#4285f4,color:#1a1a1a;';
    $lines[] = '    classDef contractLaravel fill:#e8f0fe,stroke:#4285f4,color:#1a1a1a;';
    $lines[] = '    classDef implCore fill:#e6f4ea,stroke:#34a853,color:#1a1a1a;';
    $lines[] = '    classDef implLaravel fill:#fef7e0,stroke:#f9ab00,color:#1a1a1a;';
    $lines[] = '    classDef orphan fill:#fce8e6,stroke:#ea4335,color:#1a1a1a;';
    $lines[] = '```';
    $lines[] = '';

    return implode("\n", $lines)."\n";
}
