<?php

declare(strict_types=1);

namespace ArazzoDocs\CouplingMetricsDoc;

use ArazzoDocs\NamespaceGraphDoc;
use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Coupling Metrics

Per-module size and coupling, computed from the live `use` graph (same data as
the namespace graph). **Instability** = fan-out / (fan-in + fan-out): 0 means
nothing depends on it changing, 1 means it depends on everything else.
⚠ marks unstable modules that are also depended upon — the classic refactoring
targets. Regenerated before every commit.

MD;

const TOP_EDGES_LIMIT = 12;
const UNSTABLE_THRESHOLD = 0.8;
const HUB_FAN_IN_THRESHOLD = 3;

/**
 * @param  array<string, list<ScannedFile>>  $core
 * @param  array<string, list<ScannedFile>>  $laravel
 */
function render(array $scans): string
{
    $all = NamespaceGraphDoc\merge($scans);

    $classModule = [];
    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            $classModule[$file->namespace.'\\'.$file->className] = $module;
        }
    }

    [$fanIn, $fanOut, $pairWeight, $edgeCount] = computeGraph($all, $classModule);

    $lines = [
        BANNER,
        '| Module | Files | LOC | Fan-in | Fan-out | Instability | Flag |',
        '|---|---:|---:|---:|---:|---:|---|',
    ];

    $modules = array_keys($all);
    sort($modules);
    foreach ($modules as $module) {
        $files = $all[$module];
        $loc = 0;
        foreach ($files as $file) {
            $loc += substr_count($file->content, "\n");
        }
        $in = count($fanIn[$module] ?? []);
        $out = count($fanOut[$module] ?? []);
        $total = $in + $out;
        $instability = $total === 0 ? 0.0 : round($out / $total, 2);
        $flag = $instability >= UNSTABLE_THRESHOLD && $in >= HUB_FAN_IN_THRESHOLD ? '⚠ unstable hub' : '';

        $lines[] = sprintf(
            '| `%s` | %d | %d | %d | %d | %.2f | %s |',
            label($module),
            count($files),
            $loc,
            $in,
            $out,
            $instability,
            $flag,
        );
    }

    $lines[] = '';
    $lines[] = sprintf('Total cross-module edges: **%d**', $edgeCount);
    $lines[] = '';
    $lines[] = '## Most entangled module pairs';
    $lines[] = '';
    $lines[] = '| From → To | References |';
    $lines[] = '|---|---:|';

    $pairs = [];
    foreach ($pairWeight as $from => $targets) {
        foreach ($targets as $to => $weight) {
            $pairs[] = [$weight, $from, $to];
        }
    }
    usort($pairs, fn (array $a, array $b): int => $b[0] <=> $a[0] ?: strcmp(label($a[1]).$a[2], label($b[1]).$b[2]));
    foreach (array_slice($pairs, 0, TOP_EDGES_LIMIT) as [$weight, $from, $to]) {
        $lines[] = sprintf('| `%s` → `%s` | %d |', label($from), label($to), $weight);
    }

    return implode("\n", $lines)."\n";
}

/**
 * @param  array<string, list<ScannedFile>>  $all
 * @param  array<string, string>  $classModule
 * @return array{0: array<string, array<string, true>>, 1: array<string, array<string, true>>, 2: array<string, array<string, int>>, 3: int}
 */
function computeGraph(array $all, array $classModule): array
{
    $fanIn = [];
    $fanOut = [];
    $pairWeight = [];
    $edgeCount = 0;

    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            foreach ($file->uses as $use) {
                $target = $classModule[$use] ?? null;
                if ($target === null || $target === $module) {
                    continue;
                }
                $edgeCount++;
                $fanOut[$module][$target] = true;
                $fanIn[$target][$module] = true;
                $pairWeight[$module][$target] = ($pairWeight[$module][$target] ?? 0) + 1;
            }
        }
    }

    ksort($fanIn);
    ksort($fanOut);
    foreach ($pairWeight as &$targets) {
        ksort($targets);
    }
    unset($targets);

    return [$fanIn, $fanOut, $pairWeight, $edgeCount];
}

function label(string $key): string
{
    $pos = strpos($key, ':');
    if ($pos === false) {
        return $key;
    }
    $package = substr($key, 0, $pos);
    $module = substr($key, $pos + 1);

    return $module === '_' ? "({$package} root)" : $key;
}
