<?php

declare(strict_types=1);

namespace ArazzoDocs\CoverageRiskDoc;

use const ArazzoDocs\CORE_SRC_PACKAGES;

use ArazzoDocs\NamespaceGraphDoc;
use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Coverage / Risk Quadrant

Each module plotted by **instability** (x, from the coupling graph) vs **test
density** (y: test files referencing the module ÷ src files in it).

- *Untested churn* (bottom-right) — changing constantly with no safety net: refactor first.
- *Well-tested hotspots* (top-right) — churn is paid for; keep tests green.
- Test density is file-level and name-based (a test file counts once per
  module whose class names it mentions); it is a proxy, not line coverage.

MD;

/**
 * @param  array<string, list<ScannedFile>>  $core
 * @param  array<string, list<ScannedFile>>  $laravel
 */
function render(array $scans, string $root): string
{
    $all = NamespaceGraphDoc\merge($scans);

    $classModule = [];
    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            $classModule[$file->namespace.'\\'.$file->className] = $module;
        }
    }

    // instability per module (same formula as coupling-metrics)
    $fanIn = [];
    $fanOut = [];
    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            foreach ($file->uses as $use) {
                $target = $classModule[$use] ?? null;
                if ($target === null || $target === $module) {
                    continue;
                }
                $fanOut[$module][$target] = true;
                $fanIn[$target][$module] = true;
            }
        }
    }

    // test density per module: scan test files of both packages
    $testMentions = scanTestMentions($root);

    $points = [];
    foreach ($all as $key => $files) {
        if (str_ends_with($key, ':_')) {
            continue; // package roots are not plottable units
        }
        $in = count($fanIn[$key] ?? []);
        $out = count($fanOut[$key] ?? []);
        $instability = ($in + $out) === 0 ? 0.0 : $out / ($in + $out);
        $srcCount = max(1, count($files));
        $density = min(1.0, ($testMentions[$key] ?? 0) / $srcCount);
        $points[] = [
            'label' => plotLabel($key),
            'x' => round($instability, 3),
            'y' => round($density, 3),
            'src' => $srcCount,
            'tests' => $testMentions[$key] ?? 0,
        ];
    }
    usort($points, fn (array $a, array $b): int => strcmp($a['label'], $b['label']));

    $lines = [BANNER, '```mermaid', 'quadrantChart'];
    $lines[] = '    title Module risk map';
    $lines[] = '    x-axis Low stability --> High instability';
    $lines[] = '    y-axis Low test density --> High test density';
    $lines[] = '    quadrant-1 Well-tested hotspots';
    $lines[] = '    quadrant-2 Solid & stable';
    $lines[] = '    quadrant-3 Stable but untested';
    $lines[] = '    quadrant-4 Untested churn';
    foreach ($points as $point) {
        $lines[] = sprintf('    %s: [%s, %s]', $point['label'], $point['x'], $point['y']);
    }
    $lines[] = '```';

    $lines[] = '';
    $lines[] = '| Module | Instability | Test files | Src files | Density |';
    $lines[] = '|---|---:|---:|---:|---:|';
    foreach ($points as $point) {
        $lines[] = sprintf(
            '| `%s` | %.2f | %d | %d | %.0f%% |',
            $point['label'],
            $point['x'],
            $point['tests'],
            $point['src'],
            $point['y'] * 100,
        );
    }

    $worst = array_filter($points, fn (array $p): bool => $p['x'] >= 0.5 && $p['y'] <= 0.3);
    if ($worst !== []) {
        usort($worst, fn (array $a, array $b): int => $b['x'] <=> $a['x']);
        $lines[] = '';
        $lines[] = '**Refactor-now list** (untested churn): '
            .implode(', ', array_map(fn (array $p): string => '`'.$p['label'].'`', $worst));
    }

    return implode("\n", $lines)."\n";
}

/**
 * Number of test files per module that mention at least one of the module's
 * class short names.
 *
 * @return array<string, int> module bare name => test file count
 */
function scanTestMentions(string $root): array
{
    // module => class short names
    $namesByModule = [];
    $srcDirs = [];
    foreach (CORE_SRC_PACKAGES as $package) {
        $srcDirs[] = [$root.'/packages/'.$package.'/src', $package];
    }
    $srcDirs[] = [$root.'/packages/laravel/src', 'laravel'];
    foreach ($srcDirs as [$srcDir, $package]) {
        if (!is_dir($srcDir)) {
            continue;
        }
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($srcDir, \FilesystemIterator::SKIP_DOTS),
        );
        /** @var \SplFileInfo $file */
        foreach ($iterator as $file) {
            if ($file->getExtension() !== 'php') {
                continue;
            }
            $relative = str_replace($srcDir.'/', '', (string) $file->getPathname());
            $parts = explode('/', $relative);
            if (count($parts) < 2) {
                continue; // root files have no module dir
            }
            $module = $package.':'.$parts[0];
            $namesByModule[$module][basename((string) $file->getPathname(), '.php')] = true;
        }
    }

    $counts = [];
    $testsDirs = [$root.'/packages/core/tests']; // cross-cutting integration/architecture/conformance suites
    foreach (CORE_SRC_PACKAGES as $package) {
        $testsDirs[] = $root.'/packages/'.$package.'/tests';
    }
    $testsDirs[] = $root.'/packages/laravel/tests';
    foreach ($testsDirs as $testsDir) {
        if (!is_dir($testsDir)) {
            continue;
        }
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($testsDir, \FilesystemIterator::SKIP_DOTS),
        );
        /** @var \SplFileInfo $file */
        foreach ($iterator as $file) {
            if ($file->getExtension() !== 'php') {
                continue;
            }
            $content = (string) file_get_contents((string) $file->getPathname());
            foreach ($namesByModule as $module => $names) {
                foreach (array_keys($names) as $name) {
                    if (preg_match('/\b'.preg_quote($name, '/').'\b/', $content) === 1) {
                        $counts[$module] = ($counts[$module] ?? 0) + 1;

                        break; // one file counts once per module
                    }
                }
            }
        }
    }

    return $counts;
}

function plotLabel(string $key): string
{
    return str_replace(':', '/', $key);
}
