<?php

declare(strict_types=1);

namespace ArazzoDocs\DatabaseSchemaDoc;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Persistence Schema (ER Diagram)

Derived live from the Laravel migrations in
`packages/laravel/database/migrations`. Regenerated before every commit.

MD;

/**
 * Parses `$table->type('name')` calls plus index/FK modifiers out of the
 * migration files and renders a mermaid erDiagram. `Schema::create` blocks
 * define tables; later `Schema::table` alterations merge columns in
 * (migration-basename order), so the diagram reflects the migrated schema,
 * not just day-one tables.
 */
function render(string $migrationsDir): string
{
    $tables = [];
    $paths = glob($migrationsDir.'/*.php') ?: [];
    sort($paths);
    foreach ($paths as $path) {
        $base = basename($path);
        if (!preg_match('/create_(\w+)_table/', $base, $m)) {
            continue; // only create-table migrations define entities
        }
        $table = $m[1];
        $content = (string) file_get_contents($path);

        [$entries, $composites] = parseColumns($content, $content);
        ksort($entries);
        $tables[$table] = ['columns' => $entries, 'composites' => $composites];
    }

    // table alterations: Schema::table('x', fn) blocks merge columns in
    foreach ($paths as $path) {
        $content = (string) file_get_contents($path);
        // never parse down() — dropColumn calls are not schema
        $content = (string) preg_replace('/function down\(\).*?\n    \}\n?\}/s', '', $content);
        if (preg_match_all('/Schema::table\(\'(\w+)\',\s*function\s*\([^)]*\)\s*(?:use\s*\([^)]*\)\s*)?\{(.*?)\n\s*\}\);/s', $content, $alters, PREG_SET_ORDER) !== false) {
            foreach ($alters as [, $table, $body]) {
                if (!isset($tables[$table])) {
                    continue;
                }
                [$entries] = parseColumns($body, $content);
                foreach ($entries as $name => $entry) {
                    $tables[$table]['columns'][$name] = $entry;
                }
                ksort($tables[$table]['columns']);
            }
        }
    }

    ksort($tables);

    $lines = [BANNER, '```mermaid', 'erDiagram'];
    $compositeNotes = [];
    foreach ($tables as $table => $meta) {
        if ($meta['composites'] !== []) {
            $compositeNotes[] = sprintf('- `%s`: %s', $table, implode('; ', $meta['composites']));
        }
        $lines[] = "    {$table} {";
        foreach ($meta['columns'] as $entry) {
            $lines[] = $entry;
        }
        $lines[] = '    }';
    }

    // relationships
    if (isset($tables['arazzo_definitions'], $tables['arazzo_executions'])) {
        $lines[] = '    arazzo_definitions ||--o{ arazzo_executions : "definition_id"';
    }
    if (isset($tables['arazzo_executions'], $tables['arazzo_events'])) {
        $lines[] = '    arazzo_executions ||--o{ arazzo_events : "execution_id"';
    }
    if (isset($tables['arazzo_executions'], $tables['arazzo_pending_correlations'])) {
        $lines[] = '    arazzo_executions ||--o{ arazzo_pending_correlations : "execution_id"';
    }
    $lines[] = '```';

    if ($compositeNotes !== []) {
        $lines[] = '';
        $lines[] = '## Composite constraints';
        $lines[] = '';
        foreach ($compositeNotes as $note) {
            $lines[] = $note;
        }
    }

    return implode("\n", $lines)."\n";
}

/**
 * @return array{0: array<string, string>, 1: list<string>} columns + composites
 */
function parseColumns(string $block, string $fullContent): array
{
    // columns: $table->type('name')
    preg_match_all('/\$table->(\w+)\(\'(\w+)\'(?:,\s*[^)]+)?\)([^;]*);/', $block, $cols, PREG_SET_ORDER);

    $entries = [];
    $composites = [];
    foreach ($cols as $c) {
        $type = $c[1];
        $name = $c[2];
        $tail = $c[3];
        if ($type === 'foreign') {
            continue; // handled as relationship below
        }
        $keys = [];
        $comments = [];
        if ($type === 'id' || str_contains($tail, '->primary(')) {
            $keys[] = 'PK';
        }
        if (str_contains($tail, '->unique(')) {
            $keys[] = 'UK';
        }
        if (str_contains($tail, '->index(')) {
            $comments[] = 'indexed';
        }
        if (preg_match('/\$table->foreign\(\''.$name.'\'\)/', $fullContent)) {
            $keys[] = 'FK';
        }
        $entries[$name] = sprintf(
            '        %s %s %s%s',
            columnType($type),
            $name,
            implode(',', $keys),
            $comments === [] ? '' : ' "'.implode(' ', $comments).'"',
        );
    }

    // composite unique/index definitions -> notes under the diagram
    preg_match_all('/\$table->(unique|index)\(\[([^\]]+)\]\)/', $block, $compMatches, PREG_SET_ORDER);
    foreach ($compMatches as $comp) {
        $names = array_map(static fn (string $n): string => trim($n, "'\" "), explode(',', $comp[2]));
        $composites[] = sprintf('%s(%s)', $comp[1], implode(', ', $names));
    }

    return [$entries, $composites];
}

function columnType(string $migrationType): string
{
    return match ($migrationType) {
        'id', 'ulid' => 'ulid',
        'string' => 'string',
        'text', 'longText' => 'text',
        'json' => 'json',
        'timestamp', 'timestamps', 'dateTime' => 'timestamp',
        'integer', 'bigInteger', 'unsignedInteger' => 'int',
        'boolean' => 'bool',
        default => strtolower($migrationType),
    };
}
