<?php

declare(strict_types=1);

namespace ArazzoDocs\DependencyFlowDoc;

use ArazzoDocs\CouplingMetricsDoc;
use ArazzoDocs\NamespaceGraphDoc;
use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Dependency Flow

The weighted coupling data from the metrics table, rendered as a flow:
band thickness = number of `use` references from one module to another. Read
it as "where the architectural mass moves" — thick bands into one module mean
changes there ripple widely.

Sankey diagrams must be acyclic; where dependencies are bidirectional only
the heavier direction is drawn and the folded side is listed below the chart.

MD;

/**
 * @param  array<string, list<ScannedFile>>  $core
 * @param  array<string, list<ScannedFile>>  $laravel
 */
function render(array $core, array $laravel): string
{
    $all = NamespaceGraphDoc\merge($core, $laravel);

    $classModule = [];
    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            $classModule[$file->namespace.'\\'.$file->className] = $module;
        }
    }

    [, , $pairWeight] = CouplingMetricsDoc\computeGraph($all, $classModule);

    $rows = [];
    foreach ($pairWeight as $from => $targets) {
        foreach ($targets as $to => $weight) {
            $rows[] = ['from' => $from, 'to' => $to, 'weight' => $weight];
        }
    }

    if ($rows === []) {
        return BANNER."_No cross-module dependencies found._\n";
    }

    // Sankey must be free of DIRECTED cycles; GitHub rejects circular links.
    // Keep the heavier edges first (greedy, weight-desc); fold an edge only
    // when its target can already reach its source through kept edges.
    usort($rows, fn (array $a, array $b): int => $b['weight'] <=> $a['weight']
        ?: strcmp((string) $a['from'], (string) $b['from'])
        ?: strcmp((string) $a['to'], (string) $b['to']));

    $adjacency = [];
    $reaches = function (string $from, string $to) use (&$adjacency): bool {
        if ($from === $to) {
            return true;
        }
        $seen = [];
        $stack = [$from];
        while ($stack !== []) {
            $node = array_pop($stack);
            foreach ($adjacency[$node] ?? [] as $next) {
                if ($next === $to) {
                    return true;
                }
                if (!isset($seen[$next])) {
                    $seen[$next] = true;
                    $stack[] = $next;
                }
            }
        }

        return false;
    };

    $kept = [];
    $folded = [];
    foreach ($rows as $row) {
        $from = (string) $row['from'];
        $to = (string) $row['to'];
        if ($reaches($to, $from)) {
            // to ->* from already drawn; adding from->to would close a directed cycle
            $folded[] = $row;

            continue;
        }
        $adjacency[$from][] = $to;
        $kept[] = $row;
    }
    usort($kept, fn (array $a, array $b): int => strcmp((string) $a['from'], (string) $b['from'])
        ?: strcmp((string) $a['to'], (string) $b['to']));

    $lines = [BANNER, '```mermaid', 'sankey-beta', ''];
    foreach ($kept as $row) {
        $lines[] = sprintf('%s,%s,%d', label($row['from']), label($row['to']), $row['weight']);
    }
    $lines[] = '```';

    if ($folded !== []) {
        $lines[] = '';
        $lines[] = '## Folded flows';
        $lines[] = '';
        $lines[] = 'These references exist in the code but are not drawn: drawing them would'
            .' close a dependency cycle and Sankey diagrams must stay acyclic. The heavier'
            .' direction of each cycle is shown above.';
        $lines[] = '';
        $lines[] = '| From | To | References |';
        $lines[] = '|---|---|---:|';
        usort($folded, fn (array $a, array $b): int => strcmp((string) $a['from'], (string) $b['from'])
            ?: strcmp((string) $a['to'], (string) $b['to']));
        foreach ($folded as $row) {
            $lines[] = sprintf('| `%s` | `%s` | %d |', label($row['from']), label($row['to']), $row['weight']);
        }
    }

    return implode("\n", $lines)."\n";
}

function label(string $module): string
{
    if ($module === '_') {
        return 'core-root';
    }
    if ($module === 'Laravel:_') {
        return 'laravel-root';
    }
    if (str_starts_with($module, 'Laravel:')) {
        return str_replace(':', '-', $module);
    }

    return \ArazzoDocs\modulePackageSegment($module).'\\'.$module;
}
