<?php

declare(strict_types=1);

namespace ArazzoDocs\DependencyFlowDoc;

use ArazzoDocs\CouplingMetricsDoc;
use ArazzoDocs\NamespaceGraphDoc;
use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Dependency Flow

The same weighted coupling data as the metrics table, rendered as a flow:
band thickness = number of `use` references from one module to another. Read
it as "where the architectural mass moves" — thick bands into one module mean
changes there ripple widely.

MD;

/**
 * @param array<string, list<ScannedFile>> $core
 * @param array<string, list<ScannedFile>> $laravel
 */
function render(array $core, array $laravel): string
{
    $all = NamespaceGraphDoc\merge($core, $laravel);

    $classModule = [];
    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            $classModule[$file->namespace . '\\' . $file->className] = $module;
        }
    }

    [, , $pairWeight] = CouplingMetricsDoc\computeGraph($all, $classModule);

    $rows = [];
    foreach ($pairWeight as $from => $targets) {
        foreach ($targets as $to => $weight) {
            $rows[] = [$from, $to, $weight];
        }
    }
    usort($rows, fn (array $a, array $b): int => strcmp($a[0], $b[0]) ?: strcmp($a[1], $b[1]));

    if ($rows === []) {
        return BANNER . "_No cross-module dependencies found._\n";
    }

    $lines = [BANNER, '```mermaid', 'sankey-beta', ''];
    foreach ($rows as [$from, $to, $weight]) {
        $lines[] = sprintf('%s,%s,%d', label($from), label($to), $weight);
    }
    $lines[] = '```';

    return implode("\n", $lines) . "\n";
}

function label(string $module): string
{
    if ($module === '_') {
        return 'core-root';
    }
    if ($module === 'Laravel:_') {
        return 'laravel-root';
    }
    if (str_starts_with($module, 'Laravel:')) {
        return str_replace(':', '-', $module);
    }

    return $module;
}
