<?php

declare(strict_types=1);

namespace ArazzoDocs\DocumentModelDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Document Model (`Spec\`)

The immutable Arazzo document value-object tree, scanned live from
`packages/core/src/Spec`. Composition edges are derived from constructor
promoted properties whose types resolve to other `Spec\` classes.

MD;

/**
 * @param  array<string, list<ScannedFile>>  $core
 */
function render(array $core): string
{
    $files = [];
    foreach ($core as $moduleFiles) {
        foreach ($moduleFiles as $file) {
            if ($file->path === 'Spec') {
                $files[] = $file;
            }
        }
    }

    // className => fqcn for Spec classes only
    $specClasses = [];
    foreach ($files as $file) {
        if (!$file->isInterface) {
            $specClasses[$file->className] = $file->namespace.'\\'.$file->className;
        }
    }
    ksort($specClasses);

    // composition edges: from => to (promoted property types + @param docblock generics)
    $edges = [];
    foreach ($files as $file) {
        if ($file->isInterface) {
            continue;
        }
        $found = [];

        // 1. promoted constructor property types
        if (preg_match('/__construct\((.*?)\)\s*(?:{|$)/s', $file->content, $m)) {
            preg_match_all('/(?:public|protected|private)(?:\s+readonly)?\s+(?:\?|list<|array{)?([\w\\\\]+)/', $m[1], $types);
            foreach ($types[1] as $type) {
                $found[] = basename(str_replace('\\', '/', $type));
            }
        }

        // 2. @param annotations on the constructor (list<Spec\Class>, Class[], ?Class, unions)
        if (preg_match('/\/\*\*(.*?)\*\/\s*(?:private|public|protected)?\s*(?:readonly\s+)?function\s+__construct/s', $file->content, $doc)) {
            preg_match_all('/@param\s+([^\n]+)\s+\$\w+/', $doc[1], $params);
            foreach ($params[1] as $type) {
                preg_match_all('/[A-Z]\w+/', str_replace(['list<', '>', '[', ']'], ' ', $type), $names);
                foreach ($names[0] as $name) {
                    $found[] = $name;
                }
            }
        }

        foreach ($found as $short) {
            if (isset($specClasses[$short]) && $short !== $file->className) {
                $edges[$file->className][$short] = true;
            }
        }
    }

    $lines = [BANNER, '```mermaid', 'classDiagram', '    direction LR'];

    foreach (array_keys($specClasses) as $class) {
        $stereotype = str_ends_with($class, 'Action') ? '<<value>>' : null;
        if ($stereotype !== null) {
            $lines[] = "    class {$class} {$stereotype}";
        } else {
            $lines[] = "    class {$class}";
        }
    }

    $seen = [];
    foreach ($edges as $from => $targets) {
        foreach (array_keys($targets) as $to) {
            $key = "{$from}->{$to}";
            if (isset($seen[$key])) {
                continue;
            }
            $seen[$key] = true;
            $label = cardinality($to);
            $lines[] = "    {$from} \"1\" --> \"{$label}\" {$to} : holds";
        }
    }

    $lines[] = '```';
    $lines[] = '';
    $lines[] = '## Enumerations';
    $lines[] = '';

    foreach ($files as $file) {
        if (!preg_match('/^enum\s+(\w+)(?::\s*string)?/m', $file->content, $m)) {
            continue;
        }
        preg_match_all('/^\s*case\s+(\w+)\s*=\s*\'([^\']*)\'\s*;/m', $file->content, $cases, PREG_SET_ORDER);
        $values = implode(' &middot; ', array_map(
            static fn (array $c): string => "`{$c[2]}`",
            $cases,
        ));
        $lines[] = "- **{$m[1]}** — {$values}";
    }

    return implode("\n", $lines)."\n";
}

function cardinality(string $target): string
{
    // list-typed properties are 0..*; we approximate by target name heuristics
    return in_array($target, ['Workflow', 'Step', 'SourceDescription', 'SuccessCriterion'], true) ? '0..*' : '0..1';
}
