<?php

declare(strict_types=1);

namespace ArazzoDocs\EventsDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Domain Events

PSR-14 event classes under `Runner/Events` (core) and `Events/` (Laravel), with
every dispatch site found in the live tree. Regenerated before every commit.

MD;

/**
 * @param  array<string, array<string, list<ScannedFile>>>  $scans  package slug => (module => files)
 */
function render(array $scans): string
{
    // collect event classes: concrete classes living in an Events/ directory
    $events = [];   // shortName => [fqcn, package]
    foreach (\ArazzoDocs\flattenScans($scans) as $file) {
        if ($file->isInterface) {
            continue;
        }
        $dir = $file->relativeDir;
        if ($dir !== 'Events' && !str_ends_with($dir, '/Events')) {
            continue;
        }
        if (str_contains($dir, 'Dispatcher') || str_contains($file->className, 'Dispatcher')) {
            continue; // dispatch infrastructure, not a domain event
        }
        $events[$file->className] = [$file->namespace.'\\'.$file->className, $file->package];
    }

    // find dispatch sites: any class that constructs an event (possibly via
    // a "use ...\StepExecuted as Foo;" alias) and dispatches somewhere
    $dispatches = [];
    foreach (\ArazzoDocs\flattenScans($scans) as $file) {
        if (!str_contains($file->content, 'dispatch(')) {
            continue;
        }
        $pkg = $file->package;
        $module = \ArazzoDocs\packageKey($file->package, \ArazzoDocs\fileModule($file));

        // alias => event short name
        $aliasToEvent = [];
        foreach ($file->useStatements as $statement) {
            if (preg_match('/^([\w\\\\]+)\s+as\s+(\w+)$/', $statement, $m)) {
                $source = basename(str_replace('\\', '/', $m[1]));
                if (isset($events[$source])) {
                    $aliasToEvent[$m[2]] = $source;
                }
            }
        }

        // every "new X(" where X resolves to an event
        preg_match_all('/new\s+(\w+)\s*\(/', $file->content, $news);
        foreach ($news[1] as $constructed) {
            $event = $events[$constructed] ?? null;
            if ($event === null && isset($aliasToEvent[$constructed])) {
                $event = $events[$aliasToEvent[$constructed]];
            }
            if ($event === null) {
                // try matching by short name (basename of FQCN)
                $shortConstructed = basename($constructed);
                $event = null;
                foreach ($events as $fqcn => $eventData) {
                    if (basename($fqcn) === $shortConstructed) {
                        $event = [$fqcn, $eventData[1]];
                        break;
                    }
                }
            }
            if ($event === null) {
                continue;
            }
            $eventName = basename(str_replace('\\', '/', $event[0]));
            $dispatches[$eventName][$file->namespace.'\\'.$file->className] = [$pkg, $module];
        }
    }

    ksort($events);

    $lines = [BANNER, '```mermaid', 'flowchart LR'];

    foreach ($events as $name => [$fqcn, $pkg]) {
        $style = $pkg === 'laravel' ? 'eventLaravel' : 'event';
        $lines[] = sprintf('    E_%s(["%s"]):::%s', $name, $name, $style);
    }

    foreach ($dispatches as $event => $sites) {
        ksort($sites);
        foreach ($sites as $fqcn => [$pkg, $module]) {
            $short = basename(str_replace('\\', '/', $fqcn));
            $id = 'S_'.preg_replace('/[^A-Za-z0-9_]/', '_', $fqcn);
            $lines[] = sprintf(
                '    %s["%s<br/><small>%s</small>"] -->|dispatches| E_%s',
                $id,
                $short,
                str_ends_with($module, ':_') ? '('.strtok($module, ':').' root)' : $module,
                $event,
            );
        }
    }

    $lines[] = '    classDef event fill:#f3e8fd,stroke:#a142f4,color:#1a1a1a;';
    $lines[] = '    classDef eventLaravel fill:#fef7e0,stroke:#f9ab00,color:#1a1a1a;';
    $lines[] = '```';
    $lines[] = '';
    $lines[] = '| Event | Dispatched from |';
    $lines[] = '|---|---|';

    foreach ($events as $fqcn => [$eventFqcn, $pkg]) {
        $shortName = basename($fqcn);
        $sites = $dispatches[$shortName] ?? [];
        if ($sites === []) {
            $lines[] = "| **{$shortName}** | _(no dispatch site found)_ |";

            continue;
        }
        $cells = [];
        foreach ($sites as $siteFqcn => $_) {
            $cells[] = '`'.basename(str_replace('\\', '/', $siteFqcn)).'`';
        }
        $lines[] = "| **{$shortName}** | ".implode(', ', array_unique($cells)).' |';
    }

    return implode("\n", $lines)."\n";
}
