<?php

declare(strict_types=1);

namespace ArazzoDocs\ExceptionTreeDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Exception Tree

Every exception class in both packages and what it extends, scanned live from
source. Use this to decide which exception to throw or catch.

MD;

/**
 * @param  array<string, list<ScannedFile>>  $core
 * @param  array<string, list<ScannedFile>>  $laravel
 */
function render(array $core, array $laravel): string
{
    // shortName => [fqcn, parentShortName, module]
    $exceptions = [];
    foreach ([['core', $core], ['laravel', $laravel]] as [$pkg, $modules]) {
        foreach ($modules as $module => $files) {
            foreach ($files as $file) {
                if (!str_ends_with($file->className, 'Exception')) {
                    continue;
                }
                preg_match('/^(?:final\s+)?(?:readonly\s+)?class\s+\w+(?:\s+extends\s+([\w\\\\]+))?/m', $file->content, $m);
                $parent = basename(str_replace('\\', '/', $m[1] ?? '\RuntimeException'));
                $exceptions[$file->className] = [
                    'fqcn' => $file->namespace.'\\'.$file->className,
                    'parent' => $parent,
                    'module' => $module === '_' ? '(root)' : ($pkg === 'laravel' ? "Laravel:{$module}" : $module),
                ];
            }
        }
    }
    ksort($exceptions);

    // include external/parent roots that are not scanned exceptions
    $roots = [];
    foreach ($exceptions as $meta) {
        if (!isset($exceptions[$meta['parent']])) {
            $roots[$meta['parent']] = true;
        }
    }

    $lines = [BANNER, '```mermaid', 'classDiagram', '    direction TB'];

    foreach (array_keys($roots) as $root) {
        $lines[] = sprintf('    class %s["%s"]:::builtin', nodeId($root), $root);
    }
    foreach ($exceptions as $name => $meta) {
        $lines[] = sprintf('    class %s["%s<br/><small>%s</small>"]:::domain', nodeId($name), $name, $meta['module']);
    }

    $seen = [];
    foreach ($exceptions as $name => $meta) {
        $key = "{$name}<--{$meta['parent']}";
        if (isset($seen[$key])) {
            continue;
        }
        $seen[$key] = true;
        $lines[] = sprintf('    %s <|-- %s', nodeId($meta['parent']), nodeId($name));
    }

    $lines[] = '    classDef builtin fill:#f1f5f9,stroke:#64748b,color:#1a1a1a;';
    $lines[] = '    classDef domain fill:#fce8e6,stroke:#ea4335,color:#1a1a1a;';
    $lines[] = '```';
    $lines[] = '';
    $lines[] = '| Exception | Extends | Module |';
    $lines[] = '|---|---|---|';

    foreach ($exceptions as $name => $meta) {
        $lines[] = "| `{$name}` | `{$meta['parent']}` | {$meta['module']} |";
    }

    return implode("\n", $lines)."\n";
}

function nodeId(string $name): string
{
    return preg_replace('/[^A-Za-z0-9_]/', '_', "E_{$name}") ?? $name;
}
