<?php

declare(strict_types=1);

namespace ArazzoDocs\ExpressionAstDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Expression AST Hierarchy

Node classes under `packages/expression/src/Ast`, scanned live from source.
`ExpressionEvaluator` pattern-matches on these node types.

MD;

/**
 * @param  array<string, array<string, list<ScannedFile>>>  $scans  package slug => (module => files)
 */
function render(array $scans): string
{
    $nodes = [];   // className => ['parent' => ?string, 'abstract' => bool]
    foreach ($scans['expression']['Ast'] ?? [] as $file) {
        if (!str_starts_with($file->relativeDir, 'Ast')) {
            continue;
        }
        preg_match('/^(abstract\s+)?(?:final\s+)?(?:readonly\s+)?class\s+(\w+)(?:\s+extends\s+([\w\\\\]+))?/m', $file->content, $m);
        if (!isset($m[2])) {
            continue;
        }
        $nodes[$file->className] = [
            'parent' => isset($m[3]) ? basename(str_replace('\\', '/', $m[3])) : null,
            'abstract' => ($m[1] ?? '') !== '',
        ];
    }
    ksort($nodes);

    // part classes hanging off StepRef (RequestPart, ResponsePart, ...)
    $partClasses = [];
    foreach ($nodes as $name => $meta) {
        if (str_ends_with($name, 'Part')) {
            $partClasses[] = $name;
        }
    }
    sort($partClasses);

    $lines = [BANNER, '```mermaid', 'classDiagram', '    direction TB'];

    foreach ($nodes as $name => $meta) {
        $label = $meta['abstract'] ? "{$name}<br/><small>abstract</small>" : $name;
        $lines[] = sprintf(
            '    class %s["%s"]:::%s',
            nodeId($name),
            $label,
            styleFor($name, $partClasses),
        );
    }

    $seen = [];
    foreach ($nodes as $name => $meta) {
        if ($meta['parent'] === null) {
            continue;
        }
        $key = "{$name}<--{$meta['parent']}";
        if (isset($seen[$key])) {
            continue;
        }
        $seen[$key] = true;
        $lines[] = sprintf('    %s <|-- %s', nodeId($meta['parent']), nodeId($name));
    }

    // composition: StepRef carries exactly one StepPart
    if (isset($nodes['StepRef'], $nodes['StepPart'])) {
        $lines[] = sprintf('    %s "1" o-- "1" %s : part', nodeId('StepRef'), nodeId('StepPart'));
    }

    $lines[] = '    classDef root fill:#f1f5f9,stroke:#64748b,color:#1a1a1a;';
    $lines[] = '    classDef node fill:#e8f0fe,stroke:#4285f4,color:#1a1a1a;';
    $lines[] = '    classDef part fill:#fef7e0,stroke:#f9ab00,color:#1a1a1a;';
    $lines[] = '```';
    $lines[] = '';

    return implode("\n", $lines)."\n";
}

function nodeId(string $name): string
{
    return preg_replace('/[^A-Za-z0-9_]/', '_', "A_{$name}") ?? $name;
}

/** @param list<string> $partClasses */
function styleFor(string $name, array $partClasses): string
{
    if ($name === 'ExpressionAst') {
        return 'root';
    }
    if (in_array($name, $partClasses, true)) {
        return 'part';
    }

    return 'node';
}
