<?php

declare(strict_types=1);

namespace ArazzoDocs\ExtensionPointsDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Extension Points (SPI)

Every contract interface that other code implements, with its live
implementation set — the package's openness map. Contracts under a `Contracts`
directory are deliberate SPI; others appear when the codebase itself treats an
interface polymorphically. Interfaces nobody implements are listed separately:
either dead seams or seams waiting for their first adapter.

MD;

const CONTRACT_DIR_PATTERN = '/(^|\/)Contracts(\/|$)/';

/**
 * @param array<string, list<ScannedFile>> $core
 * @param array<string, list<ScannedFile>> $laravel
 */
function render(array $core, array $laravel): string
{
    $files = [];
    foreach ([[...$core], [...$laravel]] as $modules) {
        foreach ($modules as $moduleFiles) {
            foreach ($moduleFiles as $file) {
                if ($file->isInterface && isSpi($file)) {
                    $files[$file->className] = ['file' => $file, 'implementations' => []];
                }
            }
        }
    }

    foreach ([[...$core], [...$laravel]] as $modules) {
        foreach ($modules as $moduleFiles) {
            foreach ($moduleFiles as $file) {
                if ($file->isInterface || preg_match('/implements\s+([^;{]+)/', $file->content, $m) !== 1) {
                    continue;
                }
                foreach (explode(',', str_replace('|', ',', $m[1])) as $raw) {
                    $name = basename(str_replace('\\', '/', trim($raw)));
                    if (isset($files[$name])) {
                        $files[$name]['implementations'][$file->namespace . '\\' . $file->className] = true;
                    }
                }
            }
        }
    }
    ksort($files);

    [$implemented, $unimplemented] = array_partition(
        $files,
        fn (array $entry): bool => $entry['implementations'] !== [],
    );

    $lines = [BANNER];

    if ($implemented === []) {
        return BANNER . "_No implemented contracts found._\n";
    }

    $lines[] = '```mermaid';
    $lines[] = 'mindmap';
    $lines[] = '  root((SPI contracts))';
    foreach ($implemented as $interfaceName => $entry) {
        $lines[] = '    ' . $interfaceName;
        foreach (array_keys($entry['implementations']) as $fqcn) {
            $lines[] = '      ' . short($fqcn);
        }
    }
    $lines[] = '```';

    // per-contract table with packages and SPI marker
    $lines[] = '';
    $lines[] = '| Contract | SPI dir | Implementations |';
    $lines[] = '|---|---|---|';
    foreach ($implemented as $interfaceName => $entry) {
        /** @var ScannedFile $file */
        $file = $entry['file'];
        $cells = [];
        foreach (array_keys($entry['implementations']) as $fqcn) {
            $cells[] = '`' . short((string) $fqcn) . '` <small>' . packageOf((string) $fqcn) . '</small>';
        }
        $lines[] = sprintf(
            '| `%s` | %s | %s |',
            $interfaceName,
            isContractDir($file) ? '**yes**' : 'no',
            implode(', ', $cells),
        );
    }

    if ($unimplemented !== []) {
        $lines[] = '';
        $lines[] = '## Unimplemented contracts';
        $lines[] = '';
        $lines[] = 'Declared but nothing in src implements them — candidates for removal or for a first adapter:';
        $lines[] = '';
        foreach ($unimplemented as $interfaceName => $entry) {
            /** @var ScannedFile $file */
            $file = $entry['file'];
            $lines[] = '- `' . $interfaceName . '` <small>' . str_replace('\\', '/', $file->relativeDir) . '</small>';
        }
    }

    return implode("\n", $lines) . "\n";
}

/** @param list<mixed> $items */
function array_partition(array $items, callable $predicate): array
{
    $true = [];
    $false = [];
    foreach ($items as $key => $item) {
        if ($predicate($item)) {
            $true[$key] = $item;
        } else {
            $false[$key] = $item;
        }
    }

    return [$true, $false];
}

function isSpi(ScannedFile $file): bool
{
    return isContractDir($file)
        || preg_match('/(?:Interface)$/', $file->className) === 1;
}

function isContractDir(ScannedFile $file): bool
{
    return preg_match(CONTRACT_DIR_PATTERN, $file->relativeDir) === 1;
}

function short(string $fqcn): string
{
    $parts = explode('\\', $fqcn);

    return end($parts);
}

function packageOf(string $fqcn): string
{
    return str_contains($fqcn, 'Laravel') ? 'laravel' : 'core';
}
