<?php

declare(strict_types=1);

namespace ArazzoDocs\FailureModesDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Failure Modes

How the system fails, scanned live from `packages/*/src`:

1. **Throw sites** — every exception class and who raises it.
2. **Catch sites** — every handler; empty catch bodies are flagged as
   potential swallowed failures.
3. **Safety interlocks** — budget/limit/TTL guards that bound runaway runs.

Regenerated before every commit.

MD;

/**
 * @param  array<string, array<string, list<ScannedFile>>>  $scans  package slug => (module => files)
 */
function render(array $scans): string
{
    [$allFiles, $classIndex] = indexClasses($scans);
    $exceptions = exceptionIndex($allFiles);

    [$throws, $catches, $swallowed] = scanSites($allFiles, $exceptions, $classIndex);
    $interlocks = scanInterlocks($allFiles);

    $lines = [BANNER];

    // --- throw sites ---
    ksort($throws);
    $lines[] = '## Throw sites';
    $lines[] = '';
    $lines[] = '| Exception | Raised by |';
    $lines[] = '|---|---|';
    foreach ($throws as $exception => $throwers) {
        sort($throwers);
        $cells = [];
        foreach ($throwers as [$fqcn, $module]) {
            $cells[] = '`'.short($fqcn).'` <small>'.$module.'</small>';
        }
        $lines[] = '| **'.$exception.'** | '.implode(', ', array_unique($cells)).' |';
    }
    foreach ($exceptions as $name => $fqcn) {
        if (!isset($throws[$name])) {
            $lines[] = '| **'.$name.'** | _(never raised in src)_ |';
        }
    }

    // --- catch sites ---
    $lines[] = '';
    $lines[] = '## Catch sites';
    $lines[] = '';
    $lines[] = '| Caught type | Handled by | Flag |';
    $lines[] = '|---|---|---|';
    ksort($catches);
    if ($catches === []) {
        $lines[] = '| — | — | — |';
    }
    foreach ($catches as $type => $handlers) {
        sort($handlers);
        foreach (array_unique($handlers) as $handler) {
            $isSwallowed = isset($swallowed[$type][$handler]);
            $lines[] = '| `'.$type.'` | `'.short($handler).'` | '.($isSwallowed ? '⚠ empty body' : '').' |';
        }
    }

    // --- interlocks ---
    // budget-class exceptions act as guards too: raising them IS the interlock
    $budgetExceptions = array_filter(
        array_keys($throws),
        fn (string $name): bool => (bool) preg_match('/(?:Exceeded|Cycle|Depth|Budget|Timeout)/', $name),
    );

    $lines[] = '';
    $lines[] = '## Safety interlocks';
    $lines[] = '';
    $lines[] = '| Guard | Class | Limit expression |';
    $lines[] = '|---|---|---|';
    ksort($interlocks);
    foreach ($budgetExceptions as $exception) {
        $raisers = [];
        foreach ($throws[$exception] as [$fqcn]) {
            $raisers[] = '`'.short($fqcn).'`';
        }
        $lines[] = '| throws **'.$exception.'** | '.implode(', ', array_unique($raisers)).' | — |';
    }
    if ($interlocks === []) {
        $lines[] = '| — | — | — |';
    } else {
        foreach ($interlocks as [$name, $fqcn, $expr]) {
            $lines[] = '| '.$name.' | `'.short($fqcn).'` | `'.$expr.'` |';
        }
    }

    return implode("\n", $lines)."\n";
}

/**
 * @param  array<string, array<string, list<ScannedFile>>>  $scans
 * @return array{0: list<ScannedFile>, 1: array<string, string>}
 */
function indexClasses(array $scans): array
{
    $files = \ArazzoDocs\flattenScans($scans);
    $index = [];
    foreach ($files as $file) {
        $fqcn = $file->namespace.'\\'.$file->className;
        if (!isset($index[$file->className])) {
            $index[$file->className] = $fqcn;
        } else {
            $index[$file->className] = ''; // ambiguous short name
        }
    }

    return [$files, $index];
}

/** @param list<ScannedFile> $files */
function exceptionIndex(array $files): array
{
    $index = [];
    foreach ($files as $file) {
        if ($file->isInterface || preg_match('/^\s*(?:(?:abstract|final|readonly)\s+)*class\s/m', $file->content) !== 1) {
            continue;
        }
        if (!preg_match('/\bextends\s+\\\\?(?:[\w\\\\]*\\\\)*(\w*Exception|Throwable)\b/', $file->content)) {
            continue;
        }
        $index[$file->className] = $file->namespace.'\\'.$file->className;
    }
    ksort($index);

    return $index;
}

/**
 * @param  list<ScannedFile>  $files
 * @param  array<string, string>  $exceptions
 * @param  array<string, string>  $classIndex
 * @return array{0: array<string, list<array{string, string}>>, 1: array<string, list<string>>, 2: array<string, array<string, true>>}
 */
function scanSites(array $files, array $exceptions, array $classIndex): array
{
    $throws = [];
    $catches = [];
    $swallowed = [];

    foreach ($files as $file) {
        $selfFqcn = $file->namespace.'\\'.$file->className;
        $aliases = aliasMap($file);

        $resolve = function (string $token) use ($classIndex, $aliases): ?string {
            $token = ltrim(trim($token), '\\');
            if ($token === '' || !preg_match('/^[A-Za-z_][\w\\\\]*$/', $token)) {
                return null;
            }
            if (str_ends_with($token, 'Exception') || $token === 'Throwable') {
                // resolve through alias / same-namespace / unique-short fallback
                if (isset($aliases[$token]) && $aliases[$token] !== '') {
                    return $aliases[$token];
                }
                if (isset($classIndex[$token])) {
                    return $classIndex[$token] !== '' ? $classIndex[$token] : $token;
                }

                return $token; // vendor/global type (Psr\Log\..., RuntimeException)
            }

            return null;
        };

        // throws
        preg_match_all('/throw\s+new\s+(?:\\\\)?([\w\\\\]+)\s*\(/', $file->content, $thrown);
        foreach ($thrown[1] as $rawType) {
            $short = basename(str_replace('\\', '/', $rawType));
            $resolved = $resolve($short) ?? $resolve($rawType);
            $key = $resolved !== null ? short((string) $resolved) : $short;
            $throwModule = \ArazzoDocs\fileModule($file);
            $throws[$key][] = [$selfFqcn, $throwModule === '_' ? "({$file->package} root)" : \ArazzoDocs\packageKey($file->package, $throwModule)];
        }

        // catches — with swallowed-body detection
        if (preg_match_all('/catch\s*\(\s*([\w\\\\|?]+)\s+\$\w+\s*\)\s*\{/', $file->content, $caught, PREG_OFFSET_CAPTURE)) {
            foreach ($caught[1] as $instance) {
                $types = explode('|', trim($instance[0]));
                $bracePos = (int) $caught[0][0][1] + strlen((string) $caught[0][0][0]) - 1;
                $isEmptyBody = catchBodyIsEmpty($file->content, $bracePos);
                foreach ($types as $type) {
                    $clean = ltrim(trim($type), '\\?');
                    $short = basename(str_replace('\\', '/', $clean));
                    $resolved = $resolve($short) ?? $resolve($clean);
                    $label = $resolved !== null && str_contains((string) $resolved, '\\') ? short((string) $resolved) : $clean;
                    $catches[$label][] = $selfFqcn;
                    if ($isEmptyBody) {
                        $swallowed[$label][$selfFqcn] = true;
                    }
                }
            }
        }
    }

    foreach ($catches as &$handlers) {
        $handlers = array_values(array_unique($handlers));
    }
    unset($handlers);
    ksort($catches);
    ksort($swallowed);

    return [$throws, $catches, $swallowed];
}

/** Naive brace match from the opening brace; returns true when body holds only whitespace/comments. */
function catchBodyIsEmpty(string $content, int $bracePos): bool
{
    if ($bracePos < 0) {
        return false;
    }
    $depth = 0;
    $length = strlen($content);
    for ($i = $bracePos; $i < $length; $i++) {
        $char = $content[$i];
        if ($char === '{') {
            $depth++;

            continue;
        }
        if ($char === '}') {
            $depth--;
            if ($depth === 0) {
                $body = substr($content, $bracePos + 1, $i - $bracePos - 1);
                $stripped = preg_replace(['#//[^\n]*#', '#/\*.*?\*/#s'], '', $body);

                return trim((string) $stripped) === '';
            }
        }
    }

    return false;
}

/**
 * Budget/limit/TTL guards: typed constants and promoted properties whose
 * names signal a bound on runaway behaviour.
 *
 * @param  list<ScannedFile>  $files
 * @return list<array{string, string, string}>
 */
function scanInterlocks(array $files): array
{
    $patternName = '/(?:max|min|limit|budget|ttl|timeout|depth|attempt)/i';
    $found = [];

    foreach ($files as $file) {
        $selfFqcn = $file->namespace.'\\'.$file->className;

        if (preg_match_all('/const\s+(\w+)\s*=\s*([^;\n]+);/', $file->content, $consts, PREG_SET_ORDER)) {
            foreach ($consts as $c) {
                if (preg_match($patternName, $c[1]) !== 1) {
                    continue;
                }
                $found[] = ['const '.$c[1], $selfFqcn, trim($c[2])];
            }
        }

        if (preg_match_all('/(?:private|protected)(?:\s+readonly)?\s+(?:int|float|\?)\s+\$(\w+)\s*=\s*([^;,)]+)[;,)]/', $file->content, $props, PREG_SET_ORDER)) {
            foreach ($props as $p) {
                if (preg_match($patternName, $p[1]) !== 1) {
                    continue;
                }
                $found[] = ['prop '.$p[1], $selfFqcn, trim($p[2])];
            }
        }
    }

    usort($found, fn (array $a, array $b): int => [$a[1], $a[0]] <=> [$b[1], $b[0]] ?: strcmp($a[2], $b[2]));

    return $found;
}

function short(string $fqcn): string
{
    $parts = explode('\\', $fqcn);

    return end($parts);
}

/** @return array<string, string> alias => fqcn */
function aliasMap(ScannedFile $file): array
{
    $map = [];
    foreach ($file->useStatements as $statement) {
        if (preg_match('/^([\w\\\\]+)\s+as\s+(\w+)$/', $statement, $m)
            && str_starts_with($m[1], 'Alama\\Arazzo\\')
        ) {
            $map[$m[2]] = $m[1];
        }
    }

    return $map;
}
