<?php

declare(strict_types=1);

namespace ArazzoDocs\FitnessFunctionsDoc;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Architecture Fitness Functions

Every automated check that guards an architectural property, what it protects,
and where it is enforced. A property without a row here is protected only by
good intentions. Enforcement artifacts are verified live — a missing hook or
script turns its row red.

MD;

/**
 * [fitness function, guarded property, enforcement artifact (repo-relative,
 * must exist to be green), cadence, evidence doc]
 */
const FUNCTIONS = [
    ['Layer order holds', 'Dependencies only point downward', '.githooks/pre-commit', 'every commit', 'layering.md'],
    ['Sankey acyclicity', 'Module graph has no directed cycles worth drawing', '.githooks/pre-commit', 'every commit', 'dependency-flow.md'],
    ['Public API drift visible', 'Any signature change is a deliberate review event', '.githooks/pre-commit', 'every commit', 'public-api.md'],
    ['No debug leftovers', 'No dd/var_dump/dump in src', 'packages/core/tests/ArchTest.php', 'every test run', 'quality-gates.md'],
    ['Core stays framework-free', 'packages/core never imports Illuminate', 'packages/core/tests/ArchTest.php', 'every test run', 'boundaries-audit.md'],
    ['Spec DTOs strict', 'Spec value objects are readonly + typed', 'packages/core/tests/ArchTest.php', 'every test run', 'aggregate-map.md'],
    ['Gate scorecard fresh', 'Pint/PHPStan/Pest measured and recorded', 'scripts/quality-gates.php', 'manual / CI', 'quality-gates.md'],
    ['Failure budget trend', 'Errors and failures move down over time', 'storage/quality-history.jsonl', 'per measurement', 'gate-trend.md'],
    ['Mutation score tracked', 'Behavioural coverage, not just line coverage', 'scripts/quality-gates.php', 'manual (--with-mutations)', 'gate-trend.md'],
    ['Spec conformance', 'Official OAI corpus passes through the real stack', 'scripts/generate-conformance-matrix.php', 'out-of-band', '../CONFORMANCE.md'],
];

function render(string $root): string
{
    $lines = [
        BANNER,
        '| Fitness function | Guarded property | Enforcement | Cadence | Evidence | Status |',
        '|---|---|---|---|---|---|',
    ];

    $green = 0;
    foreach (FUNCTIONS as [$name, $property, $artifact, $cadence, $doc]) {
        $exists = is_file($root . '/' . $artifact);
        $green += $exists ? 1 : 0;
        $status = $exists ? '**enforced**' : '⚠ **artifact missing**';
        $lines[] = sprintf(
            '| %s | %s | `%s` | %s | `%s` | %s |',
            $name,
            $property,
            $artifact,
            $cadence,
            $doc,
            $status,
        );
    }

    $lines[] = '';
    $lines[] = sprintf('**%d / %d enforced.**', $green, count(FUNCTIONS));
    $lines[] = '';
    $lines[] = '## Known gaps';
    $lines[] = '';
    $lines[] = '- Mutation testing runs only on demand (`make quality-gates ARGS=--with-mutations`); no MSI threshold fails the build yet.';
    $lines[] = '- `bc-diff.md` activates at the first release tag; until then BC drift has no gate, only visibility.';
    $lines[] = '- The conformance matrix generator runs out-of-band; it is not wired into `composer docs` / pre-commit.';

    return implode("\n", $lines) . "\n";
}
