<?php

declare(strict_types=1);

namespace ArazzoDocs\GateTrendDoc;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Quality Gate Trend

Failure counts over time from `storage/quality-history.jsonl`, appended by
every `make quality-gates` run (one entry per day, last measurement wins).
The line should only ever move down — an upward step is a regression that the
scorecard alone would show you too late.

MD;

/**
 * @param  array<string, mixed>  $_core  unused (signature symmetry)
 * @param  array<string, mixed>  $_laravel  unused
 */
function render(array $_core = [], array $_laravel = [], ?string $historyPath = null): string
{
    $historyPath ??= dirname(__DIR__, 2).'/storage/quality-history.jsonl';

    $points = readPoints($historyPath);

    if ($points === []) {
        return BANNER.<<<'MD'
_No history yet._

Every `make quality-gates` run appends today's measurements to
`storage/quality-history.jsonl`. Run it now, then again after future work
sessions — this chart turns those entries into the trend.

MD;
    }

    ksort($points);

    $dates = [];
    $stanErrors = [];
    $testFailures = [];
    foreach ($points as $date => $point) {
        $dates[] = '"'.$date.'"';
        $stanErrors[] = (string) ($point['stan_errors'] ?? 0);
        $testFailures[] = (string) ($point['test_failures'] ?? 0);
    }

    $yMax = max(10, ...array_map(intval(...), [...$stanErrors, ...$testFailures]));
    $yMax = (int) (ceil($yMax * 1.2 / 10) * 10);

    $lines = [
        BANNER,
        sprintf('%d measurement day(s): %s → %s.', count($dates), trim($dates[0], '"'), trim(rtrim(end($dates), '"'))),
        '',
        '```mermaid',
        'xychart-beta',
        '    title "Gate failures per day"',
        '    x-axis ['.implode(', ', $dates).']',
        sprintf('    y-axis "Failures" 0 --> %d', $yMax),
        '    line "PHPStan errors" ['.implode(', ', $stanErrors).']',
        '    line "Test failures" ['.implode(', ', $testFailures).']',
        '```',
        '',
        '| Day | PHPStan errors | Test failures | MSI (core) | Gates failing |',
        '|---|---:|---:|---:|---:|',
    ];

    foreach ($points as $date => $point) {
        $lines[] = sprintf(
            '| %s | %d | %d | %s | %d |',
            $date,
            $point['stan_errors'] ?? 0,
            $point['test_failures'] ?? 0,
            isset($point['msi']) ? sprintf('%.1f%%', $point['msi']) : '—',
            $point['failing_gates'] ?? 0,
        );
    }

    return implode("\n", $lines)."\n";
}

/**
 * @return array<string, array<string, int|float>> date => aggregated metrics
 */
function readPoints(string $path): array
{
    if (!is_file($path)) {
        return [];
    }

    $byDate = [];
    foreach (file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [] as $line) {
        $entry = json_decode($line, true);
        if (!is_array($entry) || !isset($entry['date'], $entry['gates']) || !is_array($entry['gates'])) {
            continue;
        }
        // last measurement of a day wins
        $byDate[(string) $entry['date']] = aggregate((array) $entry['gates']);
    }

    return $byDate;
}

/** @param array<string, mixed> $gates */
function aggregate(array $gates): array
{
    $out = ['stan_errors' => 0, 'test_failures' => 0, 'failing_gates' => 0];
    foreach ($gates as $id => $record) {
        if (!is_array($record)) {
            continue;
        }
        if (($record['status'] ?? null) === 'fail') {
            $out['failing_gates']++;
        }
        if (str_starts_with((string) $id, 'phpstan')) {
            $out['stan_errors'] += (int) ($record['errors'] ?? 0);
        }
        if (str_starts_with((string) $id, 'pest')) {
            $out['test_failures'] += (int) ($record['failed'] ?? 0);
        }
        if ($id === 'mutations-core' && isset($record['msi_percent'])) {
            $out['msi'] = (float) $record['msi_percent'];
        }
    }

    return $out;
}
