<?php

declare(strict_types=1);

namespace ArazzoDocs\IntegrationContextDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Integration Context (C4-lite)

The system boundary view: what hosts the package, which infrastructure it
touches through its persistence/queue contracts, and what external networks it
reaches. Nodes and edges are derived from the live `implements` graph plus
known technology markers in implementation names (`Redis*`, `Database*`,
`Queue*`, Guzzle) — when a new adapter appears it joins the map automatically.

MD;

/**
 * Class-name marker => [external system node, human label].
 * First match wins; order matters.
 */
const TECH_MARKERS = [
    'Redis' => ['redis', 'Redis'],
    'Database' => ['sql', 'SQL database'],
    'Db[A-Z]' => ['sql', 'SQL database'],
    'Queue' => ['queue', 'Application queue backend'],
];

const HTTP_MARKERS = [
    'HttpFetcher' => 'HTTP network',
    'Psr18HttpClient' => 'HTTP network',
    'GuzzleHttp\Client' => 'HTTP network',
    'OpenAiClient' => 'OpenAI API',
];

/**
 * @param array<string, list<ScannedFile>> $core
 * @param array<string, list<ScannedFile>> $laravel
 */
function render(array $core, array $laravel): string
{
    $files = [];
    foreach ([[...$core], [...$laravel]] as $modules) {
        foreach ($modules as $moduleFiles) {
            foreach ($moduleFiles as $file) {
                $files[$file->namespace . '\\' . $file->className] = $file;
            }
        }
    }
    ksort($files);

    [$infraEdges, $httpEdges] = scanEdges($files);

    if ($infraEdges === [] && $httpEdges === []) {
        return BANNER . "_No integration adapters found._\n";
    }

    $lines = [BANNER, '```mermaid', 'flowchart LR'];

    // declare external system nodes first so every edge has a target
    $systems = [];
    foreach ($infraEdges as [, $systemId, $label]) {
        $systems[$systemId] = $label;
    }
    foreach ($httpEdges as $targetLabel) {
        $systems[$targetLabel === 'OpenAI API' ? 'openai' : 'net'] = $targetLabel;
    }

    // hosting context
    $lines[] = '    subgraph Host["Consumer application"]';
    $lines[] = '        LARAVEL["Laravel app<br/><small>service provider + bindings</small>"]:::host';
    $lines[] = '        CLI["CLI users<br/><small>bin/arazzo</small>"]:::host';
    $lines[] = '    end';

    $lines[] = '    subgraph Package["alama/php-arazzo"]';
    $lines[] = '        CORE["arazzo-core<br/><small>parser · validator · runner</small>"]:::package';
    $lines[] = '        BRIDGE["laravel-arazzo<br/><small>adapters + persistence</small>"]:::package';
    $lines[] = '        CLI --> CORE';
    $lines[] = '        LARAVEL --> BRIDGE';
    $lines[] = '        BRIDGE --> CORE';
    $lines[] = '    end';

    foreach ($infraEdges as [$adapter, $systemId, $label]) {
        $node = nodeId($adapter);
        $lines[] = sprintf('        %s["%s"]:::adapter', $node, short($adapter));
        $lines[] = sprintf('        %s --- BRIDGE', $node);
        unset($label);
        $lines[] = sprintf('        %s --- %s', $node, $systemId);
    }

    foreach ($httpEdges as $sourceClass => $targetLabel) {
        $node = nodeId($sourceClass);
        $lines[] = sprintf('        %s["%s"]:::adapter', $node, short($sourceClass));
        $lines[] = sprintf('        %s --- CORE', $node);
        $lines[] = sprintf('        %s --- %s', $node, $targetLabel === 'OpenAI API' ? 'openai' : 'net');
    }

    ksort($systems);
    foreach ($systems as $id => $label) {
        $lines[] = sprintf('    %s["%s"]:::system', $id, $label);
    }

    $lines[] = '    classDef host fill:#f1f3f4,stroke:#9aa0a6,color:#1a1a1a;';
    $lines[] = '    classDef package fill:#e8f0fe,stroke:#4285f4,color:#1a1a1a;';
    $lines[] = '    classDef adapter fill:#e6f4ea,stroke:#34a853,color:#1a1a1a;';
    $lines[] = '    classDef system fill:#fef7e0,stroke:#f9ab00,color:#1a1a1a;';
    $lines[] = '```';

    return implode("\n", $lines) . "\n";
}

/**
 * Adapter classes → external system edges via implements + name markers.
 *
 * @param array<string, ScannedFile> $files
 *
 * @return array{0: list<array{string, string, string}>, 1: array<string, string>}
 */
function scanEdges(array $files): array
{
    $contracts = [
        'StateStoreInterface', 'EventLedgerInterface', 'ExecutionRegistryInterface',
        'LockManagerInterface', 'DefinitionRegistryInterface', 'PendingCorrelationRegistryInterface',
        'QueueDriverInterface',
    ];

    $infraEdges = [];
    $seenAdapters = [];
    foreach ($files as $fqcn => $file) {
        if ($file->isInterface || preg_match('/implements\s+([^;{]+)/', $file->content, $m) !== 1) {
            continue;
        }
        $implemented = array_map(
            fn (string $raw): string => basename(str_replace('\\', '/', trim($raw))),
            explode(',', str_replace('|', ',', $m[1])),
        );
        $matchesContract = !empty(array_intersect($implemented, $contracts));
        if (!$matchesContract && !str_contains($fqcn, 'Arazzo\\')) {
            continue;
        }

        foreach (TECH_MARKERS as $markerPattern => [$systemId, $label]) {
            $pattern = str_contains($markerPattern, '[')
                ? '/(?:' . $markerPattern . ')/'
                : '/' . preg_quote($markerPattern, '/') . '/';
            if (preg_match($pattern, $file->className) !== 1 || isset($seenAdapters[$fqcn])) {
                continue;
            }
            $seenAdapters[$fqcn] = true;
            $infraEdges[] = [$fqcn, $systemId, $label];

            break;
        }
    }

    $httpEdges = [];
    foreach ($files as $fqcn => $file) {
        foreach (HTTP_MARKERS as $marker => $systemLabel) {
            $needle = str_contains($marker, '\\')
                ? 'use ' . $marker . ';'
                : 'class ' . $marker;
            if (!str_contains($file->content, $needle) && $file->className !== $marker) {
                continue;
            }
            $httpEdges[$fqcn] = $systemLabel;

            break;
        }
    }
    ksort($httpEdges);

    return [$infraEdges, $httpEdges];
}

function short(string $fqcn): string
{
    $parts = explode('\\', $fqcn);

    return end($parts);
}

function nodeId(string $value): string
{
    return 'A_' . ((preg_replace('/[^A-Za-z0-9_]/', '_', $value)) ?? $value);
}
