<?php

declare(strict_types=1);

namespace ArazzoDocs\LayeringDoc;

use const ArazzoDocs\PACKAGE_LAYER_ORDER;

use ArazzoDocs\NamespaceGraphDoc;
use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Layering Map

The real architecture is six composer packages, not one monolith with many
namespaces: `contracts <- expression <- document <- runner <- cli <- laravel`,
read directly from each package's `composer.json` `require`. A package may
only depend on packages strictly below it in that chain. Edges that point
**upward across a package boundary** violate the layering and are drawn red —
any red edge here is either a design regression to fix or a dependency
direction to consciously revise (which would mean editing the actual
`composer.json require`, since this order is derived from it, not declared
here).

Modules are grouped into their owning package's subgraph so the diagram shows
package boundaries directly, not just a flat list of namespaces.

MD;

/**
 * @param  array<string, list<ScannedFile>>  $core
 * @param  array<string, list<ScannedFile>>  $laravel
 */
function render(array $core, array $laravel): string
{
    $all = NamespaceGraphDoc\merge($core, $laravel);

    // fqcn => package (ground truth from the scanner, not guessed from name)
    $classPackage = [];
    // module => package (every module belongs to exactly one package)
    $modulePackage = [];
    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            $classPackage[$file->namespace.'\\'.$file->className] = $file->package;
            $modulePackage[$module] = $file->package;
        }
    }

    [$edges, $violations, $packageEdges, $packageViolations] = computeEdges($all, $classPackage, $modulePackage);

    $lines = [BANNER, '```mermaid', 'flowchart TB'];

    // group modules by package, packages ordered bottom-to-top
    $byPackage = [];
    foreach ($all as $module => $files) {
        $byPackage[$modulePackage[$module] ?? '?'][] = $module;
    }
    foreach (PACKAGE_LAYER_ORDER as $package) {
        $modules = $byPackage[$package] ?? [];
        if ($modules === []) {
            continue;
        }
        sort($modules);
        $lines[] = sprintf('    subgraph PKG_%s["%s"]', nodeId($package), $package);
        foreach ($modules as $module) {
            $label = $module === '_' ? '(package root)' : $module;
            $lines[] = sprintf('        %s["%s"]:::%s', nodeId($module), $label, $package === 'laravel' ? 'laravelNode' : 'node');
        }
        $lines[] = '    end';
    }
    // any module whose package fell outside PACKAGE_LAYER_ORDER (shouldn't happen, but stay honest)
    foreach ($byPackage as $package => $modules) {
        if (in_array($package, PACKAGE_LAYER_ORDER, true)) {
            continue;
        }
        sort($modules);
        $lines[] = sprintf('    subgraph PKG_%s["%s (unclassified)"]', nodeId($package === '' ? 'unknown' : $package), $package === '' ? 'unknown package' : $package);
        foreach ($modules as $module) {
            $lines[] = sprintf('        %s["%s"]:::rootNode', nodeId($module), $module === '_' ? '(package root)' : $module);
        }
        $lines[] = '    end';
    }

    foreach ($edges as [$from, $to, $isViolation]) {
        $arrow = $isViolation ? '-.->|violation|' : '-->';
        $lines[] = sprintf('    %s %s %s', nodeId($from), $arrow, nodeId($to));
    }

    $lines[] = '    classDef node fill:#e8f0fe,stroke:#4285f4,color:#1a1a1a;';
    $lines[] = '    classDef laravelNode fill:#fef7e0,stroke:#f9ab00,color:#1a1a1a;';
    $lines[] = '    classDef rootNode fill:#f1f3f4,stroke:#9aa0a6,color:#1a1a1a;';
    $lines[] = '```';

    // --- package-level rollup: the primary answer to "is this layered?" ---
    $lines[] = '';
    $lines[] = '## Package boundaries';
    $lines[] = '';
    if ($packageViolations === []) {
        $lines[] = '**No package-level layering violations.** Every cross-package `use` points downward through `contracts -> expression -> document -> runner -> cli -> laravel`.';
    } else {
        $lines[] = sprintf('**%d package boundary violation(s):**', count($packageViolations));
        $lines[] = '';
        $lines[] = '| Package | ↑ depends on package | Refs | Modules involved |';
        $lines[] = '|---|---|---:|---|';
        usort($packageViolations, fn (array $a, array $b): int => $b[2] <=> $a[2] ?: strcmp($a[0], $b[0]));
        foreach ($packageViolations as [$from, $to, $weight, $moduleRefs]) {
            $moduleCells = implode(', ', array_map(
                fn (string $pair): string => '`'.$pair.'`',
                array_slice($moduleRefs, 0, 6),
            )).(count($moduleRefs) > 6 ? sprintf(' + %d more', count($moduleRefs) - 6) : '');
            $lines[] = sprintf('| `%s` | `%s` | %d | %s |', $from, $to, $weight, $moduleCells);
        }
    }

    $lines[] = '';
    $lines[] = '### All package edges (reference counts)';
    $lines[] = '';
    $lines[] = '| From package | To package | Refs |';
    $lines[] = '|---|---|---:|';
    ksort($packageEdges);
    foreach ($packageEdges as $from => $targets) {
        ksort($targets);
        foreach ($targets as $to => $weight) {
            $lines[] = sprintf('| `%s` | `%s` | %d |', $from, $to, $weight);
        }
    }

    // --- module-level detail, kept for intra-investigation ---
    $lines[] = '';
    $lines[] = '## Module-level detail';
    $lines[] = '';
    if ($violations === []) {
        $lines[] = '**No module-level layering violations.**';
    } else {
        $lines[] = sprintf('**%d module-level violation(s) found:**', count($violations));
        $lines[] = '';
        $lines[] = '| From | ↑ depends on | Weight |';
        $lines[] = '|---|---|---:|';
        usort($violations, fn (array $a, array $b): int => $b[2] <=> $a[2] ?: strcmp(labelOf($a[0]), labelOf($b[0])));
        foreach ($violations as [$from, $to, $weight]) {
            $lines[] = sprintf('| `%s` | `%s` | %d |', labelOf($from), labelOf($to), $weight);
        }
    }

    return implode("\n", $lines)."\n";
}

/**
 * @param  array<string, list<ScannedFile>>  $all
 * @param  array<string, string>  $classPackage
 * @param  array<string, string>  $modulePackage
 * @return array{
 *     0: list<array{string, string, bool}>,
 *     1: list<array{string, string, int}>,
 *     2: array<string, array<string, int>>,
 *     3: list<array{string, string, int, list<string>}>
 * }
 */
function computeEdges(array $all, array $classPackage, array $modulePackage): array
{
    $weights = [];
    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            foreach ($file->uses as $use) {
                $target = classModuleOf($use, $all);
                if ($target === null || $target === $module) {
                    continue;
                }
                $weights[$module][$target] = ($weights[$module][$target] ?? 0) + 1;
            }
        }
    }

    $edges = [];
    $violations = [];
    /** @var array<string, array<string, int>> $packageEdges */
    $packageEdges = [];
    /** @var array<string, array<string, array<string, true>>> $packageModulePairs */
    $packageModulePairs = [];
    foreach ($weights as $from => $targets) {
        ksort($targets);
        $fromPackage = $modulePackage[$from] ?? '';
        foreach ($targets as $to => $weight) {
            $toPackage = $modulePackage[$to] ?? '';

            $violation = packageRank($toPackage) > packageRank($fromPackage);
            $edges[] = [$from, $to, $violation];
            if ($violation) {
                $violations[] = [$from, $to, $weight];
            }

            if ($toPackage !== $fromPackage) {
                $packageEdges[$fromPackage][$toPackage] = ($packageEdges[$fromPackage][$toPackage] ?? 0) + $weight;
                $packageModulePairs[$fromPackage][$toPackage][labelOf($from).' -> '.labelOf($to)] = true;
            }
        }
    }
    usort($edges, fn (array $a, array $b): int => strcmp($a[0].$a[1], $b[0].$b[1]));

    $packageViolations = [];
    foreach ($packageEdges as $from => $targets) {
        foreach ($targets as $to => $weight) {
            if (packageRank($to) > packageRank($from)) {
                $packageViolations[] = [$from, $to, $weight, array_keys($packageModulePairs[$from][$to] ?? [])];
            }
        }
    }

    return [$edges, $violations, $packageEdges, $packageViolations];
}

/**
 * @param  array<string, list<ScannedFile>>  $all
 */
function classModuleOf(string $fqcn, array $all): ?string
{
    static $index = null;
    if ($index === null) {
        $index = [];
        foreach ($all as $module => $files) {
            foreach ($files as $file) {
                $index[$file->namespace.'\\'.$file->className] = $module;
            }
        }
    }

    return $index[$fqcn] ?? null;
}

/** Lower rank = lower layer, per the real composer require chain. Unknown packages rank top. */
function packageRank(string $package): int
{
    $index = array_search($package, PACKAGE_LAYER_ORDER, true);

    return $index !== false ? (int) $index : count(PACKAGE_LAYER_ORDER) + 1;
}

function labelOf(string $module): string
{
    return match ($module) {
        '_' => '(package root)',
        default => str_starts_with($module, 'Laravel:') ? substr($module, strlen('Laravel:')) : $module,
    };
}

function nodeId(string $module): string
{
    return 'M_'.((preg_replace('/[^A-Za-z0-9_]/', '_', $module)) ?? $module);
}
