<?php

declare(strict_types=1);

namespace ArazzoDocs\LayeringDoc;

use const ArazzoDocs\PACKAGE_LAYER_ORDER;

use ArazzoDocs\NamespaceGraphDoc;
use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Layering Map

The real architecture is six composer packages, not one monolith with many
namespaces: `contracts <- expression <- document <- runner <- cli <- laravel`,
read directly from each package's `composer.json` `require`. A package may
only depend on packages strictly below it in that chain. Edges that point
**upward across a package boundary** violate the layering and are drawn red —
any red edge here is either a design regression to fix or a dependency
direction to consciously revise (which would mean editing the actual
`composer.json require`, since this order is derived from it, not declared
here).

Modules are grouped into their owning package's subgraph so the diagram shows
package boundaries directly, not just a flat list of namespaces.

MD;

/**
 * @param  array<string, array<string, list<ScannedFile>>>  $scans  package slug => (module => files)
 * @param  list<string>|null  $layerOrder  bottom-to-top package order; derived
 *                                         from composer.json by the caller, PACKAGE_LAYER_ORDER fallback.
 */
function render(array $scans, ?array $layerOrder = null): string
{
    $all = NamespaceGraphDoc\merge($scans);

    // fqcn => package (ground truth from the scanner, not guessed from name)
    $classPackage = [];
    // package-qualified key => package (each key belongs to exactly one package)
    $modulePackage = [];
    foreach ($all as $key => $files) {
        foreach ($files as $file) {
            $classPackage[$file->namespace.'\\'.$file->className] = $file->package;
            $modulePackage[$key] = $file->package;
        }
    }

    [$edges, $violations, $packageEdges, $packageViolations] = computeEdges($all, $classPackage, $modulePackage, $layerOrder);

    $lines = [BANNER, '```mermaid', 'flowchart TB'];

    // group package-qualified keys by package, packages ordered bottom-to-top
    $byPackage = [];
    foreach ($all as $key => $files) {
        $byPackage[$modulePackage[$key] ?? '?'][] = $key;
    }
    $layerOrder ??= PACKAGE_LAYER_ORDER;
    foreach ($layerOrder as $package) {
        $keys = $byPackage[$package] ?? [];
        if ($keys === []) {
            continue;
        }
        sort($keys);
        $lines[] = sprintf('    subgraph PKG_%s["%s"]', nodeId($package), $package);
        foreach ($keys as $key) {
            $lines[] = sprintf('        %s["%s"]:::%s', nodeId($key), labelOf($key), $package === 'laravel' ? 'laravelNode' : 'node');
        }
        $lines[] = '    end';
    }
    // any key whose package fell outside the layer order (shouldn't happen, but stay honest)
    foreach ($byPackage as $package => $keys) {
        if (in_array($package, $layerOrder, true)) {
            continue;
        }
        sort($keys);
        $lines[] = sprintf('    subgraph PKG_%s["%s (unclassified)"]', nodeId($package === '' ? 'unknown' : $package), $package === '' ? 'unknown package' : $package);
        foreach ($keys as $key) {
            $lines[] = sprintf('        %s["%s"]:::rootNode', nodeId($key), labelOf($key));
        }
        $lines[] = '    end';
    }

    foreach ($edges as [$from, $to, $isViolation]) {
        $arrow = $isViolation ? '-.->|violation|' : '-->';
        $lines[] = sprintf('    %s %s %s', nodeId($from), $arrow, nodeId($to));
    }

    $lines[] = '    classDef node fill:#e8f0fe,stroke:#4285f4,color:#1a1a1a;';
    $lines[] = '    classDef laravelNode fill:#fef7e0,stroke:#f9ab00,color:#1a1a1a;';
    $lines[] = '    classDef rootNode fill:#f1f3f4,stroke:#9aa0a6,color:#1a1a1a;';
    $lines[] = '```';

    // --- package-level rollup: the primary answer to "is this layered?" ---
    $lines[] = '';
    $lines[] = '## Package boundaries';
    $lines[] = '';
    if ($packageViolations === []) {
        $lines[] = '**No package-level layering violations.** Every cross-package `use` points downward through `contracts -> expression -> document -> runner -> cli -> laravel`.';
    } else {
        $lines[] = sprintf('**%d package boundary violation(s):**', count($packageViolations));
        $lines[] = '';
        $lines[] = '| Package | ↑ depends on package | Refs | Modules involved |';
        $lines[] = '|---|---|---:|---|';
        usort($packageViolations, fn (array $a, array $b): int => $b[2] <=> $a[2] ?: strcmp($a[0], $b[0]));
        foreach ($packageViolations as [$from, $to, $weight, $moduleRefs]) {
            $moduleCells = implode(', ', array_map(
                fn (string $pair): string => '`'.$pair.'`',
                array_slice($moduleRefs, 0, 6),
            )).(count($moduleRefs) > 6 ? sprintf(' + %d more', count($moduleRefs) - 6) : '');
            $lines[] = sprintf('| `%s` | `%s` | %d | %s |', $from, $to, $weight, $moduleCells);
        }
    }

    $lines[] = '';
    $lines[] = '### All package edges (reference counts)';
    $lines[] = '';
    $lines[] = '| From package | To package | Refs |';
    $lines[] = '|---|---|---:|';
    ksort($packageEdges);
    foreach ($packageEdges as $from => $targets) {
        ksort($targets);
        foreach ($targets as $to => $weight) {
            $lines[] = sprintf('| `%s` | `%s` | %d |', $from, $to, $weight);
        }
    }

    // --- module-level detail, kept for intra-investigation ---
    $lines[] = '';
    $lines[] = '## Module-level detail';
    $lines[] = '';
    if ($violations === []) {
        $lines[] = '**No module-level layering violations.**';
    } else {
        $lines[] = sprintf('**%d module-level violation(s) found:**', count($violations));
        $lines[] = '';
        $lines[] = '| From | ↑ depends on | Weight |';
        $lines[] = '|---|---|---:|';
        usort($violations, fn (array $a, array $b): int => $b[2] <=> $a[2] ?: strcmp(labelOf($a[0]), labelOf($b[0])));
        foreach ($violations as [$from, $to, $weight]) {
            $lines[] = sprintf('| `%s` | `%s` | %d |', labelOf($from), labelOf($to), $weight);
        }
    }

    return implode("\n", $lines)."\n";
}

/**
 * @param  array<string, list<ScannedFile>>  $all
 * @param  array<string, string>  $classPackage
 * @param  array<string, string>  $modulePackage
 * @return array{
 *     0: list<array{string, string, bool}>,
 *     1: list<array{string, string, int}>,
 *     2: array<string, array<string, int>>,
 *     3: list<array{string, string, int, list<string>}>
 * }
 */
function computeEdges(array $all, array $classPackage, array $modulePackage, array $layerOrder): array
{
    $index = [];
    foreach ($all as $key => $files) {
        foreach ($files as $file) {
            $index[$file->namespace.'\\'.$file->className] = $key;
        }
    }

    $weights = [];
    foreach ($all as $key => $files) {
        foreach ($files as $file) {
            foreach ($file->uses as $use) {
                $target = $index[$use] ?? null;
                if ($target === null || $target === $key) {
                    continue;
                }
                $weights[$key][$target] = ($weights[$key][$target] ?? 0) + 1;
            }
        }
    }

    $edges = [];
    $violations = [];
    /** @var array<string, array<string, int>> $packageEdges */
    $packageEdges = [];
    /** @var array<string, array<string, array<string, true>>> $packageModulePairs */
    $packageModulePairs = [];
    foreach ($weights as $from => $targets) {
        ksort($targets);
        $fromPackage = $modulePackage[$from] ?? '';
        foreach ($targets as $to => $weight) {
            $toPackage = $modulePackage[$to] ?? '';

            $violation = packageRank($toPackage, $layerOrder) > packageRank($fromPackage, $layerOrder);
            $edges[] = [$from, $to, $violation];
            if ($violation) {
                $violations[] = [$from, $to, $weight];
            }

            if ($toPackage !== $fromPackage) {
                $packageEdges[$fromPackage][$toPackage] = ($packageEdges[$fromPackage][$toPackage] ?? 0) + $weight;
                $packageModulePairs[$fromPackage][$toPackage][labelOf($from).' -> '.labelOf($to)] = true;
            }
        }
    }
    usort($edges, fn (array $a, array $b): int => strcmp($a[0].$a[1], $b[0].$b[1]));

    $packageViolations = [];
    foreach ($packageEdges as $from => $targets) {
        foreach ($targets as $to => $weight) {
            if (packageRank($to, $layerOrder) > packageRank($from, $layerOrder)) {
                $packageViolations[] = [$from, $to, $weight, array_keys($packageModulePairs[$from][$to] ?? [])];
            }
        }
    }

    return [$edges, $violations, $packageEdges, $packageViolations];
}

/**
 * @param  array<string, list<ScannedFile>>  $all  package-qualified key => files
 */
function classModuleOf(string $fqcn, array $all): ?string
{
    foreach ($all as $key => $files) {
        foreach ($files as $file) {
            if ($file->namespace.'\\'.$file->className === $fqcn) {
                return $key;
            }
        }
    }

    return null;
}

/** Lower rank = lower layer, per the real composer require chain. Unknown packages rank top. */
function packageRank(string $package, array $layerOrder): int
{
    $index = array_search($package, $layerOrder, true);

    return $index !== false ? (int) $index : count($layerOrder) + 1;
}

function labelOf(string $key): string
{
    $pos = strpos($key, ':');
    if ($pos === false) {
        return $key;
    }
    $package = substr($key, 0, $pos);
    $module = substr($key, $pos + 1);

    return $module === '_' ? "({$package} package root)" : $key;
}

function nodeId(string $key): string
{
    return 'M_'.((preg_replace('/[^A-Za-z0-9_]/', '_', $key)) ?? $key);
}
