<?php

declare(strict_types=1);

namespace ArazzoDocs\LayeringDoc;

use ArazzoDocs\NamespaceGraphDoc;
use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Layering Map

The intended architecture as a strict layer order (bottom = depended upon,
top = depends). Edges that point **upward** violate the layering and are drawn
red — any red edge in this diagram is a design regression to fix or an order
to consciously revise in `LAYER_ORDER` below.

Edit `scripts/generate-docs/LayeringDoc.php → LAYER_ORDER` when the intended
architecture changes; the map stays honest because edges are always scanned
live.

MD;

/**
 * Bottom-to-top. A module may only depend on modules strictly below it.
 * Laravel:* and the package roots sit on top implicitly.
 */
const LAYER_ORDER = [
    'Spec',
    'Support',
    'Contracts',
    'Expression',
    'License',
    'Generator',
    'Dependency',
    'Parser',
    'Resolver',
    'Normalizer',
    'Validator',
    'Infrastructure',
    'State',
    'Evaluation',
    'Telemetry',
    'Events',
    'Jobs',
    'Policy',
    'Execution',
    'Protocol',
    'Async',
    'Renderer',
    'Console',
];

/**
 * @param  array<string, list<ScannedFile>>  $core
 * @param  array<string, list<ScannedFile>>  $laravel
 */
function render(array $core, array $laravel): string
{
    $all = NamespaceGraphDoc\merge($core, $laravel);

    $classModule = [];
    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            $classModule[$file->namespace.'\\'.$file->className] = $module;
        }
    }

    [$edges, $violations] = computeEdges($all, $classModule);
    $layers = assignLayers(array_keys($all));

    $lines = [BANNER, '```mermaid', 'flowchart TB'];

    // declare nodes grouped by layer for visual ordering
    ksort($layers);
    foreach ($layers as $layerIndex => $modules) {
        sort($modules);
        $lines[] = sprintf('    subgraph L%d["layer %d"]', $layerIndex, $layerIndex);
        foreach ($modules as $module) {
            $style = str_starts_with($module, 'Laravel:') ? 'laravelNode' : ($module === '_' || $module === 'Laravel:_' ? 'rootNode' : 'node');
            $label = str_starts_with($module, 'Laravel:')
                ? substr($module, strlen('Laravel:'))
                : ($module === '_' ? '(core root)' : ($module === 'Laravel:_' ? '(laravel root)' : $module));
            $lines[] = sprintf('        %s["%s"]:::%s', nodeId($module), $label, $style);
        }
        $lines[] = '    end';
    }

    foreach ($edges as [$from, $to, $isViolation]) {
        $arrow = $isViolation ? '-.->|violation|' : '-->';
        $lines[] = sprintf('    %s %s %s', nodeId($from), $arrow, nodeId($to));
    }

    $lines[] = '    classDef node fill:#e8f0fe,stroke:#4285f4,color:#1a1a1a;';
    $lines[] = '    classDef laravelNode fill:#fef7e0,stroke:#f9ab00,color:#1a1a1a;';
    $lines[] = '    classDef rootNode fill:#f1f3f4,stroke:#9aa0a6,color:#1a1a1a;';
    $lines[] = '```';

    $lines[] = '';
    if ($violations === []) {
        $lines[] = '**No layering violations.** All cross-module dependencies point downward.';
    } else {
        $lines[] = sprintf('**%d violation(s) found:**', count($violations));
        $lines[] = '';
        $lines[] = '| From | ↑ depends on | Weight |';
        $lines[] = '|---|---|---:|';
        usort($violations, fn (array $a, array $b): int => $b[2] <=> $a[2] ?: strcmp(labelOf($a[0]), labelOf($b[0])));
        foreach ($violations as [$from, $to, $weight]) {
            $lines[] = sprintf('| `%s` | `%s` | %d |', labelOf($from), labelOf($to), $weight);
        }
    }

    return implode("\n", $lines)."\n";
}

/**
 * @param  array<string, list<ScannedFile>>  $all
 * @param  array<string, string>  $classModule
 * @return array{0: list<array{string, string, bool}>, 1: list<array{string, string, int}>}
 */
function computeEdges(array $all, array $classModule): array
{
    $weights = [];
    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            foreach ($file->uses as $use) {
                $target = $classModule[$use] ?? null;
                if ($target === null || $target === $module) {
                    continue;
                }
                $weights[$module][$target] = ($weights[$module][$target] ?? 0) + 1;
            }
        }
    }

    $edges = [];
    $violations = [];
    foreach ($weights as $from => $targets) {
        ksort($targets);
        foreach ($targets as $to => $weight) {
            // target ranked HIGHER than source == upward edge == violation
            $violation = layerRank($to) > layerRank($from);
            $edges[] = [$from, $to, $violation];
            if ($violation) {
                $violations[] = [$from, $to, $weight];
            }
        }
    }
    usort($edges, fn (array $a, array $b): int => strcmp($a[0].$a[1], $b[0].$b[1]));

    return [$edges, $violations];
}

/** Lower rank = lower layer. Unknown/unplaced modules rank top. */
function layerRank(string $module): int
{
    $bare = str_starts_with($module, 'Laravel:')
        ? substr($module, strlen('Laravel:'))
        : $module;

    $index = array_search($bare, LAYER_ORDER, true);
    if ($index !== false) {
        return (int) $index;
    }
    if (str_starts_with($module, 'Laravel:')) {
        return count(LAYER_ORDER) + 1;
    }

    return count(LAYER_ORDER) + 2; // package roots on very top
}

/**
 * @param  list<string>  $modules
 * @return array<int, list<string>> rank => modules
 */
function assignLayers(array $modules): array
{
    $layers = [];
    foreach ($modules as $module) {
        $layers[layerRank($module)][] = $module;
    }
    ksort($layers);

    return $layers;
}

function labelOf(string $module): string
{
    return match ($module) {
        '_' => '(core root)',
        'Laravel:_' => '(laravel root)',
        default => $module,
    };
}

function nodeId(string $module): string
{
    return 'M_'.((preg_replace('/[^A-Za-z0-9_]/', '_', $module)) ?? $module);
}
