<?php

declare(strict_types=1);

namespace ArazzoDocs\ModularizationProgressDoc;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Modularization Progress

Tracks the completed split of the monolith into six composer packages
(`contracts <- expression <- document <- runner <- cli <- laravel`):
`packages/core/src` must stay empty (aggregator only — `.gitkeep`) and every
package entry point must expose its `*Interface` + facade pair. Any file in
`packages/core/src` or any missing facade below is a modularization
regression to fix, not drift to accept.

MD;

/**
 * Package entry-point contracts: relative path => [interface, facade].
 * Every pair must exist; the facade hides the package's internal graph.
 *
 * @var array<string, list<string>>
 */
const FACADE_PAIRS = [
    'packages/expression/src' => ['ExpressionEngineInterface.php', 'ExpressionEngine.php'],
    'packages/document/src' => ['DocumentInterface.php', 'Document.php'],
    'packages/runner/src' => ['RunnerFacadeInterface.php', 'RunnerFacade.php'],
];

function render(string $root): string
{
    $stray = [];
    foreach (glob($root.'/packages/core/src/*.php') ?: [] as $file) {
        if (is_file($file)) {
            $stray[] = 'packages/core/src/'.basename((string) $file);
        }
    }
    sort($stray);

    $missing = [];
    $present = 0;
    foreach (FACADE_PAIRS as $dir => $pair) {
        foreach ($pair as $file) {
            if (is_file($root.'/'.$dir.'/'.$file)) {
                $present++;
            } else {
                $missing[] = $dir.'/'.$file;
            }
        }
    }
    sort($missing);

    $total = 0;
    foreach (FACADE_PAIRS as $pair) {
        $total += count($pair);
    }
    $percent = (int) round($present / max(1, $total) * 100);

    $lines = [
        BANNER,
        sprintf('- Core aggregator clean: **%s** (%d stray file(s) in `packages/core/src`)', $stray === [] ? 'yes' : 'no', count($stray)),
        sprintf('- Facade pairs present: **%d / %d** (**%d%%**)', $present, $total, $percent),
        '',
        '```mermaid',
        'xychart-beta',
        sprintf('    title "Facade entry points present (%d%%)"', $percent),
        '    x-axis ["present", "missing"]',
        sprintf('    y-axis "Files" 0 --> %d', max(5, $total)),
        sprintf('    bar [%d, %d]', $present, count($missing)),
        '```',
    ];

    if ($stray !== []) {
        $lines[] = '';
        $lines[] = '## Stray files in packages/core/src';
        $lines[] = '';
        foreach ($stray as $relative) {
            $lines[] = '- `'.$relative.'`';
        }
    }

    if ($missing !== []) {
        $lines[] = '';
        $lines[] = '## Missing facade files';
        $lines[] = '';
        foreach ($missing as $relative) {
            $lines[] = '- `'.$relative.'`';
        }
    }

    return implode("\n", $lines)."\n";
}
