<?php

declare(strict_types=1);

namespace ArazzoDocs\ModularizationProgressDoc;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Modularization Progress

Tracks `docs/superpowers/plans/*-modularization-plan.md` against reality:
every `.php` path the plan promises is checked against the working tree on
each commit. A plan that never meets this doc is a wish, not a roadmap.

MD;

const PLAN_GLOB = '/docs/superpowers/plans/*modularization-plan.md';

function render(string $root): string
{
    $matches = glob($root . PLAN_GLOB) ?: [];
    if ($matches === []) {
        return BANNER . "_No modularization plan found in docs/superpowers/plans/._\n";
    }
    sort($matches);
    $planPath = $matches[0];
    $plan = (string) file_get_contents($planPath);
    $planName = basename((string) $planPath);

    // promised PHP paths anywhere in the plan
    preg_match_all('/`(packages\/[\w\/.-]+\.php)`/', $plan, $paths);
    $promised = array_values(array_unique($paths[1]));

    preg_match_all('/^[-*]\s+\[( |x)\]\s+(.+)$/m', $plan, $boxes, PREG_SET_ORDER);
    $boxesDone = count(array_filter($boxes, fn (array $b): bool => trim($b[1]) === 'x'));

    $created = [];
    $missing = [];
    foreach ($promised as $relative) {
        if (is_file($root . '/' . $relative)) {
            $created[] = $relative;
        } else {
            $missing[] = $relative;
        }
    }

    $total = max(1, count($promised));
    $percent = round(count($created) / $total * 100);

    $lines = [
        BANNER,
        sprintf('Plan: `%s`', $planName),
        '',
        sprintf('- Files promised: **%d** · created: **%d** (**%d%%**)', $total, count($created), $percent),
        sprintf('- Checkboxes ticked: **%d / %d**', $boxesDone, count($boxes)),
        '',
        '```mermaid',
        'xychart-beta',
        sprintf('    title "Planned files created (%d%%)"', $percent),
        '    x-axis ["created", "missing"]',
        sprintf('    y-axis "Files" 0 --> %d', max(5, $total)),
        sprintf('    bar [%d, %d]', count($created), count($missing)),
        '```',
    ];

    if ($missing !== []) {
        $lines[] = '';
        $lines[] = '## Not yet in the tree';
        $lines[] = '';
        foreach ($missing as $relative) {
            $lines[] = '- `' . $relative . '`';
        }
    }

    return implode("\n", $lines) . "\n";
}
