<?php

declare(strict_types=1);

namespace ArazzoDocs\NamespaceGraphDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Namespace Dependency Graph

Cross-module `use` relationships between top-level namespaces, scanned live from
`packages/core/src` and `packages/laravel/src`. Regenerated before every commit.

MD;

/**
 * @param array<string, list<ScannedFile>> $core
 * @param array<string, list<ScannedFile>> $laravel
 *
 * @return array<string, list<ScannedFile>> laravel modules prefixed "Laravel:"
 */
function merge(array $core, array $laravel): array
{
    $merged = [];
    foreach ($core as $module => $files) {
        $merged[$module] = $files;
    }
    foreach ($laravel as $module => $files) {
        $merged["Laravel:{$module}"] = $files;
    }

    return $merged;
}

/**
 * @param array<string, list<ScannedFile>> $core
 * @param array<string, list<ScannedFile>> $laravel
 */
function render(array $core, array $laravel): string
{
    $all = merge($core, $laravel);

    // fqcn => module map
    $classModule = [];
    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            $classModule[$file->namespace . '\\' . $file->className] = $module;
        }
    }

    // module-level edges
    $edges = [];
    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            foreach ($file->uses as $use) {
                $target = $classModule[$use] ?? null;
                if ($target === null || $target === $module) {
                    continue;
                }
                $edges[$module][$target] = true;
            }
        }
    }

    $nodeIds = [];
    foreach ($edges as $from => $targets) {
        $nodeIds[] = $from;
        foreach (array_keys($targets) as $to) {
            $nodeIds[] = $to;
        }
    }
    $nodeIds = array_values(array_unique($nodeIds));
    sort($nodeIds);

    $lines = [BANNER, '```mermaid', 'flowchart LR'];
    foreach ($nodeIds as $id) {
        $label = match ($id) {
            '_' => '(core package root)',
            'Laravel:_' => '(Laravel package root)',
            default => str_starts_with($id, 'Laravel:')
                ? 'Alama\\Arazzo\\Laravel\\' . substr($id, strlen('Laravel:'))
                : 'Alama\\Arazzo\\' . $id,
        };
        $style = str_starts_with($id, 'Laravel:') ? 'laravelNode' : 'coreNode';
        $lines[] = sprintf('    %s["%s"]:::%s', nodeId($id), $label, $style);
    }

    $seen = [];
    foreach ($edges as $from => $targets) {
        foreach (array_keys($targets) as $to) {
            $key = "{$from}->{$to}";
            if (isset($seen[$key])) {
                continue;
            }
            $seen[$key] = true;
            $lines[] = sprintf('    %s --> %s', nodeId($from), nodeId($to));
        }
    }

    $lines[] = '    classDef coreNode fill:#e8f0fe,stroke:#4285f4,color:#1a1a1a;';
    $lines[] = '    classDef laravelNode fill:#fef7e0,stroke:#f9ab00,color:#1a1a1a;';
    $lines[] = '```';

    return implode("\n", $lines) . "\n";
}

function nodeId(string $module): string
{
    return preg_replace('/[^A-Za-z0-9_]/', '_', $module) ?? $module;
}
