<?php

declare(strict_types=1);

namespace ArazzoDocs\NamespaceGraphDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Namespace Dependency Graph

Cross-module `use` relationships between top-level namespaces, scanned live from
the split core packages (`packages/{contracts,expression,document,runner,cli}/src`)
and `packages/laravel/src`. Regenerated before every commit.

MD;

/**
 * Dual-mode merge (Task 8 unifies everything onto $scans and drops legacy):
 * - merge($scans): package slug => (module => files); keys output on
 *   package-qualified keys (`expression:Ast`).
 * - merge($core, $laravel): historic bare-module shape for renderers not yet
 *   migrated; output is byte-identical to the pre-split behavior.
 *
 * @param  array<string, array<string, list<ScannedFile>>>|array<string, list<ScannedFile>>  $a
 * @param  array<string, list<ScannedFile>>  $b
 * @return array<string, list<ScannedFile>>
 */
function merge(array $a, array $b = []): array
{
    if (func_num_args() === 1) {
        $merged = [];
        foreach ($a as $package => $modules) {
            foreach ($modules as $module => $files) {
                $key = \ArazzoDocs\packageKey($package, $module);
                $merged[$key] = array_merge($merged[$key] ?? [], $files);
            }
        }

        return $merged;
    }

    $merged = [];
    foreach ($a as $module => $files) {
        $merged[$module] = $files;
    }
    foreach ($b as $module => $files) {
        $merged["Laravel:{$module}"] = $files;
    }

    return $merged;
}

/**
 * Deterministic display namespace for a module: most common real namespace
 * across its files, tie-broken alphabetically (scanner file order is
 * filesystem-dependent, so first-file picks would be nondeterministic).
 */
function displayNamespace(string $package, string $module, array $files): string
{
    $namespaces = [];
    foreach ($files as $file) {
        $namespaces[$file->namespace] = ($namespaces[$file->namespace] ?? 0) + 1;
    }
    uksort($namespaces, fn (string $a, string $b): int => $namespaces[$b] <=> $namespaces[$a] ?: strcmp($a, $b));

    return \ArazzoDocs\moduleLabel($package, $module, array_key_first($namespaces) ?? '');
}

/**
 * @param  array<string, array<string, list<ScannedFile>>>  $scans  package slug => (module => files)
 */
function render(array $scans): string
{
    $all = merge($scans);

    // fqcn => package-qualified module key
    $classModule = [];
    foreach ($all as $key => $files) {
        foreach ($files as $file) {
            $classModule[$file->namespace.'\\'.$file->className] = $key;
        }
    }

    // module-level edges
    $edges = [];
    foreach ($all as $key => $files) {
        foreach ($files as $file) {
            foreach ($file->uses as $use) {
                $target = $classModule[$use] ?? null;
                if ($target === null || $target === $key) {
                    continue;
                }
                $edges[$key][$target] = true;
            }
        }
    }

    $nodeIds = [];
    foreach ($edges as $from => $targets) {
        $nodeIds[] = $from;
        foreach (array_keys($targets) as $to) {
            $nodeIds[] = $to;
        }
    }
    $nodeIds = array_values(array_unique($nodeIds));
    sort($nodeIds);

    // package-qualified key => [package, module] for labels
    $split = [];
    foreach ($nodeIds as $id) {
        $pos = strpos($id, ':');
        $split[$id] = $pos === false ? ['', $id] : [substr($id, 0, $pos), substr($id, $pos + 1)];
    }

    $lines = [BANNER, '```mermaid', 'flowchart LR'];
    foreach ($nodeIds as $id) {
        [$package, $module] = $split[$id];
        $label = match (true) {
            $module === '_' => "({$package} package root)",
            default => displayNamespace($package, $module, $all[$id]),
        };
        $style = $package === 'laravel' ? 'laravelNode' : 'coreNode';
        $lines[] = sprintf('    %s["%s"]:::%s', nodeId($id), $label, $style);
    }

    $seen = [];
    foreach ($edges as $from => $targets) {
        foreach (array_keys($targets) as $to) {
            $key = "{$from}->{$to}";
            if (isset($seen[$key])) {
                continue;
            }
            $seen[$key] = true;
            $lines[] = sprintf('    %s --> %s', nodeId($from), nodeId($to));
        }
    }

    $lines[] = '    classDef coreNode fill:#e8f0fe,stroke:#4285f4,color:#1a1a1a;';
    $lines[] = '    classDef laravelNode fill:#fef7e0,stroke:#f9ab00,color:#1a1a1a;';
    $lines[] = '```';

    return implode("\n", $lines)."\n";
}

function nodeId(string $module): string
{
    return preg_replace('/[^A-Za-z0-9_]/', '_', $module) ?? $module;
}
