<?php

declare(strict_types=1);

namespace ArazzoDocs\ObservabilityDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Observability Map

What an operator can actually see at runtime, scanned live:

1. **Event → ledger catalog** — the mapping `LedgerAppendingListener` writes
   to persistent storage (the audit trail).
2. **Log call sites** — every logger touch in src, by level.
3. **Persistence adapters** — the contracts that carry runtime state and
   their implementations per package.
4. **Correlation touchpoints** — where async suspend/resume state lives.

See also: `events.md` (dispatch graph), `failure-modes.md` (interlocks).

MD;

const LOG_LEVELS = ['error', 'warning', 'notice', 'info', 'debug', 'critical', 'alert', 'emergency'];

/**
 * @param  array<string, array<string, list<ScannedFile>>>  $scans  package slug => (module => files)
 */
function render(array $scans): string
{
    $files = [];
    foreach (\ArazzoDocs\flattenScans($scans) as $file) {
        $files[$file->namespace.'\\'.$file->className] = $file;
    }
    ksort($files);

    [$catalog, $catalogSource] = extractLedgerCatalog($files);
    [$logSites, $logTotal] = scanLogs($files);
    $adapters = scanAdapters($files);
    $correlation = scanCorrelations($files);

    $lines = [BANNER];

    // --- event -> ledger catalog ---
    $lines[] = '## Event → ledger catalog';
    $lines[] = '';
    if ($catalog === []) {
        $lines[] = sprintf("_No catalog found (%s)._\n", $catalogSource);
    } else {
        $lines[] = 'Written by `'.$catalogSource.'` — this is the durable audit trail schema:';
        $lines[] = '';
        $lines[] = '| Domain event | Ledger type | Payload keys |';
        $lines[] = '|---|---|---|';
        ksort($catalog);
        foreach ($catalog as $event => [$type, $payloadKeys]) {
            sort($payloadKeys);
            $keys = $payloadKeys === [] ? '—' : implode(', ', array_map(fn (string $k): string => '`'.$k.'`', $payloadKeys));
            $lines[] = '| `'.$event.'` | `'.$type.'` | '.$keys.' |';
        }
        $lines[] = '';
    }

    // --- log call sites ---
    $lines[] = '## Log call sites';
    $lines[] = '';
    $lines[] = '| Class | Level(s) | Calls |';
    $lines[] = '|---|---|---:|';
    if ($logSites === []) {
        $lines[] = '| — | — | — |';
    } else {
        ksort($logSites);
        foreach ($logSites as $class => $levels) {
            asort($levels);
            $cells = [];
            $count = 0;
            foreach ($levels as $level => $hits) {
                $cells[] = '`'.$level.'`';
                $count += $hits;
            }
            $lines[] = '| `'.short($class).'` <small>'.packageOf($class).'</small> | '.implode(' · ', $cells).' | '.$count.' |';
        }
        $lines[] = '';
        $lines[] = sprintf('%d logging calls total. PSR-14 events are dispatched independently (see events.md).', $logTotal);
    }
    $lines[] = '';

    // --- persistence adapters ---
    $lines[] = '## Persistence adapters';
    $lines[] = '';
    $lines[] = 'Runtime state survives process boundaries through these contracts:';
    $lines[] = '';
    $lines[] = '| Contract | Implementations |';
    $lines[] = '|---|---|';
    ksort($adapters);
    foreach ($adapters as $contract => $implementations) {
        $cells = [];
        foreach ($implementations as $impl) {
            $cells[] = '`'.short($impl).'` <small>'.packageOf($impl).'</small>';
        }
        $lines[] = '| `'.$contract.'` | '.implode(', ', $cells).' |';
    }
    $lines[] = '';

    // --- correlations ---
    $lines[] = '## Correlation touchpoints';
    $lines[] = '';
    $lines[] = 'Where async suspend/resume bookkeeping happens:';
    $lines[] = '';
    $lines[] = '| Class | Role signals |';
    $lines[] = '|---|---|';
    if ($correlation === []) {
        $lines[] = '| — | — |';
    } else {
        ksort($correlation);
        foreach ($correlation as $class => $roles) {
            sort($roles);
            $lines[] = '| `'.short($class).'` <small>'.packageOf((string) $class).'</small> | '.implode(', ', $roles).' |';
        }
    }

    return implode("\n", $lines)."\n";
}

/**
 * Extracts instanceof → [ledgerType, payloadKeys] arms from the listener's
 * match(true) block.
 *
 * @param  array<string, ScannedFile>  $files
 * @return array{0: array<string, array{string, list<string>}>, 1: string}
 */
function extractLedgerCatalog(array $files): array
{
    $listener = null;
    foreach ($files as $file) {
        if ($file->className === 'LedgerAppendingListener') {
            $listener = $file;

            break;
        }
    }
    if ($listener === null) {
        return [[], 'LedgerAppendingListener not found'];
    }

    $content = $listener->content;
    preg_match_all(
        '/\$event\s+instanceof\s+(\w+)\s*=>\s*\[(.*?)(?=\$event\s+instanceof|\bdefault\s*=>)/s',
        $content,
        $arms,
        PREG_SET_ORDER,
    );

    $catalog = [];
    foreach ($arms as $arm) {
        $eventClass = $arm[1];
        $body = $arm[2];
        if (!preg_match('/[\'"]([\w.]+)[\'"]/', $body, $typeMatch)) {
            continue;
        }
        preg_match_all('/[\'"](\w+)[\'"]\s*=>/', $body, $keyMatches);
        $payloadKeys = array_values(array_unique(array_diff($keyMatches[1], [$typeMatch[1]])));
        $catalog[$eventClass] = [$typeMatch[1], $payloadKeys];
    }

    ksort($catalog);

    return [$catalog, $listener->namespace.'\\'.$listener->className];
}

/**
 * @param  array<string, ScannedFile>  $files
 * @return array{0: array<string, array<string, int>>, 1: int}
 */
function scanLogs(array $files): array
{
    $sites = [];
    $total = 0;
    foreach ($files as $fqcn => $file) {
        foreach (LOG_LEVELS as $level) {
            $hits = preg_match_all('/->'.$level.'\s*\(/', $file->content);
            if ($hits > 0) {
                $sites[$fqcn][$level] = $hits;
                $total += $hits;
            }
        }
        // Laravel facade + generic ->log(
        $facadeHits = preg_match_all('/(?:Log::(?:'.implode('|', LOG_LEVELS).')\s*\(|->log\s*\()/', $file->content);
        if ($facadeHits > 0) {
            $sites[$fqcn]['generic'] = ($sites[$fqcn]['generic'] ?? 0) + $facadeHits;
            $total += $facadeHits;
        }
    }

    return [$sites, $total];
}

/**
 * Contracts carrying runtime state + who implements them.
 *
 * @param  array<string, ScannedFile>  $files
 * @return array<string, list<string>>
 */
function scanAdapters(array $files): array
{
    $contracts = [];
    foreach ($files as $fqcn => $file) {
        if (!$file->isInterface) {
            continue;
        }
        if (preg_match('/(StateStore|EventLedger|ExecutionRegistry|LockManager|DefinitionRegistry|PendingCorrelationRegistry|QueueDriver)/', $file->className) !== 1) {
            continue;
        }
        $contracts[$file->className] = [];
    }

    foreach ($files as $fqcn => $file) {
        if ($file->isInterface) {
            continue;
        }
        if (preg_match('/implements\s+([^;{]+)/', $file->content, $m) !== 1) {
            continue;
        }
        foreach (explode(',', str_replace('|', ',', $m[1])) as $raw) {
            $name = basename(str_replace('\\', '/', trim($raw)));
            if (isset($contracts[$name])) {
                $contracts[$name][] = $fqcn;
            }
        }
    }

    foreach ($contracts as &$implementations) {
        sort($implementations);
    }
    unset($implementations);

    return $contracts;
}

/**
 * @param  array<string, ScannedFile>  $files
 * @return array<string, list<string>>
 */
function scanCorrelations(array $files): array
{
    $signals = [
        'creates pending correlation' => '/new\s+PendingCorrelation\b|createPending/',
        'consumes correlation' => '/consume[A-Z(]/',
        'resumes from webhook' => '/resume/i',
        'reads pending state' => '/findPending|existsForExecution/',
    ];

    $found = [];
    foreach ($files as $fqcn => $file) {
        $roles = [];
        foreach ($signals as $role => $pattern) {
            if (preg_match($pattern, $file->content) === 1 && stripos($file->content, 'correlation') !== false) {
                $roles[] = $role;
            }
        }
        if ($roles !== []) {
            $found[$fqcn] = $roles;
        }
    }

    ksort($found);

    return $found;
}

function short(string $fqcn): string
{
    $parts = explode('\\', $fqcn);

    return end($parts);
}

function packageOf(string $fqcn): string
{
    return str_contains($fqcn, 'Laravel') ? 'laravel' : 'core';
}
