<?php

declare(strict_types=1);

namespace ArazzoDocs\PackageContractsDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Package Capability Contracts

One public face per package: what the package promises, the entry surface
downstream packages may depend on, the value types that legitimately cross the
seam, and what is deliberately internal. Capabilities, faces and the
internal-intent lists are the **declared target** of the boundary-hardening
effort; the `@internal` markers reflect the current docblock state, so every
`no` row is a scheduled item for the `@internal` sweep. `contracts` is the
deliberate exception to "one face": its SPI interfaces are the shared,
public contract between packages.

MD;

/**
 * Declared per-package public contract (the defined target).
 *
 * - `faces`: entry interfaces/classes downstream packages may depend on.
 *   Names are matched by short class name inside the owning package.
 * - `value_types`: data that is allowed to cross the seam as values (DTOs,
 *   state carriers, throwables).
 * - `internal`: types that must carry an `@internal` docblock once the sweep
 *   lands. Entries ending in `\*` denote a whole namespace group.
 *
 * @var array<string, array{provides: string, capabilities: list<string>, faces: list<string>, value_types: list<string>, internal: list<string>}>
 */
const PACKAGE_CONTRACTS = [
    'contracts' => [
        'provides' => 'The shared cross-package contract layer: SPI ports downstream packages implement, the workflow-context contract, and the parsed document model (`Spec`) with state carriers nobody may redefine.',
        'capabilities' => [
            'SPI ports implemented by framework adapters (AI client, queue driver, lock manager/strategy, backoff, protocol executor, output extractor, response validator)',
            'Workflow-context contract shared across execution',
            'Own the parsed document model (`Spec`) and shared state/value types',
            'Support services: event dispatch, input-schema resolution, dependency analysis',
        ],
        'faces' => ['AiClientInterface', 'StepProtocolExecutorInterface', 'QueueDriverInterface', 'LockManagerInterface', 'LockStrategyInterface', 'BackoffCalculatorInterface', 'OutputExtractorInterface', 'ResponseValidatorInterface', 'WorkflowContextInterface'],
        'value_types' => ['ArazzoDocument', 'Step', 'Workflow', 'Expression', 'RawDocument', 'SourceDescription', 'SuccessCriterion', 'Selector', 'PayloadReplacement', 'WorkflowContext', 'ExecutionState'],
        'internal' => ['InputSchemaResolver', 'NullEventDispatcher', 'SimpleEventDispatcher', 'DependencyAnalyzer', 'ImplicitDependencies', 'DependencyGraph'],
    ],
    'expression' => [
        'provides' => 'Parses and evaluates Arazzo expressions, selectors and payload substitutions against the workflow context.',
        'capabilities' => [
            'Parse expression strings with typed syntax errors surfaced through the face',
            'Expose expression reference projections (kind + target fields) without leaking the AST',
            'Evaluate expressions against an evaluation context',
            'Evaluate success-criteria / condition expressions',
            'Evaluate selectors (JSONPath, JSON-pointer, XPath)',
            'String interpolation and payload replacement for request/response bodies',
            'Build symbol tables over the parsed document (value data for downstream consumers)',
        ],
        'faces' => ['ExpressionEngineInterface'],
        'value_types' => ['SymbolTable', 'WorkflowSymbols', 'StepSymbols', 'EvaluationInputInterface', 'EvaluationInput', 'ExpressionSyntaxException', 'SelectorEvaluationException', 'ExpressionReference', 'ReferenceKind'],
        'internal' => ['ExpressionEvaluatorInterface', 'ExpressionResolverInterface', 'ExpressionEvaluator', 'SelectorEvaluator', 'StringInterpolator', 'JsonPathEvaluator', 'JsonPointer', 'DomXpathEvaluator', 'XpathEvaluator', 'Lexer', 'Parser', 'Token', 'Ast\\*', 'Evaluation\\*'],
    ],
    'document' => [
        'provides' => 'Loads, parses, validates and preflights Arazzo documents, and resolves the OpenAPI operations they reference.',
        'capabilities' => [
            'Load and parse Arazzo documents from YAML/JSON (or already-decoded raw documents)',
            'Static conformance validation via rule sets',
            'Preflight validation incl. source-audited steps and runtime-input schema checks',
            'Source-document resolution and fetching (URL, local, cached) exposed through the face',
            'OpenAPI operation resolution plus normalization and version detection through the face',
        ],
        'faces' => ['DocumentInterface'],
        'value_types' => ['ValidationResult', 'Error', 'Warning', 'ResolvedOperation', 'NormalizedOpenApiOperation', 'LoaderException', 'ParserException', 'PreflightFailureException'],
        'internal' => ['SourceResolver', 'SourceFetcher', 'SourceRegistry', 'DefaultSourceResolver', 'HttpFetcher', 'LocalFetcher', 'CachedFetcher', 'OpenApiNormalizerInterface', 'OpenApi30Normalizer', 'OpenApi31Normalizer', 'Swagger2Normalizer', 'OpenApiVersionDetector', 'OpenApiDocumentLoader', 'OpenApiOperationResolver', 'YamlDecoder', 'JsonDecoder', 'SymfonyYamlDecoder', 'NativeJsonDecoder', 'Loader', 'Parser', 'ParseContext', 'RuleSet', 'Validator', 'PreflightValidator', 'ErrorCollector', 'OfficialSchemaRule', 'Rules\\*', 'Validator\\Support\\*'],
    ],
    'runner' => [
        'provides' => 'Executes Arazzo workflows: step dispatch, state transitions, async/queued execution, protocol executors and persistence registries.',
        'capabilities' => [
            'Execute a workflow from its document (runner facade): compact summary and per-step verdicts',
            'Source resolution/fetching, preflight validation and OpenAPI operation resolution obtained through the document face',
            'Step dispatch: HTTP, async and sub-workflow protocol executors',
            'State transitions, budgeting, retries and correlation resume',
            'Async/queued step execution with suspension and reconciliation',
            'Persistence registries and state stores (injectable implementations)',
            'Event ledger and telemetry hooks',
        ],
        'faces' => ['RunnerFacadeInterface'],
        'value_types' => [],
        'internal' => ['StateStoreInterface', 'DefinitionRegistryInterface', 'WritableDefinitionRegistryInterface', 'ExecutionRegistryInterface', 'PendingCorrelationRegistryInterface', 'InMemoryStateStore', 'FileStateStore', 'EventLedgerInterface', 'HttpClientInterface', 'ProtocolExecutorRegistryInterface', 'OpenApiExecutorInterface', 'PessimisticLockStrategy', 'NullLockStrategy', 'FileLockStrategy', 'RetryPolicy', 'ExponentialBackoffCalculator', 'Execution\\*', 'Async\\*', 'Jobs\\*', 'Telemetry\\*', 'Events\\*', 'Policy\\*', 'State\\Data\\*', 'Protocol\\*'],
    ],
    'cli' => [
        'provides' => 'The terminal edge: runs, validates, explains and renders Arazzo workflows, and can generate new workflows.',
        'capabilities' => [
            'Run a workflow (arazzo run)',
            'Validate a document (arazzo validate)',
            'List workflows (arazzo list)',
            'Explain a document (arazzo explain)',
            'Render output templates (arazzo render) and generate workflows via OpenAI',
        ],
        'faces' => ['Application', 'RunCommand', 'ValidateCommand', 'ListWorkflowsCommand', 'ExplainCommand', 'RenderCommand'],
        'value_types' => [],
        'internal' => ['ArazzoGenerator', 'OpenAiClient', 'Renderer', 'DocumentLoader', 'CliRunner', 'CliRunResult', 'NullEventLedger', 'InProcessExecutionRegistry'],
    ],
    'laravel' => [
        'provides' => 'The Laravel integration edge: wires every port to framework adapters and exposes the workflow engine to the container.',
        'capabilities' => [
            'Service-container wiring for every contracts SPI port (queue, lock, AI client, HTTP, registries, state)',
            'HTTP controllers for API + webhook resume',
            'Persistence adapters (database registries, Redis state/locks)',
            'Queued async execution jobs',
            'Framework event dispatch',
        ],
        'faces' => ['LaravelArazzoServiceProvider'],
        'value_types' => ['ConfigValue'],
        'internal' => ['FacadeBindings', 'GeneratorBindings', 'ResolverBindings', 'PersistenceBindings', 'EventBindings', 'HttpBindings', 'ExecutionBindings', 'DatabaseDefinitionRegistry', 'DatabaseExecutionRegistry', 'DatabaseEventLedger', 'DatabasePendingCorrelationRegistry', 'IlluminatePsrEventDispatcher', 'Psr18HttpClient', 'LaravelQueueDriver', 'LaravelRedisLockManager', 'RedisHotStateStore', 'RunExecuteStepJob', 'RunResumeCorrelationJob', 'WebhookResumeController', 'ArazzoApiController'],
    ],
];

/**
 * @param  array<string, array<string, list<ScannedFile>>>  $scans  package slug => (module => files)
 */
function render(array $scans): string
{
    $lines = [BANNER];

    foreach (\ArazzoDocs\PACKAGE_LAYER_ORDER as $package) {
        $contract = PACKAGE_CONTRACTS[$package] ?? null;
        if ($contract === null) {
            continue;
        }
        $modules = $scans[$package] ?? [];

        $lines[] = '## '.$package;
        $lines[] = '';
        $lines[] = '> **Provides:** '.$contract['provides'];
        $lines[] = '';
        $lines[] = '### Capabilities';
        $lines[] = '';
        foreach ($contract['capabilities'] as $capability) {
            $lines[] = '- '.$capability;
        }
        $lines[] = '';
        $lines[] = '### Public entry surface';
        $lines[] = '';
        foreach ($contract['faces'] as $face) {
            $lines = [...$lines, ...renderFace($modules, $face)];
        }
        $lines[] = '';
        $lines[] = '### Cross-boundary value types';
        $lines[] = '';
        if ($contract['value_types'] === []) {
            $lines[] = '_None — the entry surface exchanges plain arrays._';
        } else {
            foreach ($contract['value_types'] as $valueType) {
                $file = findInPackage($modules, $valueType);
                $status = $file === null ? ' not found' : ' present';
                $lines[] = '- `'.$valueType.'` —'.$status;
            }
        }
        $lines[] = '';
        $lines[] = '### Deliberately internal';
        $lines[] = '';
        foreach ($contract['internal'] as $internal) {
            $lines[] = renderInternal($modules, $internal);
        }
        $lines[] = '';
    }

    return implode("\n", $lines)."\n";
}

/**
 * @param  array<string, list<ScannedFile>>  $modules
 * @return list<string>
 */
function renderFace(array $modules, string $face): array
{
    $file = findInPackage($modules, $face);
    if ($file === null) {
        return ['- `'.$face.'` — _not found in scan_'];
    }
    $kind = $file->isInterface ? 'interface' : 'class';
    $internalMark = \ArazzoDocs\hasInternalDocblock($file->content) ? ' ⚠ marked `@internal` — contradicts its face role' : '';
    $lines = ['- `'.$face.'` (`'.$kind.'`)'.$internalMark];
    foreach (\ArazzoDocs\PublicApiDoc\publicSignatures($file->content) as $signature) {
        $lines[] = '  - `'.$signature.'`';
    }

    return $lines;
}

/**
 * @param  array<string, list<ScannedFile>>  $modules
 */
function renderInternal(array $modules, string $internal): string
{
    if (str_ends_with($internal, '\\*')) {
        return '- `'.$internal.'` — whole namespace (declared target)';
    }
    $file = findInPackage($modules, $internal);
    if ($file === null) {
        return '- `'.$internal.'` — _not found in scan_';
    }
    $marked = \ArazzoDocs\hasInternalDocblock($file->content) ? 'yes' : 'no (target for the sweep)';

    return '- `'.$internal.'` — `@internal`: '.$marked;
}

/**
 * First scanned file whose class short-name matches inside a package.
 *
 * @param  array<string, list<ScannedFile>>  $modules
 */
function findInPackage(array $modules, string $short): ?ScannedFile
{
    foreach ($modules as $files) {
        foreach ($files as $file) {
            if ($file->className === $short) {
                return $file;
            }
        }
    }

    return null;
}
