<?php

declare(strict_types=1);

namespace ArazzoDocs\PipelineFlowDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Pipeline Flow

Execution topology of the Runner: every concrete service under `Runner/` (plus
Laravel queue jobs) with the edges introduced by constructor injection or direct
instantiation. Entry points (nothing injects them) are green. Isolated value
objects, enums and exceptions are omitted. Regenerated before every commit.

MD;

/**
 * @param  array<string, array<string, list<ScannedFile>>>  $scans  package slug => (module => files)
 */
function render(array $scans): string
{
    [$all, $packageOf] = collectNodes($scans);

    if ($all === []) {
        return BANNER."_No runner classes found._\n";
    }

    $shortIndex = shortNameIndex($all);
    $edges = [];
    foreach ($all as $fqcn => $file) {
        foreach (dependenciesOf($file, $all, $shortIndex) as $dep) {
            if ($dep === $fqcn) {
                continue;
            }
            $edges[$fqcn][$dep] = true;
        }
    }

    // keep only nodes that participate in at least one edge
    $inDegree = array_fill_keys(array_keys($all), 0);
    foreach ($edges as $targets) {
        foreach (array_keys($targets) as $target) {
            $inDegree[$target] = ($inDegree[$target] ?? 0) + 1;
        }
    }
    $kept = [];
    foreach (array_keys($all) as $fqcn) {
        $out = count($edges[$fqcn] ?? []);
        if ($out > 0 || $inDegree[$fqcn] > 0) {
            $kept[$fqcn] = true;
        }
    }

    $dispatches = dispatchIndex($scans, $kept, $shortIndex);

    $lines = [BANNER, '```mermaid', 'flowchart TD'];

    $groups = groupByDir($all, $kept);
    foreach ($groups as $dir => $fqcms) {
        $gid = 'G_'.nodeId($dir === '' ? '_root' : $dir);
        $lines[] = sprintf('    subgraph %s["%s"]', $gid, $dir === '' ? '(package root)' : $dir);
        foreach ($fqcms as $fqcn) {
            $style = match (true) {
                $inDegree[$fqcn] === 0 => 'entry',
                $packageOf[$fqcn] === 'laravel' => 'laravelNode',
                default => 'service',
            };
            $lines[] = sprintf('        %s["%s"]:::%s', nodeId($fqcn), short($fqcn), $style);
        }
        $lines[] = '    end';
    }

    $pairs = [];
    foreach ($edges as $from => $targets) {
        foreach (array_keys($targets) as $to) {
            if (isset($kept[$from], $kept[$to])) {
                $pairs[] = [$from, $to];
            }
        }
    }
    sort($pairs);
    foreach ($pairs as [$from, $to]) {
        $lines[] = sprintf('    %s --> %s', nodeId($from), nodeId($to));
    }

    $lines[] = '    classDef entry fill:#e6f4ea,stroke:#34a853,color:#1a1a1a;';
    $lines[] = '    classDef service fill:#e8f0fe,stroke:#4285f4,color:#1a1a1a;';
    $lines[] = '    classDef laravelNode fill:#fef7e0,stroke:#f9ab00,color:#1a1a1a;';
    $lines[] = '```';
    $lines[] = '';
    $lines[] = '| Service | Package | Depends on | Used by | Dispatches |';
    $lines[] = '|---|---|---|---|---|';

    $fqcms = array_keys($all);
    sort($fqcms);
    foreach ($fqcms as $fqcn) {
        if (!isset($kept[$fqcn])) {
            continue;
        }
        $deps = array_keys($edges[$fqcn] ?? []);
        sort($deps);
        $users = [];
        foreach ($edges as $from => $targets) {
            if (isset($targets[$fqcn])) {
                $users[] = $from;
            }
        }
        sort($users);
        $fired = $dispatches[$fqcn] ?? [];
        sort($fired);
        $lines[] = sprintf(
            '| **%s** | %s | %s | %s | %s |',
            short($fqcn),
            $packageOf[$fqcn],
            cells(array_map(short(...), $deps)),
            cells(array_map(short(...), $users)),
            cells(array_map(short(...), $fired)),
        );
    }

    return implode("\n", $lines)."\n";
}

/**
 * @param  array<string, array<string, list<ScannedFile>>>  $scans
 * @return array{0: array<string, ScannedFile>, 1: array<string, string>}
 */
function collectNodes(array $scans): array
{
    $nodes = [];
    $packages = [];
    foreach (\ArazzoDocs\flattenScans($scans) as $file) {
        if (!isPipelineClass($file)) {
            continue;
        }
        $fqcn = $file->namespace.'\\'.$file->className;
        $nodes[$fqcn] = $file;
        $packages[$fqcn] = $file->package;
    }

    return [$nodes, $packages];
}

function isPipelineClass(ScannedFile $file): bool
{
    if ($file->isInterface) {
        return false;
    }
    if (preg_match('/^(?:(?:abstract|final|readonly)\s+)*class\s/m', $file->content) !== 1) {
        return false;
    }
    // thrown/constructed exceptions are noise, not pipeline participants
    if (preg_match('/\bextends\s+\\\\?(?:\w+\\\\)*(\w*Exception|Throwable)\b/', $file->content) === 1) {
        return false;
    }

    $ns = $file->namespace;
    $dir = $file->relativeDir;

    if (str_starts_with($ns, 'Alama\\Arazzo\\Runner\\')) {
        return !str_contains($ns, '\\Exceptions') && !str_ends_with($dir, '/Events');
    }
    if (str_starts_with($ns, 'Alama\\Arazzo\\Laravel\\')) {
        return str_starts_with($dir, 'Queue/Jobs');
    }

    return false;
}

/**
 * @param  array<string, ScannedFile>  $all
 * @return array<string, string> unique short name => fqcn
 */
function shortNameIndex(array $all): array
{
    $index = [];
    foreach (array_keys($all) as $fqcn) {
        $name = short($fqcn);
        if (isset($index[$name])) {
            $index[$name] = ''; // ambiguous, unusable
        } else {
            $index[$name] = $fqcn;
        }
    }

    return $index;
}

/**
 * Dependency FQCNs of a file via promoted properties, `new X(` and typed
 * private/protected properties assigned in the constructor.
 *
 * @param  array<string, ScannedFile>  $all
 * @param  array<string, string>  $shortIndex
 * @return list<string>
 */
function dependenciesOf(ScannedFile $file, array $all, array $shortIndex): array
{
    $aliases = aliasMap($file);
    $deps = [];

    $resolve = function (string $token) use ($file, $all, $shortIndex, $aliases, &$deps): void {
        $token = ltrim(trim($token), '?');
        if ($token === '' || $token === 'self' || $token === 'static' || $token === 'parent') {
            return;
        }
        foreach (explode('|', $token) as $part) {
            $part = ltrim(trim($part), '?');
            if ($part === '' || !preg_match('/^[A-Za-z_][\w\\\\]*$/', $part)) {
                continue;
            }
            $candidate = null;
            if (str_starts_with($part, 'Alama\\Arazzo\\')) {
                $candidate = $part;
            } elseif (isset($aliases[$part])) {
                $candidate = $aliases[$part];
            } elseif (isset($all[$file->namespace.'\\'.$part])) {
                $candidate = $file->namespace.'\\'.$part;
            } else {
                $unique = $shortIndex[$part] ?? '';
                if ($unique !== '') {
                    $candidate = $unique;
                }
            }
            if ($candidate !== null && isset($all[$candidate])) {
                $deps[$candidate] = true;
            }
        }
    };

    if (preg_match_all('/(?:private|protected|public)(?:\s+readonly)?\s+([\w|?]+)\s+\$\w+/', $file->content, $props)) {
        foreach ($props[1] as $type) {
            $resolve($type);
        }
    }

    if (preg_match_all('/new\s+(\w+)\s*\(/', $file->content, $news)) {
        foreach ($news[1] as $class) {
            $resolve($class);
        }
    }

    $list = array_keys($deps);
    sort($list);

    return $list;
}

/** @return array<string, string> alias => fqcn (Alama\Arazzo\ only) */
function aliasMap(ScannedFile $file): array
{
    $map = [];
    foreach ($file->useStatements as $statement) {
        if (preg_match('/^([\w\\\\]+)\s+as\s+(\w+)$/', $statement, $m)
            && str_starts_with($m[1], 'Alama\\Arazzo\\')
        ) {
            $map[$m[2]] = $m[1];
        }
    }

    return $map;
}

/**
 * fqcn of pipeline node => event short names it constructs.
 *
 * @param  array<string, ScannedFile>  $pipelineNodes
 * @param  array<string, string>  $shortIndex
 * @return array<string, list<string>>
 */
function dispatchIndex(array $scans, array $pipelineNodes, array $shortIndex): array
{
    $flat = \ArazzoDocs\flattenScans($scans);

    $events = [];
    foreach ($flat as $file) {
        $dir = $file->relativeDir;
        $isEventsDir = $dir === 'Events' || str_ends_with($dir, '/Events');
        if (!$isEventsDir || $file->isInterface) {
            continue;
        }
        if (str_contains($file->className, 'Dispatcher')) {
            continue;
        }
        $events[$file->className] = $file->namespace.'\\'.$file->className;
    }

    $byFqcn = [];
    foreach ($flat as $file) {
        $byFqcn[$file->namespace.'\\'.$file->className] = $file;
    }

    $index = [];
    foreach ($pipelineNodes as $fqcn => $_) {
        $file = $byFqcn[$fqcn] ?? null;
        if ($file === null || !str_contains($file->content, 'dispatch(')) {
            continue;
        }
        $aliases = aliasMap($file);
        preg_match_all('/new\s+(\w+)\s*\(/', $file->content, $news);
        foreach (array_unique($news[1]) as $constructed) {
            $eventFqcn = $events[$constructed]
                ?? (isset($aliases[$constructed]) ? ($events[short($aliases[$constructed])] ?? null) : null);
            if ($eventFqcn !== null) {
                $index[$fqcn][] = short($eventFqcn);
            }
        }
    }

    ksort($index);

    return $index;
}

/**
 * @param  array<string, ScannedFile>  $all
 * @param  array<string, bool>  $kept
 * @return array<string, list<string>> dir => sorted fqcms
 */
function groupByDir(array $all, array $kept): array
{
    $groups = [];
    foreach ($all as $fqcn => $file) {
        if (!isset($kept[$fqcn])) {
            continue;
        }
        $groups[$file->relativeDir][] = $fqcn;
    }
    ksort($groups);
    foreach ($groups as $dir => $fqcms) {
        sort($fqcms);
        $groups[$dir] = $fqcms;
    }

    return $groups;
}

function short(string $fqcn): string
{
    $parts = explode('\\', $fqcn);

    return end($parts);
}

function cells(array $names): string
{
    if ($names === []) {
        return '—';
    }

    return implode(', ', array_map(fn (string $n): string => '`'.$n.'`', $names));
}

function nodeId(string $value): string
{
    return preg_replace('/[^A-Za-z0-9_]/', '_', $value) ?? $value;
}
