<?php

declare(strict_types=1);

namespace ArazzoDocs\PublicApiDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Public API Surface

Every public method signature, constructor promotion and constant of
classes/interfaces/enums in `packages/*/src`, excluding `Support`, `Internal`
and `Exceptions` namespaces (exceptions have their own doc). Any diff in this
file on a commit is a public API change — review it deliberately.

MD;

/**
 * @param array<string, list<ScannedFile>> $core
 * @param array<string, list<ScannedFile>> $laravel
 */
function render(array $core, array $laravel): string
{
    $lines = [BANNER];

    foreach ([['core', 'Alama\\Arazzo\\', $core], ['laravel', 'Alama\\Arazzo\\Laravel\\', $laravel]] as [$pkg, $prefix, $modules]) {
        ksort($modules);
        foreach ($modules as $module => $files) {
            $entries = collectEntries($files);
            if ($entries === []) {
                continue;
            }
            $lines[] = sprintf('## %s · `%s`', $pkg, $module === '_' ? trim($prefix, '\\') : $prefix . $module);
            $lines[] = '';
            foreach ($entries as $entry) {
                $lines = [...$lines, ...renderEntry($entry)];
            }
        }
    }

    return implode("\n", $lines) . "\n";
}

/**
 * @param list<ScannedFile> $files
 *
 * @return list<array{kind: string, name: string, signature: list<string>, constants: list<string>, cases: list<string>}>
 */
function collectEntries(array $files): array
{
    $byName = [];
    foreach ($files as $file) {
        if (isInternal($file)) {
            continue;
        }
        $name = $file->className;
        if (isset($byName[$name])) {
            // duplicate short name across namespaces: keep both, suffix deterministically
            $suffix = 2;
            while (isset($byName["{$name}~{$suffix}"])) {
                $suffix++;
            }
            $name = "{$name}~{$suffix}";
        }

        $kind = match (true) {
            $file->isInterface => 'interface',
            preg_match('/^enum\s+/m', $file->content) === 1 => 'enum',
            preg_match('/^trait\s+/m', $file->content) === 1 => 'trait',
            preg_match('/^abstract\s+class\s+/m', $file->content) === 1 => 'abstract class',
            default => 'class',
        };

        $methods = publicSignatures($file->content);
        sort($methods);

        $constants = publicConstants($file->content);
        $cases = $kind === 'enum' ? enumCases($file->content) : [];

        if ($methods === [] && $constants === [] && $cases === []) {
            continue;
        }

        $byName[$name] = [
            'kind' => $kind,
            'name' => $name,
            'signature' => $methods,
            'constants' => $constants,
            'cases' => $cases,
        ];
    }

    ksort($byName);

    return array_values($byName);
}

function isInternal(ScannedFile $file): bool
{
    foreach (explode('\\', $file->namespace) as $segment) {
        if (in_array($segment, ['Support', 'Internal'], true)) {
            return true;
        }
    }
    if (str_ends_with($file->relativeDir, '/Events') || $file->relativeDir === 'Events') {
        return true;
    }

    return false;
}

/** @return list<string> normalized one-line signatures */
function publicSignatures(string $content): array
{
    $signatures = [];
    $lines = explode("\n", $content);
    $buffer = null;
    foreach ($lines as $line) {
        if ($buffer === null) {
            if (preg_match('/^\s*public\s+(?:static\s+)?function\s+\w+/', $line) === 1) {
                $buffer = $line;
            }
        } else {
            $buffer .= ' ' . trim($line);
        }
        if ($buffer !== null && preg_match('/[;{]\s*(?:\/\/.*)?$/', trim($buffer)) === 1) {
            $normalized = normalizeSignature($buffer);
            if ($normalized !== '') {
                $signatures[] = $normalized;
            }
            $buffer = null;
        }
    }

    return $signatures;
}

function normalizeSignature(string $raw): string
{
    $cut = strcspn($raw, ';{');
    $terminator = $cut < strlen($raw) ? $raw[$cut] : '';

    // strip doc-level noise: attribute lines already excluded by the scan,
    // but inline comments may survive whitespace collapse
    $oneLine = trim((string) preg_replace('/\s+\/\/.*$/', '', (string) preg_replace('/\s+/', ' ', substr($raw, 0, $cut))));
    $oneLine = (string) preg_replace('/\(\s+/', '(', $oneLine);
    $oneLine = (string) preg_replace('/,\s+\)$/', ')', rtrim($oneLine));

    if ($oneLine === '') {
        return '';
    }

    return rtrim($oneLine, ';') . ($terminator === ';' ? ';' : '');
}

/** @return list<string> */
function publicConstants(string $content): array
{
    $names = [];
    if (preg_match_all('/^\s*public\s+(?:final\s+)?const\s+(.+);/m', $content, $matches)) {
        foreach ($matches[1] as $declaration) {
            $declaration = trim((string) preg_replace('/\s+/', ' ', $declaration));
            foreach (splitConstDeclaration($declaration) as $piece) {
                if (preg_match('/^(\\\\?\w+)\s*=/', $piece, $m) === 1 || preg_match('/^(\\\\?\w+)$/', $piece, $m) === 1) {
                    $names[] = ltrim($m[1], '\\');
                }
            }
        }
    }
    $names = array_values(array_unique($names));
    sort($names);

    return $names;
}

/**
 * Split "A = [1, 2], B = self::X" on top-level commas.
 *
 * @return list<string>
 */
function splitConstDeclaration(string $declaration): array
{
    $pieces = [];
    $depth = 0;
    $current = '';
    $length = strlen($declaration);
    for ($i = 0; $i < $length; $i++) {
        $char = $declaration[$i];
        if ($char === '[' || $char === '(') {
            $depth++;
        } elseif ($char === ']' || $char === ')') {
            $depth--;
        }
        if ($char === ',' && $depth === 0) {
            $pieces[] = trim($current);
            $current = '';

            continue;
        }
        $current .= $char;
    }
    if (trim($current) !== '') {
        $pieces[] = trim($current);
    }

    return $pieces;
}

/** @return list<string> */
function enumCases(string $content): array
{
    $names = [];
    if (preg_match_all('/^\s*case\s+(\w+)/m', $content, $matches)) {
        $names = $matches[1];
    }
    $names = array_values(array_unique($names));
    sort($names);

    return $names;
}

/**
 * @param array{kind: string, name: string, signature: list<string>, constants: list<string>, cases: list<string>} $entry
 *
 * @return list<string>
 */
function renderEntry(array $entry): array
{
    $lines = [sprintf('### `%s` %s', $entry['name'], $entry['kind'])];

    if ($entry['constants'] !== []) {
        $lines[] = '- Constants: ' . implode(', ', array_map(fn (string $c): string => '`' . $c . '`', $entry['constants']));
    }
    if ($entry['cases'] !== []) {
        $lines[] = '- Cases: ' . implode(', ', array_map(fn (string $c): string => '`' . $c . '`', $entry['cases']));
    }
    foreach ($entry['signature'] as $signature) {
        $lines[] = '- `' . $signature . '`';
    }
    $lines[] = '';

    return $lines;
}
