<?php

declare(strict_types=1);

namespace ArazzoDocs\QualityGatesDoc;

const METRIC_LABELS = [
    'errors' => 'errors',
    'baseline_ignored' => 'baseline-ignored',
    'passed' => 'passed',
    'failed' => 'failed',
    'skipped' => 'skipped',
    'error' => 'error',
    'assertion' => 'assertions',
    'files_reported' => 'files-reported',
    'msi_percent' => 'MSI %',
    'killed' => 'killed',
    'escaped' => 'escaped',
    'timed_out' => 'timed-out',
    'not_covered' => 'not-covered',
];

const HIDDEN_METRICS = ['exit_code', 'duration_ms', 'summary'];

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Quality Gates Scorecard

Live measurements of the gates enforced by `.githooks/pre-commit` and
`.githooks/pre-push`, recorded by `scripts/quality-gates.php` into
`storage/quality-gates.json` (committed). Refresh with:

    make quality-gates                  # pint + phpstan + pest
    make quality-gates ARGS=--with-mutations   # + mutation testing (slow)

Only metrics are rendered (never durations or timestamps) so this file stays
byte-deterministic per measurement.

MD;

function render(string $snapshotPath): string
{
    if (!is_file($snapshotPath)) {
        return BANNER . <<<'MD'

## No measurements recorded

`storage/quality-gates.json` does not exist yet. Run:

    make quality-gates

and commit the resulting snapshot to populate this scorecard.

MD;
    }

    $data = json_decode((string) file_get_contents($snapshotPath), true);
    if (!is_array($data) || !isset($data['gates']) || !is_array($data['gates'])) {
        return BANNER . "_Corrupt snapshot at storage/quality-gates.json — rerun `make quality-gates`._\n";
    }

    $lines = [BANNER, '| Gate | Status | Metrics | Command |', '|---|---|---|---|'];

    foreach ($data['gates'] as $gate) {
        if (!is_array($gate)) {
            continue;
        }
        $status = match ($gate['status'] ?? 'unknown') {
            'pass' => '**PASS**',
            'fail' => '**FAIL**',
            default => 'UNKNOWN',
        };
        $metrics = renderMetrics(is_array($gate['metrics'] ?? null) ? $gate['metrics'] : []);
        $command = '`' . ($gate['command'] ?? '?') . '`';
        $label = (string) ($gate['label'] ?? $gate['id'] ?? '?');
        $lines[] = "| {$label} | {$status} | {$metrics} | {$command} |";
    }

    $lines[] = '';
    $lines[] = renderRollup($data['gates']);

    return implode("\n", $lines) . "\n";
}

/** @param array<string, int|float|string> $metrics */
function renderMetrics(array $metrics): string
{
    $parts = [];
    foreach ($metrics as $key => $value) {
        if (in_array($key, HIDDEN_METRICS, true) || !is_int($value) && !is_float($value)) {
            continue;
        }
        $label = METRIC_LABELS[$key] ?? str_replace('_', '-', (string) $key);
        $formatted = $key === 'msi_percent' ? sprintf('%.1f', $value) : (string) $value;
        $parts[] = "{$label}: **{$formatted}**";
    }
    ksort($parts);

    return $parts === [] ? '—' : implode(' · ', $parts);
}

/**
 * @param list<mixed> $gates
 */
function renderRollup(array $gates): string
{
    $total = count($gates);
    $pass = count(array_filter($gates, fn ($g): bool => is_array($g) && ($g['status'] ?? null) === 'pass'));
    $unmeasured = $total - $pass - count(array_filter($gates, fn ($g): bool => is_array($g) && ($g['status'] ?? null) === 'fail'));

    $failing = array_map(
        fn ($g): string => is_array($g) && ($g['status'] ?? null) === 'fail'
            ? (string) ($g['id'] ?? '?')
            : '',
        $gates,
    );
    $failing = array_values(array_filter($failing));

    $summary = "**{$pass}/{$total} gates passing.**";
    if ($unmeasured > 0) {
        $summary .= " ({$unmeasured} unmeasured)";
    }
    if ($failing !== []) {
        $summary .= "\n\nFailing: " . implode(', ', array_map(fn (string $id): string => "`{$id}`", $failing));
    }

    return $summary;
}
