<?php

declare(strict_types=1);

namespace ArazzoDocs\SecuritySurfaceDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Security Surface

Inventory of security-relevant code paths in `packages/*/src`, scanned live:

1. **Trust boundaries** — where external input enters the system.
2. **Sinks** — filesystem, process, deserialization, outbound I/O, raw SQL.
3. **Weak primitives** — known-risky constructs (eval, unserialize, weak
   hashes). This table is expected to stay empty; any row is a review item.

Regenerated before every commit.

MD;

/**
 * category => list<array{symbol, pattern, note}>
 * Patterns are matched against file content.
 */
const SINK_PATTERNS = [
    'filesystem' => [
        ['file_put_contents', '\bfile_put_contents\s*\(', null],
        ['fopen / fwrite', '\bf(?:open|write)\s*\(', null],
        ['unlink', '\bunlink\s*\(', null],
        ['Storage facade', '\bStorage::(disk|path|put|delete|get)\b', 'Laravel storage'],
    ],
    'process' => [
        ['proc_open', '\bproc_open\s*\(', null],
        ['shell_exec', '\bshell_exec\s*\(', null],
        ['exec/system/passthru', '\b(?:exec|system|passthru)\s*\(', 'verify not string function'],
    ],
    'deserialization' => [
        ['unserialize', '\bunserialize\s*\(', 'prefer allowed_classes=false'],
        ['eval', '\beval\s*\(', 'never acceptable in library code'],
    ],
    'outbound' => [
        ['Guzzle client', 'new\s+\\\\?GuzzleHttp\\\\Client\b', 'HTTP egress'],
        ['curl_init', '\bcurl_init\s*\(', 'HTTP egress'],
    ],
    'sql' => [
        ['DB::raw', 'DB::raw\s*\(', 'raw SQL'],
        ['->statement', '->statement\s*\(', 'raw SQL'],
        ['->whereRaw', '->whereRaw\s*\(', 'raw SQL'],
    ],
];

/**
 * name => pattern
 */
const WEAK_PATTERNS = [
    'eval' => '\beval\s*\(',
    'unserialize' => '\bunserialize\s*\(',
    'md5/sha1 hash' => '\b(?:md5|sha1)\s*\(',
    'openssl_random_pseudo_bytes' => '\bopenssl_random_pseudo_bytes\s*\(',
];

const TRUST_BOUNDARY_DIRS = ['Http/Controllers', 'Queue/Jobs', 'Http/Middleware'];

/**
 * @param array<string, list<ScannedFile>> $core
 * @param array<string, list<ScannedFile>> $laravel
 */
function render(array $core, array $laravel): string
{
    $files = [];
    foreach ([[...$core], [...$laravel]] as $modules) {
        foreach ($modules as $moduleFiles) {
            $files = [...$files, ...$moduleFiles];
        }
    }

    [$boundaries, $sinks, $weak] = scan($files);

    $lines = [BANNER];

    $lines[] = '## Trust boundaries';
    $lines[] = '';
    $lines[] = 'Entry points where untrusted data (HTTP requests, queue payloads) first touches the system:';
    $lines[] = '';
    $lines[] = '| Entry point | Kind |';
    $lines[] = '|---|---|';
    if ($boundaries === []) {
        $lines[] = '| — | — |';
    }
    sort($boundaries);
    foreach ($boundaries as [$fqcn, $kind]) {
        $lines[] = '| `' . short($fqcn) . '` | ' . $kind . ' |';
    }

    $lines[] = '';
    $lines[] = '## Sinks';
    $lines[] = '';
    $lines[] = '| Category | Symbol | Sites |';
    $lines[] = '|---|---|---|';

    usort($sinks, fn (array $a, array $b): int => [$a['category'], $a['symbol']] <=> [$b['category'], $b['symbol']]);
    foreach ($sinks as $entry) {
        $cells = [];
        $sites = array_values(array_unique($entry['sites']));
        sort($sites);
        foreach ($sites as $site) {
            $cells[] = '`' . short((string) $site) . '` <small>' . moduleOf((string) $site) . '</small>';
        }
        $suffix = $entry['note'] !== '' ? ' — _' . $entry['note'] . '_' : '';
        $lines[] = '| ' . $entry['category'] . ' | `' . $entry['symbol'] . '`' . $suffix . ' | ' . implode(', ', $cells) . ' |';
    }
    if ($sinks === []) {
        $lines[] = '| — | — | — |';
    }

    $lines[] = '';
    $lines[] = '## Weak or risky primitives';
    $lines[] = '';
    if ($weak === []) {
        $lines[] = '_None found. Keep it that way._';
    } else {
        $lines[] = '| Primitive | Sites |';
        $lines[] = '|---|---|';
        ksort($weak);
        foreach ($weak as $primitive => $sites) {
            $cells = [];
            foreach (array_unique($sites) as $site) {
                $cells[] = '`' . short((string) $site) . '` <small>' . moduleOf((string) $site) . '</small>';
            }
            $lines[] = '| `' . $primitive . '` | ' . implode(', ', $cells) . ' |';
        }
    }

    return implode("\n", $lines) . "\n";
}

/**
 * @param list<ScannedFile> $files
 *
 * @return array{0: list<array{string, string}>, 1: list<array{category: string, symbol: string, note: string, sites: list<string>}>, 2: array<string, list<string>>}
 */
function scan(array $files): array
{
    $boundaries = [];
    $seenBoundaries = [];
    $sinks = [];

    foreach ($files as $file) {
        $selfFqcn = $file->namespace . '\\' . $file->className;
        $dir = $file->relativeDir;

        // trust boundaries: controllers, jobs, middleware
        foreach (TRUST_BOUNDARY_DIRS as $boundaryDir) {
            if ($dir === $boundaryDir || str_starts_with($dir, $boundaryDir . '/')) {
                $kind = basename(str_replace('/', '\\', $boundaryDir));
                $key = $selfFqcn . '|' . $kind;
                if (!isset($seenBoundaries[$key])) {
                    $seenBoundaries[$key] = true;
                    $boundaries[] = [$selfFqcn, $kind];
                }

                break;
            }
        }

        foreach (SINK_PATTERNS as $category => $patterns) {
            foreach ($patterns as [$symbol, $pattern, $note]) {
                if (preg_match('#' . $pattern . '#', $file->content) === 1) {
                    $key = $category . '|' . $symbol;
                    if (!isset($sinks[$key])) {
                        $sinks[$key] = ['category' => $category, 'symbol' => $symbol, 'note' => (string) ($note ?? ''), 'sites' => []];
                    }
                    $sinks[$key]['sites'][] = $selfFqcn;
                }
            }
        }
    }

    // weak primitives
    $weak = [];
    foreach ($files as $file) {
        foreach (WEAK_PATTERNS as $name => $pattern) {
            if (preg_match('#' . $pattern . '#', $file->content) === 1) {
                $weak[$name][] = $file->namespace . '\\' . $file->className;
            }
        }
    }

    usort($boundaries, fn (array $a, array $b): int => $a[0] <=> $b[0] ?: strcmp($a[1], $b[1]));

    return [$boundaries, $sinks, $weak];
}

function short(string $fqcn): string
{
    $parts = explode('\\', $fqcn);

    return end($parts);
}

function moduleOf(string $fqcn): string
{
    return str_contains($fqcn, 'Arazzo\\Laravel\\') ? 'laravel' : 'core';
}
