<?php

declare(strict_types=1);

namespace ArazzoDocs\SolidMetricsDoc;

use ArazzoDocs\NamespaceGraphDoc;
use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: SOLID Metrics

Uncle Bob's structural health check, computed live:

1. **Abstractness × Instability** — the classic design balance chart. Bottom-right
   ("zone of pain"): concrete modules everything depends on. Top-left
   ("zone of uselessness"): abstractions nobody uses.
2. **God classes** — single types absorbing too much responsibility (SRP).
3. **Fat interfaces** — contracts demanding more than clients need (ISP).
4. **Concrete hubs** — heavily depended-upon modules offering no abstraction (DIP).

MD;

const GOD_CLASS_LOC = 300;
const FAT_INTERFACE_METHODS = 7;
const CONCRETE_HUB_FAN_IN = 4;

/**
 * @param  array<string, list<ScannedFile>>  $core
 * @param  array<string, list<ScannedFile>>  $laravel
 */
function render(array $core, array $laravel): string
{
    $all = NamespaceGraphDoc\merge($core, $laravel);

    $classModule = [];
    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            $classModule[$file->namespace.'\\'.$file->className] = $module;
        }
    }

    $instability = instability($all, $classModule);
    [$abstractness, $concreteCounts] = abstractness($all);
    [$godClasses, $fatInterfaces] = structuralFindings($all);
    $fanInByModule = hubFanIn($all, $classModule);

    $lines = [BANNER];

    // zone chart over plottable modules
    $points = [];
    foreach ($abstractness as $module => $aScore) {
        if (!isset($instability[$module])) {
            continue;
        }
        $points[] = ['label' => str_replace(':', '/', $module), 'x' => round($instability[$module], 3), 'y' => round($aScore, 3)];
    }
    usort($points, fn (array $a, array $b): int => strcmp((string) $a['label'], (string) $b['label']));

    if ($points !== []) {
        $lines[] = '## Design balance';
        $lines[] = '';
        $lines[] = '```mermaid';
        $lines[] = 'quadrantChart';
        $lines[] = '    title Abstractness vs Instability';
        $lines[] = '    x-axis Stable --> Unstable';
        $lines[] = '    y-axis Concrete --> Abstract';
        $lines[] = '    quadrant-1 Zone of uselessness';
        $lines[] = '    quadrant-2 Ideal abstractions';
        $lines[] = '    quadrant-3 Modular building blocks';
        $lines[] = '    quadrant-4 Zone of pain';
        foreach ($points as $point) {
            $lines[] = sprintf('    %s: [%s, %s]', $point['label'], $point['x'], $point['y']);
        }
        $lines[] = '```';
        $lines[] = '';
    }

    // god classes
    $lines[] = '## God classes (SRP)';
    $lines[] = '';
    $lines[] = sprintf('Concrete types over %d LOC:', GOD_CLASS_LOC);
    $lines[] = '';
    $lines[] = '| Class | Module | LOC |';
    $lines[] = '|---|---|---:|';
    usort($godClasses, fn (array $a, array $b): int => $b[2] <=> $a[2]);
    if ($godClasses === []) {
        $lines[] = '| — | — | — |';
    }
    foreach ($godClasses as [$fqcn, $module, $loc]) {
        $lines[] = sprintf('| `%s` | `%s` | %d |', short($fqcn), $module, $loc);
    }

    // fat interfaces
    $lines[] = '';
    $lines[] = '## Fat interfaces (ISP)';
    $lines[] = '';
    $lines[] = sprintf('Contracts declaring more than %d methods:', FAT_INTERFACE_METHODS);
    $lines[] = '';
    $lines[] = '| Interface | Methods |';
    $lines[] = '|---|---:|';
    usort($fatInterfaces, fn (array $a, array $b): int => $b[1] <=> $a[1]);
    if ($fatInterfaces === []) {
        $lines[] = '| — | — |';
    }
    foreach ($fatInterfaces as [$fqcn, $count]) {
        $lines[] = sprintf('| `%s` <small>%s</small> | %d |', short($fqcn), packageOf($fqcn), $count);
    }

    // concrete hubs
    $lines[] = '';
    $lines[] = '## Concrete hubs (DIP)';
    $lines[] = '';
    $lines[] = sprintf('Modules depended upon by ≥%d others while offering no interface:', CONCRETE_HUB_FAN_IN);
    $lines[] = '';
    $lines[] = '| Module | Fan-in | Classes | Interfaces |';
    $lines[] = '|---|---:|---:|---:|';
    $hubList = [];
    foreach ($all as $module => $files) {
        $in = count($fanInByModule[$module] ?? []);
        if ($in >= CONCRETE_HUB_FAN_IN && ($concreteCounts[$module] ?? 0) > 0 && ($abstractness[$module] ?? 1.0) === 0.0) {
            $hubList[] = sprintf('| `%s` | %d | %d | 0 |', $module, $in, $concreteCounts[$module]);
        }
    }
    $lines = [...$lines, ...($hubList === [] ? ['| — | — | — | 0 |'] : $hubList)];

    return implode("\n", $lines)."\n";
}

/**
 * @param  array<string, list<ScannedFile>>  $all
 * @param  array<string, string>  $classModule
 * @return array<string, array<string, true>>
 */
function hubFanIn(array $all, array $classModule): array
{
    $fanIn = [];
    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            foreach ($file->uses as $use) {
                $target = $classModule[$use] ?? null;
                if ($target === null || $target === $module) {
                    continue;
                }
                $fanIn[$target][$module] = true;
            }
        }
    }

    return $fanIn;
}

/**
 * @param  array<string, list<ScannedFile>>  $all
 * @param  array<string, string>  $classModule
 * @return array<string, float>
 */
function instability(array $all, array $classModule): array
{
    $fanIn = hubFanIn($all, $classModule);
    $fanOut = [];
    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            foreach ($file->uses as $use) {
                $target = $classModule[$use] ?? null;
                if ($target === null || $target === $module) {
                    continue;
                }
                $fanOut[$module][$target] = true;
            }
        }
    }

    $result = [];
    foreach (array_unique([...array_keys($fanIn), ...array_keys($fanOut)]) as $module) {
        $in = count($fanIn[$module] ?? []);
        $out = count($fanOut[$module] ?? []);
        $total = $in + $out;
        if ($total > 0) {
            $result[$module] = $out / $total;
        }
    }

    return $result;
}

/**
 * @param  array<string, list<ScannedFile>>  $all
 * @return array{0: array<string, float>, 1: array<string, int>}
 */
function abstractness(array $all): array
{
    $scores = [];
    $concrete = [];
    foreach ($all as $module => $files) {
        $interfaces = 0;
        $abstract = 0;
        $total = count($files);
        foreach ($files as $file) {
            if ($file->isInterface) {
                $interfaces++;

                continue;
            }
            if (preg_match('/^abstract\s+class\b/m', $file->content) === 1) {
                $abstract++;
            }
        }
        $concrete[$module] = $total - $interfaces - $abstract;
        $scores[$module] = $total > 0 ? ($interfaces + $abstract) / $total : 0.0;
    }

    return [$scores, $concrete];
}

/**
 * @param  array<string, list<ScannedFile>>  $all
 * @return array{0: list<array{string, string, int}>, 1: list<array{string, int}>, 2: list<array{string, int}>}
 */
function structuralFindings(array $all): array
{
    $godClasses = [];
    $fatInterfaces = [];

    foreach ($all as $module => $files) {
        foreach ($files as $file) {
            $loc = substr_count($file->content, "\n") + 1;
            if (!$file->isInterface && $loc >= GOD_CLASS_LOC) {
                $godClasses[] = [$file->namespace.'\\'.$file->className, $module, $loc];
            }
            if ($file->isInterface) {
                $methods = (int) preg_match_all('/^\s*(?:public\s+)?function\s+\w+/m', $file->content);
                if ($methods > FAT_INTERFACE_METHODS) {
                    $fatInterfaces[] = [$file->namespace.'\\'.$file->className, $methods];
                }
            }
        }
    }

    return [$godClasses, $fatInterfaces, []];
}

function short(string $fqcn): string
{
    $parts = explode('\\', $fqcn);

    return end($parts);
}

function packageOf(string $fqcn): string
{
    return str_contains($fqcn, 'Laravel') ? 'laravel' : 'core';
}
