<?php

declare(strict_types=1);

namespace ArazzoDocs\StateMachineDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Run Lifecycle State Machine

The reliability contract of the runner, in one picture. States come live from
the `*Status` / `TransitionType` enums; edges are derived from the
`Transition::*()` factories inside the engine's `transition()` method, labelled
with the trigger found immediately before each call site. Guards are the
exceptions that method raises. Any diff here is a behavioural contract change.

MD;

/**
 * Verb => [from state, to state] skeletons. Targets ending in "?" take the
 * literal argument parsed from the call site (e.g. end(...) status).
 */
const VERB_EDGES = [
    'next' => ['Executing', 'Executing'],
    'retry' => ['StepFailed', 'Retrying'],
    'goto' => ['Executing', 'Executing'],
    'invoke' => ['Executing', 'Invoking'],
    'suspend' => ['Executing', 'Suspended'],
    'end' => ['Executing', '?'],
];

/**
 * @param array<string, list<ScannedFile>> $core
 * @param array<string, list<ScannedFile>> $laravel
 */
function render(array $core, array $laravel): string
{
    $flat = [];
    foreach ([...$core, ...$laravel] as $moduleFiles) {
        foreach ($moduleFiles as $file) {
            $flat[] = $file;
        }
    }

    $enums = collectEnums($flat);
    $engine = findEngineFile($flat);

    if ($engine === null || $enums === []) {
        return BANNER . "_Engine or status enums not found — diagram unavailable._\n";
    }

    [$edges, $guards] = extractEdgesAndGuards($engine);

    $lines = [BANNER, '```mermaid', 'stateDiagram-v2'];

    // execution-level machine
    $lines[] = '    direction TB';
    $lines[] = '    [*] --> Executing : RunStarted';
    foreach ($edges as [$trigger, $verb, $arg]) {
        $target = VERB_EDGES[$verb][1];
        if ($target === '?') {
            $target = $arg !== '' ? ucfirst($arg) : 'Ended';
        }
        if ($target === 'Invoking') {
            // invoke resumes executing after the nested workflow returns
            $lines[] = sprintf('    Executing --> Invoking : %s', escapeLabel($trigger));
            $lines[] = '    Invoking --> Executing : nested run completes';
        } else {
            $lines[] = sprintf(
                '    %s --> %s : %s',
                VERB_EDGES[$verb][0],
                $target,
                escapeLabel($trigger),
            );
        }
    }
    foreach (['Succeeded', 'Failed'] as $terminal) {
        $lines[] = "    {$terminal} --> [*]";
    }

    // step-level machine derived from StepStatus enum cases
    if (isset($enums['StepStatus'])) {
        $lines[] = '';
        $lines[] = '    state "step lifecycle" as stepmachine {';
        $prev = null;
        foreach ($enums['StepStatus'] as $caseName) {
            $lines[] = sprintf('        %s', $caseName);
            if ($prev === null) {
                $lines[] = '        [*] --> ' . $caseName;
            } else {
                // no invented edges between cases: enumeration only
            }
            $prev = $caseName;
        }
        $lines[] = '    }';
    }

    $lines[] = '```';

    // live inventory tables
    $lines[] = '';
    $lines[] = '## Enumerated states (live)';
    $lines[] = '';
    $lines[] = '| Enum | Cases |';
    $lines[] = '|---|---|';
    ksort($enums);
    foreach ($enums as $name => $cases) {
        $lines[] = '| `' . $name . '` | ' . implode(' · ', $cases) . ' |';
    }

    $lines[] = '';
    $lines[] = '## Transition verbs (live call sites in engine)';
    $lines[] = '';
    $lines[] = '| Trigger (nearest condition above call) | Verb | Argument |';
    $lines[] = '|---|---|---|';
    foreach ($edges as [$trigger, $verb, $arg]) {
        $lines[] = '| ' . escapeCell($trigger) . ' | `' . $verb . '` | ' . ($arg !== '' ? '`' . $arg . '`' : '—') . ' |';
    }

    $lines[] = '';
    $lines[] = '## Guards raised by transition()';
    $lines[] = '';
    if ($guards === []) {
        $lines[] = '_None._';
    } else {
        $lines[] = '| Exception | Meaning |';
        $lines[] = '|---|---|';
        foreach ($guards as $exception) {
            $lines[] = '| `' . $exception . '` | ' . guardMeaning($exception) . ' |';
        }
    }

    return implode("\n", $lines) . "\n";
}

/** @param list<ScannedFile> $files */
function collectEnums(array $files): array
{
    $enums = [];
    foreach ($files as $file) {
        if (!str_ends_with($file->className, 'Status') && $file->className !== 'TransitionType') {
            continue;
        }
        if (preg_match_all('/^\s*case\s+(\w+)\s*=/m', $file->content, $m)) {
            $enums[$file->className] = $m[1];
        }
    }
    ksort($enums);

    return $enums;
}

/** @param list<ScannedFile> $files */
function findEngineFile(array $files): ?ScannedFile
{
    foreach ($files as $file) {
        if ($file->className === 'WorkflowEngine' && str_contains($file->content, 'function transition(')) {
            return $file;
        }
    }

    return null;
}

/**
 * Every `Transition::verb(` call site paired with the trigger text found
 * between the previous call site (or method start) and this one.
 *
 *
 * @return array{0: list<array{string, string, string}>, 1: list<string>}
 */
function extractEdgesAndGuards(ScannedFile $engine): array
{
    $content = $engine->content;

    preg_match_all('/Transition::(\w+)\(/', $content, $calls, PREG_OFFSET_CAPTURE);

    $edges = [];
    $seen = [];
    $previousOffset = 0;
    foreach ($calls[1] as $call) {
        [$verb, $offset] = [(string) $call[0], (int) $call[1]];

        // window bounded by the previous Transition:: site: triggers cannot leak
        // across call sites
        $windowStart = max(0, $previousOffset);
        $window = substr($content, $windowStart, $offset - $windowStart);
        $previousOffset = $offset;

        [$trigger, $args] = detectTrigger($window, $verb, substr($content, $offset, 160));

        foreach ($args === [] ? [''] : $args as $arg) {
            $key = "{$trigger}|{$verb}|{$arg}";
            if (isset($seen[$key])) {
                continue;
            }
            $seen[$key] = true;
            $edges[] = [$trigger, $verb, $arg];
        }
    }

    usort($edges, fn (array $x, array $y): int => [$x[1], $x[0]] <=> [$y[1], $y[0]] ?: strcmp($x[2], $y[2]));

    preg_match_all('/throw\s+new\s+(\w+)\(/', $content, $thrown);
    $guards = array_values(array_unique($thrown[1]));
    sort($guards);

    return [$edges, $guards];
}

/**
 * @return array{0: string, 1: list<string>} trigger + literal args (for end())
 */
function detectTrigger(string $windowAbove, string $verb, string $callArgs): array
{
    if ($verb === 'end' && preg_match('/\?\s*[\'"](\w+)[\'"]\s*:\s*[\'"](\w+)[\'"]/', $callArgs, $t)) {
        return ['action: terminal action', [$t[1], $t[2]]];
    }
    if ($verb === 'end' && preg_match('/[\'"](\w+)[\'"]/', $callArgs, $t)) {
        $trigger = preg_match('/!\$criteriaMet/', $windowAbove) === 1
            ? 'criteria NOT met (no matching action)'
            : 'workflow exhausted (no runnable step)';

        return [$trigger, [$t[1]]];
    }

    // prefer action-type checks; ignore unrelated instanceof (e.g. Expression)
    if (preg_match_all('/instanceof\s+(\w+)\b/', $windowAbove, $m)) {
        $actions = array_values(array_filter($m[1], fn (string $c): bool => str_ends_with($c, 'Action')));
        if ($actions !== []) {
            return ['action: ' . end($actions), []];
        }
    }

    if ($verb === 'suspend') {
        return ['adapter suspended the step', []];
    }
    if ($verb === 'retry') {
        return ['retry action, attempts < limit', []];
    }

    return [match ($verb) {
        'next', 'end' => 'criteria met + dependency-ordered next step',
        default => '(see engine)',
    }, []];
}

function guardMeaning(string $exception): string
{
    return match (true) {
        str_contains($exception, 'Budget') => 'step budget exhausted',
        str_contains($exception, 'Depth') => 'workflow nesting depth exceeded',
        str_contains($exception, 'Cycle') => 're-entry into running workflow blocked',
        str_contains($exception, 'NotFound') => 'goto/reusable target missing',
        default => '',
    };
}

function escapeLabel(string $label): string
{
    return str_replace([',', ':'], ['，', ' -'], $label);
}

function escapeCell(string $text): string
{
    return str_replace('|', '\\|', $text);
}
