<?php

declare(strict_types=1);

namespace ArazzoDocs\SubdomainMapDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Subdomain Map

Strategic classification: where does this codebase invest, and should it?
Classification is a **declared seed** (edit `SUBDOMAINS` when strategy
changes); LOC and module membership are always scanned live — the numbers keep
the declaration honest.

- **Core domain** — the reason this package exists; hand-written, heavily tested.
- **Supporting** — necessary domain work, less differentiation.
- **Generic** — solved problems; adapters over frameworks. Buy, don't build.

MD;

/**
 * Bare module name => subdomain. Modules not listed are flagged unclassified.
 */
const SUBDOMAINS = [
    'Runner' => 'core',
    'Expression' => 'core',
    'Spec' => 'core',

    'Parser' => 'supporting',
    'Resolver' => 'supporting',
    'Validator' => 'supporting',
    'Generator' => 'supporting',
    'License' => 'supporting',
    'Console' => 'supporting',
    'Renderer' => 'supporting',

    'Support' => 'generic',
    'Persistence' => 'generic',
    'Lock' => 'generic',
    'State' => 'generic',
    'Queue' => 'generic',
    'Http' => 'generic',
    'Bindings' => 'generic',
    'Events' => 'generic',
];

const SUBDOMAIN_LABELS = ['core' => 'Core domain', 'supporting' => 'Supporting', 'generic' => 'Generic subdomain'];

/**
 * @param array<string, list<ScannedFile>> $core
 * @param array<string, list<ScannedFile>> $laravel
 */
function render(array $core, array $laravel): string
{
    // bare module => [package => LOC]
    $modules = [];
    foreach ([['core', $core], ['laravel', $laravel]] as [$package, $moduleSet]) {
        foreach ($moduleSet as $module => $files) {
            if ($module === '_') {
                continue;
            }
            $loc = 0;
            foreach ($files as $file) {
                $loc += substr_count($file->content, "\n") + 1;
            }
            $modules[$module][$package] = ($modules[$module][$package] ?? 0) + $loc;
        }
    }
    ksort($modules);

    $grouped = ['core' => [], 'supporting' => [], 'generic' => [], 'unclassified' => []];
    foreach ($modules as $module => $locs) {
        $grouped[SUBDOMAINS[$module] ?? 'unclassified'][$module] = $locs;
    }

    $lines = [BANNER, '```mermaid', 'flowchart LR'];

    $colors = ['core' => 'coreDomain', 'supporting' => 'supportingDomain', 'generic' => 'genericDomain', 'unclassified' => 'unknownDomain'];
    foreach (['core', 'supporting', 'generic', 'unclassified'] as $subdomain) {
        if ($grouped[$subdomain] === []) {
            continue;
        }
        $lines[] = sprintf('    subgraph %s["%s"]', nodeId($subdomain), SUBDOMAIN_LABELS[$subdomain]);
        foreach ($grouped[$subdomain] as $module => $locs) {
            $totalLoc = array_sum($locs);
            $lines[] = sprintf('        %s["%s<br/><small>%d LOC</small>"]:::%s', nodeId($module), $module, $totalLoc, $colors[$subdomain]);
        }
        $lines[] = '    end';
    }

    $lines[] = '    classDef coreDomain fill:#e6f4ea,stroke:#34a853,color:#1a1a1a;';
    $lines[] = '    classDef supportingDomain fill:#e8f0fe,stroke:#4285f4,color:#1a1a1a;';
    $lines[] = '    classDef genericDomain fill:#f1f3f4,stroke:#9aa0a6,color:#1a1a1a;';
    $lines[] = '    classDef unknownDomain fill:#fce8e6,stroke:#ea4335,color:#1a1a1a;';
    $lines[] = '```';

    // investment table
    $lines[] = '';
    $lines[] = '| Subdomain | Modules | Core pkg LOC | Laravel pkg LOC | Share |';
    $lines[] = '|---|---:|---:|---:|---:|';
    $grandTotal = 0;
    $subTotals = [];
    foreach ($grouped as $subdomain => $mods) {
        $coreLoc = 0;
        $laravelLoc = 0;
        foreach ($mods as $locs) {
            $coreLoc += $locs['core'] ?? 0;
            $laravelLoc += $locs['laravel'] ?? 0;
        }
        $grandTotal += $coreLoc + $laravelLoc;
        $subTotals[$subdomain] = [$coreLoc, $laravelLoc, count($mods)];
    }
    foreach ($subTotals as $subdomain => [$coreLoc, $laravelLoc, $count]) {
        if ($count === 0) {
            continue;
        }
        $share = $grandTotal > 0 ? sprintf('%.0f%%', ($coreLoc + $laravelLoc) / $grandTotal * 100) : '—';
        $lines[] = sprintf(
            '| %s | %d | %s | %s | %s |',
            SUBDOMAIN_LABELS[$subdomain],
            $count,
            number_format((float) $coreLoc),
            number_format((float) $laravelLoc),
            $share,
        );
    }

    if ($grouped['unclassified'] !== []) {
        $lines[] = '';
        $lines[] = '**Unclassified modules** — classify them in `SUBDOMAINS` or delete them:';
        foreach (array_keys($grouped['unclassified']) as $module) {
            $lines[] = '- `' . $module . '`';
        }
    }

    return implode("\n", $lines) . "\n";
}

function nodeId(string $value): string
{
    return 'S_' . ((preg_replace('/[^A-Za-z0-9_]/', '_', $value)) ?? $value);
}
