<?php

declare(strict_types=1);

namespace ArazzoDocs\TestEconomicsDoc;

use const ArazzoDocs\CORE_SRC_PACKAGES;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Test Economics

Is the safety net keeping pace with the code? Production LOC vs test LOC,
test-method density, and the last measured suite cost. Cross-reference with
`coverage-risk.md` (which modules) and `churn-hotspots.md` (where edits land).

MD;

/**
 * @param  array<string, list<ScannedFile>>  $core
 * @param  array<string, list<ScannedFile>>  $laravel
 */
function render(array $core, array $laravel, string $root): string
{
    $lines = [BANNER, '| Package | Src LOC | Test LOC | Test/Src | Test files | Test methods | Methods/file |', '|---|---:|---:|---:|---:|---:|---:|'];

    foreach ([['core', $core], ['laravel', $laravel]] as [$label, $modules]) {
        $srcLoc = 0;
        foreach ($modules as $files) {
            foreach ($files as $file) {
                $srcLoc += substr_count($file->content, "\n") + 1;
            }
        }

        $testsDirs = $label === 'core'
            ? [
                ...array_map(fn (string $package): string => $root.'/packages/'.$package.'/tests', CORE_SRC_PACKAGES),
                $root.'/packages/core/tests', // cross-cutting integration/architecture/conformance suites
            ]
            : [$root.'/packages/laravel/tests'];

        [$testLoc, $testFiles, $testMethods] = array_reduce(
            $testsDirs,
            function (array $carry, string $dir): array {
                [$loc, $files, $methods] = scanTests($dir);

                return [$carry[0] + $loc, $carry[1] + $files, $carry[2] + $methods];
            },
            [0, 0, 0],
        );
        $ratio = $srcLoc > 0 ? round($testLoc / $srcLoc * 100) : 0;
        $density = $testFiles > 0 ? round($testMethods / $testFiles, 1) : 0;

        $lines[] = sprintf(
            '| %s | %s | %s | %d%% | %d | %d | %.1f |',
            $label,
            number_format((float) $srcLoc),
            number_format((float) $testLoc),
            $ratio,
            $testFiles,
            $testMethods,
            $density,
        );
    }

    // last measured cost from the gate snapshot
    $snapshotPath = $root.'/storage/quality-gates.json';
    if (is_file($snapshotPath)) {
        $data = json_decode((string) file_get_contents($snapshotPath), true);
        $rows = [];
        foreach ((array) ($data['gates'] ?? []) as $gate) {
            if (!is_array($gate) || !str_starts_with((string) ($gate['id'] ?? ''), 'pest')) {
                continue;
            }
            $metrics = (array) ($gate['metrics'] ?? []);
            $rows[$gate['id']] = [
                'duration' => (int) ($metrics['duration_ms'] ?? 0),
                'passed' => (int) ($metrics['passed'] ?? 0),
                'assertions' => (int) ($metrics['assertions'] ?? 0),
            ];
        }
        if ($rows !== []) {
            $lines[] = '';
            $lines[] = '## Last measured suite cost';
            $lines[] = '';
            $lines[] = '| Suite | Duration | Passed | Assertions/test |';
            $lines[] = '|---|---:|---:|---:|';
            foreach ($rows as $suite => $row) {
                $perTest = $row['passed'] > 0 ? round($row['assertions'] / $row['passed'], 1) : 0;
                $lines[] = sprintf(
                    '| `%s` | %.1fs | %s | %.1f |',
                    $suite,
                    $row['duration'] / 1000,
                    number_format((float) $row['passed']),
                    $perTest,
                );
            }
        }
    }

    return implode("\n", $lines)."\n";
}

/** @return array{0: int, 1: int, 2: int} loc, file count, test-method count */
function scanTests(string $testsDir): array
{
    if (!is_dir($testsDir)) {
        return [0, 0, 0];
    }

    $loc = 0;
    $files = 0;
    $methods = 0;
    $iterator = new \RecursiveIteratorIterator(
        new \RecursiveDirectoryIterator($testsDir, \FilesystemIterator::SKIP_DOTS),
    );

    /** @var \SplFileInfo $file */
    foreach ($iterator as $file) {
        if ($file->getExtension() !== 'php' || !str_ends_with($file->getFilename(), 'Test.php')) {
            continue;
        }
        $files++;
        $content = (string) file_get_contents((string) $file->getPathname());
        $loc += substr_count($content, "\n") + 1;
        $methods += (int) preg_match_all('/(?:^|\s)(?:it|test)\(|public\s+function\s+test\w*\s*\(/', $content);
    }

    return [$loc, $files, $methods];
}
