<?php

declare(strict_types=1);

namespace ArazzoDocs\TestCompositionDoc;

use const ArazzoDocs\CORE_SRC_PACKAGES;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Test Suite Composition

Shape of the reliability evidence, counted by test file (`*Test.php`) per
suite directory in `packages/*/tests`. A healthy package usually shows a wide
unit base, a deliberate feature layer, and a conformance slice proving spec
compliance — not an inverted pyramid of end-to-end tests.

MD;

const CATEGORY_DIRS = [
    'Unit' => 'Unit',
    'Feature' => 'Feature',
    'Conformance' => 'Conformance',
    'Architecture' => 'Architecture',
    'Property' => 'Property',
];

/**
 * @param  array<string, mixed>  $_core  unused (kept for signature symmetry)
 * @param  array<string, mixed>  $_laravel  unused
 */
function render(array $_core = [], array $_laravel = [], ?string $root = null): string
{
    $root ??= dirname(__DIR__, 2);

    $lines = [BANNER];

    $suites = [];
    foreach (CORE_SRC_PACKAGES as $package) {
        $suites[] = [ucfirst($package), $root.'/packages/'.$package.'/tests'];
    }
    $suites[] = ['Core (integration)', $root.'/packages/core/tests'];
    $suites[] = ['Laravel', $root.'/packages/laravel/tests'];

    foreach ($suites as [$label, $testsDir]) {
        $counts = countSuite($testsDir);

        $lines[] = '';
        $lines[] = '## '.$label.' package';
        $lines[] = '';
        if ($counts === []) {
            $lines[] = '_No test files found._';

            continue;
        }
        arsort($counts);

        $total = array_sum($counts);
        $lines[] = '```mermaid';
        $lines[] = 'pie showData';
        $lines[] = '    title '.$label.' — '.$total.' test files';
        foreach ($counts as $category => $count) {
            $lines[] = sprintf('    "%s": %d', $category, $count);
        }
        $lines[] = '```';

        $lines[] = '';
        $lines[] = '| Suite | Files | Share |';
        $lines[] = '|---|---:|---:|';
        foreach ($counts as $category => $count) {
            $lines[] = sprintf('| %s | %d | %.0f%% |', $category, $count, $count / max(1, $total) * 100);
        }
    }

    return implode("\n", $lines)."\n";
}

/** @return array<string, int> category => file count */
function countSuite(string $testsDir): array
{
    if (!is_dir($testsDir)) {
        return [];
    }

    $counts = [];
    $iterator = new \RecursiveIteratorIterator(
        new \RecursiveDirectoryIterator($testsDir, \FilesystemIterator::SKIP_DOTS),
    );

    /** @var \SplFileInfo $file */
    foreach ($iterator as $file) {
        if ($file->getExtension() !== 'php'
            || !str_ends_with($file->getFilename(), 'Test.php')) {
            continue;
        }
        $relative = str_replace($testsDir.'/', '', (string) $file->getPathname());
        $parts = explode('/', $relative);
        $top = $parts[0];
        $category = CATEGORY_DIRS[$top] ?? (count($parts) > 1 ? 'Module-scoped ('.$top.')' : 'Root');

        // collapse per-module buckets into one comparable slice
        if (str_starts_with($category, 'Module-scoped')) {
            $category = 'Module-scoped';
        }
        $counts[$category] = ($counts[$category] ?? 0) + 1;
    }

    ksort($counts);
    arsort($counts);

    return $counts;
}
