<?php

declare(strict_types=1);

namespace ArazzoDocs\TrustBoundaryFlowDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Trust Boundary Flow

How untrusted input travels from each entry point into the core. Edges are the
entry point's constructor-injected and instantiated dependencies (same
extraction as the pipeline doc). **Validation** nodes mark dependencies whose
name signals request validation; a boundary reaching a sink-named dependency
directly is drawn red — review that path before trusting it.

MD;

const BOUNDARY_DIRS = ['Http/Controllers', 'Http/Middleware', 'Queue/Jobs'];

const VALIDATION_MARKERS = '/(?:Validat|Authorize|Sanitiz|Assert)/';

const SINK_MARKERS = '/(?:Filesystem|File_|Storage|ProcOpen|ShellExec|Unserialize|RawQuery|Statement|HttpClient|Client\b)/';

/**
 * @param  array<string, array<string, list<ScannedFile>>>  $scans  package slug => (module => files)
 */
function render(array $scans): string
{
    $byFqcn = [];
    foreach (\ArazzoDocs\flattenScans($scans) as $file) {
        if (!$file->isInterface) {
            $byFqcn[$file->namespace.'\\'.$file->className] = $file;
        }
    }

    // short-name resolution index (unique names only)
    $shortIndex = [];
    foreach (array_keys($byFqcn) as $fqcn) {
        $name = short($fqcn);
        $shortIndex[$name] = isset($shortIndex[$name]) ? '' : $fqcn;
    }

    $boundaries = [];
    foreach ($byFqcn as $fqcn => $file) {
        foreach (BOUNDARY_DIRS as $dir) {
            if ($file->relativeDir === $dir || str_starts_with($file->relativeDir, $dir.'/')) {
                $boundaries[$fqcn] = $file;

                break;
            }
        }
    }
    ksort($boundaries);

    if ($boundaries === []) {
        return BANNER."_No trust boundaries found._\n";
    }

    [$lines, $findings] = renderDiagram($boundaries, $byFqcn, $shortIndex);

    $lines[] = '';
    $lines[] = '## Path audit';
    $lines[] = '';
    $lines[] = '| Boundary | Validation on path? | Direct sink access |';
    $lines[] = '|---|---|---|';
    ksort($findings);
    foreach ($findings as $boundary => [$validated, $sinkHit]) {
        $lines[] = sprintf(
            '| `%s` | %s | %s |',
            short($boundary),
            $validated ? '**yes**' : '_none found in ctor deps_',
            $sinkHit ? '⚠ **yes — review**' : 'no',
        );
    }

    return implode("\n", $lines)."\n";
}

/**
 * @param  array<string, ScannedFile>  $boundaries
 * @param  array<string, ScannedFile>  $byFqcn
 * @param  array<string, string>  $shortIndex
 * @return array{0: list<string>, 1: array<string, array{bool, bool}>}
 */
function renderDiagram(array $boundaries, array $byFqcn, array $shortIndex): array
{
    $lines = [BANNER, '```mermaid', 'flowchart LR'];
    $findings = [];

    foreach ($boundaries as $fqcn => $file) {
        $nodeId = nodeId($fqcn);
        $lines[] = sprintf('    %s["%s<br/><small>%s</small>"]:::boundary', $nodeId, short($fqcn), dirLabel($file));

        [$deps, $validated, $sinkHit] = boundaryDeps($file, $byFqcn, $shortIndex);

        if ($deps === []) {
            $lines[] = sprintf('    %s --> UNTRUSTED_%s["input used directly"]:::plain', $nodeId, nodeId($fqcn));
        }
        foreach ($deps as $depFqcn) {
            $depNode = nodeId((string) $depFqcn);
            $style = isSink((string) $depFqcn) ? 'sink' : (isValidation((string) $depFqcn) ? 'validation' : 'service');
            $lines[] = sprintf('        %s["%s"]:::%s', $depNode, short((string) $depFqcn), $style);
            $edgeStyle = isValidation((string) $depFqcn) ? '==> |validates|' : '-->';
            $lines[] = sprintf('    %s %s %s', $nodeId, $edgeStyle, $depNode);
        }

        $findings[$fqcn] = [$validated, $sinkHit];
    }

    $lines[] = '    classDef boundary fill:#fef7e0,stroke:#f9ab00,color:#1a1a1a;';
    $lines[] = '    classDef validation fill:#e6f4ea,stroke:#34a853,color:#1a1a1a;';
    $lines[] = '    classDef service fill:#e8f0fe,stroke:#4285f4,color:#1a1a1a;';
    $lines[] = '    classDef sink fill:#fce8e6,stroke:#ea4335,color:#1a1a1a;';
    $lines[] = '    classDef plain fill:#f1f3f4,stroke:#9aa0a6,color:#1a1a1a;';
    $lines[] = '```';

    return [$lines, $findings];
}

/**
 * @param  array<string, ScannedFile>  $byFqcn
 * @param  array<string, string>  $shortIndex
 * @return array{0: list<string>, 1: bool, 2: bool}
 */
function boundaryDeps(ScannedFile $file, array $byFqcn, array $shortIndex): array
{
    $aliases = aliasMap($file);
    $deps = [];

    $resolve = function (string $token) use ($file, $byFqcn, $shortIndex, $aliases, &$deps): void {
        $token = ltrim(trim($token), '?\\');
        if ($token === '' || !preg_match('/^[A-Za-z_][\w\\\\]*$/', $token)) {
            return;
        }
        foreach (explode('|', $token) as $part) {
            $part = ltrim(trim($part), '?');
            $candidate = null;
            if (isset($aliases[$part])) {
                $candidate = $aliases[$part];
            } elseif (isset($byFqcn[$file->namespace.'\\'.$part])) {
                $candidate = $file->namespace.'\\'.$part;
            } elseif (($shortIndex[$part] ?? '') !== '') {
                $candidate = $shortIndex[$part];
            }
            if ($candidate !== null && isset($byFqcn[$candidate])) {
                $deps[$candidate] = true;
            }
        }
    };

    if (preg_match_all('/(?:private|protected|public)(?:\s+readonly)?\s+([\w|?]+)\s+\$\w+/', $file->content, $props)) {
        foreach ($props[1] as $type) {
            $resolve($type);
        }
    }
    if (preg_match_all('/new\s+(\w+)\s*\(/', $file->content, $news)) {
        foreach ($news[1] as $class) {
            $resolve($class);
        }
    }

    $list = array_keys($deps);
    sort($list);

    $validated = false;
    $sinkHit = false;
    foreach ($list as $dep) {
        if (isValidation((string) $dep)) {
            $validated = true;
        }
        if (isSink((string) $dep)) {
            $sinkHit = true;
        }
    }

    return [$list, $validated, $sinkHit];
}

function isValidation(string $fqcn): bool
{
    return preg_match(VALIDATION_MARKERS, short($fqcn)) === 1;
}

function isSink(string $fqcn): bool
{
    return preg_match(SINK_MARKERS, short($fqcn)) === 1;
}

function aliasMap(ScannedFile $file): array
{
    $map = [];
    foreach ($file->useStatements as $statement) {
        if (preg_match('/^([\w\\\\]+)\s+as\s+(\w+)$/', $statement, $m)
            && str_starts_with($m[1], 'Alama\\')) {
            $map[$m[2]] = $m[1];
        }
    }

    return $map;
}

function short(string $fqcn): string
{
    $parts = explode('\\', $fqcn);

    return end($parts);
}

function dirLabel(ScannedFile $file): string
{
    return str_replace('/', '\\', $file->relativeDir);
}

function nodeId(string $value): string
{
    return 'T_'.((preg_replace('/[^A-Za-z0-9_]/', '_', $value)) ?? $value);
}
