<?php

declare(strict_types=1);

namespace ArazzoDocs\UbiquitousLanguageAuditDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Ubiquitous Language Audit

Evans' first question: does the code speak one language?

1. **Synonyms** — concept groups where several names coexist in the type
   vocabulary. Each pair is a translation cost someone pays forever; either
   pick one or document why both exist.
2. **Homonyms** — the same type name declared in more than one place, meaning
   (possibly) two things. Every one of these is a conversation trap.

MD;

/**
 * Candidate synonym groups. A group is reported only when 2+ of its members
 * actually occur in class/interface names — curated seeds, live evidence.
 */
const SYNONYM_GROUPS = [
    'run vs execute vs invoke' => ['Run', 'Execute', 'Invoke', 'Runner', 'Executor'],
    'parse vs load vs decode' => ['Parser', 'Loader', 'Decoder'],
    'document vs definition vs spec' => ['Document', 'Definition', 'Spec'],
    'fetch vs resolve vs retrieve' => ['Fetcher', 'Resolver', 'Retriever'],
    'state vs status' => ['State', 'Status'],
    'registry vs store vs repository' => ['Registry', 'Store', 'Repository'],
    'validate vs verify vs check' => ['Validator', 'Verifier', 'Check'],
    'workflow vs process vs flow' => ['Workflow', 'Process', 'Flow'],
    'render vs generate' => ['Render', 'Generator'],
];

/**
 * @param array<string, list<ScannedFile>> $core
 * @param array<string, list<ScannedFile>> $laravel
 */
function render(array $core, array $laravel): string
{
    $names = [];
    foreach ([['core', $core], ['laravel', $laravel]] as [$package, $modules]) {
        foreach ($modules as $module => $files) {
            foreach ($files as $file) {
                $names[$file->className][] = [
                    'fqcn' => $file->namespace . '\\' . $file->className,
                    'package' => $package,
                    'dir' => $file->relativeDir === '' ? '(root)' : $file->relativeDir,
                ];
            }
        }
    }
    ksort($names);

    // --- synonyms ---
    $lines = [BANNER];
    $lines[] = '## Synonym clusters';
    $lines[] = '';
    $foundGroups = 0;
    foreach (SYNONYM_GROUPS as $concept => $members) {
        $present = [];
        foreach ($members as $member) {
            foreach ($names as $className => $locations) {
                if (str_contains($className, $member)) {
                    $present[$member] = [...($present[$member] ?? []), $className];
                }
            }
        }
        if (count($present) < 2) {
            continue;
        }
        $foundGroups++;
        ksort($present);
        $lines[] = sprintf('### %s', $concept);
        $lines[] = '';
        foreach ($present as $member => $classNames) {
            $unique = array_values(array_unique($classNames));
            sort($unique);
            $examples = implode(', ', array_slice(array_map(fn (string $c): string => '`' . $c . '`', $unique), 0, 4));
            $more = count($unique) > 4 ? sprintf(' + %d more', count($unique) - 4) : '';
            $lines[] = sprintf('- **%s**: %s%s (%d types)', $member, $examples, $more, count($unique));
        }
        $lines[] = '';
    }
    if ($foundGroups === 0) {
        $lines[] = '_None detected._';
        $lines[] = '';
    }

    // --- homonyms ---
    $lines[] = '## Homonyms (same name, multiple homes)';
    $lines[] = '';
    $lines[] = '| Name | Locations | Packages |';
    $lines[] = '|---|---|---|';
    $homonyms = 0;
    foreach ($names as $className => $locations) {
        if (count($locations) < 2) {
            continue;
        }
        $homonyms++;
        $cells = [];
        $packages = [];
        foreach ($locations as $loc) {
            $cells[] = '`' . str_replace('Alama\\Arazzo\\', '', (string) $loc['fqcn']) . '`';
            $packages[$loc['package']] = true;
        }
        $lines[] = sprintf('| `%s` | %s | %s |', $className, implode('<br/>', $cells), implode(', ', array_keys($packages)));
    }
    if ($homonyms === 0) {
        $lines[] = '| — | — | — |';
    }

    return implode("\n", $lines) . "\n";
}
