<?php

declare(strict_types=1);

namespace ArazzoDocs\ValidatorRulesDoc;

use ArazzoDocs\ScannedFile;

const BANNER = <<<'MD'
<!-- GENERATED by scripts/generate-docs.php — DO NOT EDIT.
     Refreshed automatically on every commit (see .githooks/pre-commit). -->

# Generated: Validator Rules Taxonomy

Every conformance rule in `packages/core/src/Validator/Rules`, grouped by the
document area it governs (derived from rule-name prefixes). Regenerated before
every commit.

MD;

/**
 * @param  array<string, list<ScannedFile>>  $core
 */
function render(array $core): string
{
    $rules = [];
    foreach ($core['Validator'] ?? [] as $file) {
        if ($file->relativeDir === 'Validator/Rules' && !$file->isInterface) {
            $rules[] = $file->className;
        }
    }
    sort($rules);

    $groups = [];
    foreach ($rules as $rule) {
        preg_match('/^(Document|Workflow|Step|Expression|Action|Source|Self|Selector|Parameter|Components|AsyncApi|Doc|Extensions)/', $rule, $m);
        $group = match ($m[1] ?? '') {
            'Document', 'Doc' => 'Document-level',
            'Workflow' => 'Workflow-level',
            'Step' => 'Step-level',
            'Expression' => 'Expressions',
            'Action' => 'Actions',
            'Source', 'Self' => 'Sources',
            'Selector' => 'Selectors',
            'Parameter' => 'Parameters',
            'Components' => 'Components',
            'AsyncApi' => 'AsyncAPI',
            'Extensions' => 'Specification extensions',
            default => 'General',
        };
        $groups[$group][] = $rule;
    }
    ksort($groups);

    $lines = [BANNER, '```mermaid', 'flowchart TD'];
    $lines[] = '    ROOT["Validator rules ('.count($rules).')"]';

    foreach ($groups as $group => $groupRules) {
        $gid = 'G_'.preg_replace('/[^A-Za-z0-9_]/', '_', $group);
        $lines[] = sprintf('    %s["%s"]', $gid, $group.' — '.count($groupRules));
        $lines[] = sprintf('    ROOT --> %s', $gid);
        foreach ($groupRules as $rule) {
            $rid = 'R_'.preg_replace('/[^A-Za-z0-9_]/', '_', $rule);
            $label = preg_replace('/Rule$/', '', $rule);
            $lines[] = sprintf('    %s["%s"]', $rid, $label);
            $lines[] = sprintf('    %s --> %s', $gid, $rid);
        }
    }

    $lines[] = '```';
    $lines[] = '';
    $lines[] = '| Group | Rules |';
    $lines[] = '|---|---|';
    foreach ($groups as $group => $groupRules) {
        $cells = implode(', ', array_map(static fn (string $r): string => '`'.$r.'`', $groupRules));
        $lines[] = "| **{$group}** | {$cells} |";
    }

    return implode("\n", $lines)."\n";
}
