<?php

declare(strict_types=1);

arch('runner does not depend on illuminate framework')
    ->expect('Alama\Arazzo\Runner\Execution')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Runner\State')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Runner\Events')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Runner\Policy')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Runner\Jobs')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Runner\Protocol')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Runner\Async')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Runner\Telemetry')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Runner\Infrastructure')
    ->not->toUse('Illuminate');

arch('runner does not leak expression internals')
    ->expect('Alama\Arazzo\Expression')
    ->not->toUse('Alama\Arazzo\Expression\ExpressionEngine')
    ->expect('Alama\Arazzo\Runner\Execution')
    ->not->toUse('Alama\Arazzo\Cli\Console')
    ->not->toUse('Alama\Arazzo\Cli\Generator')
    ->not->toUse('Alama\Arazzo\Cli\Renderer')
    ->expect('Alama\Arazzo\Runner\State')
    ->not->toUse('Alama\Arazzo\Cli\Console')
    ->expect('Alama\Arazzo\Runner\Events')
    ->not->toUse('Alama\Arazzo\Cli\Console')
    ->expect('Alama\Arazzo\Runner\Policy')
    ->not->toUse('Alama\Arazzo\Cli\Console')
    ->expect('Alama\Arazzo\Runner\Jobs')
    ->not->toUse('Alama\Arazzo\Cli\Console')
    ->expect('Alama\Arazzo\Runner\Protocol')
    ->not->toUse('Alama\Arazzo\Cli\Console')
    ->expect('Alama\Arazzo\Runner\Async')
    ->not->toUse('Alama\Arazzo\Cli\Console')
    ->expect('Alama\Arazzo\Runner\Telemetry')
    ->not->toUse('Alama\Arazzo\Cli\Console')
    ->expect('Alama\Arazzo\Runner\Infrastructure')
    ->not->toUse('Alama\Arazzo\Cli\Console');
