<?php

declare(strict_types=1);

arch('runner does not depend on illuminate framework')
    ->expect('Alama\Arazzo\Execution')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\State')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Events')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Policy')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Jobs')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Protocol')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Async')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Telemetry')
    ->not->toUse('Illuminate')
    ->expect('Alama\Arazzo\Infrastructure')
    ->not->toUse('Illuminate');

arch('runner does not leak cli internals')
    ->expect('Alama\Arazzo\Execution')
    ->not->toUse('Alama\Arazzo\Console')
    ->not->toUse('Alama\Arazzo\Generator')
    ->not->toUse('Alama\Arazzo\Renderer')
    ->expect('Alama\Arazzo\State')
    ->not->toUse('Alama\Arazzo\Console')
    ->expect('Alama\Arazzo\Events')
    ->not->toUse('Alama\Arazzo\Console')
    ->expect('Alama\Arazzo\Policy')
    ->not->toUse('Alama\Arazzo\Console')
    ->expect('Alama\Arazzo\Jobs')
    ->not->toUse('Alama\Arazzo\Console')
    ->expect('Alama\Arazzo\Protocol')
    ->not->toUse('Alama\Arazzo\Console')
    ->expect('Alama\Arazzo\Async')
    ->not->toUse('Alama\Arazzo\Console')
    ->expect('Alama\Arazzo\Telemetry')
    ->not->toUse('Alama\Arazzo\Console')
    ->expect('Alama\Arazzo\Infrastructure')
    ->not->toUse('Alama\Arazzo\Console');
