name: CI

on:
  push:
    branches:
      - main
    paths:
      - '**.php'
      - '.github/workflows/ci.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'
      - 'phpstan.neon.dist'
      - '**/phpstan.neon.dist'
      - '**/phpstan-baseline.neon'
      - 'pint.json'
  pull_request:
    paths:
      - '**.php'
      - '.github/workflows/ci.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'
      - 'phpstan.neon.dist'
      - '**/phpstan.neon.dist'
      - '**/phpstan-baseline.neon'
      - 'pint.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  style:
    name: Code Style
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check PHP code style
        uses: aglipanci/laravel-pint-action@2.6
        with:
          testMode: true

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          cache: composer
      - name: Install composer dependencies
        run: |
          composer update --no-progress --prefer-dist --no-interaction
          cd packages/core
          composer update --no-progress --prefer-dist --no-interaction
          cd ../laravel
          composer update --no-progress --prefer-dist --no-interaction
          cd ../..
      - name: Run PHPStan
        run: composer run analyse

  test:
    name: Test P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: ['8.4']
        laravel: ['13.*']
        stability: [prefer-stable]
        include:
          - laravel: 13.*
            testbench: 11.*
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
          cache: composer
      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Install dependencies
        run: |
          composer update --no-progress --${{ matrix.stability }} --prefer-dist --no-interaction
          cd packages/core
          composer update --no-progress --${{ matrix.stability }} --prefer-dist --no-interaction
          cd ../laravel
          composer require "illuminate/contracts:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --no-progress --${{ matrix.stability }} --prefer-dist --no-interaction
          cd ../..
      - name: Execute tests
        run: composer run test
